# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: Publish Docker Image
description: This workflow automates the process of pushing a Docker image to AWS ECR and pulling it from an EC2 instance.

inputs:
  docker-image-tag:
    description: The tag of the Docker image that you want to publish to AWS ECR. This should be in the format `repository:tag`.
    required: true

outputs:
  docker-image-remote-tag:
    description: The remote tag of the Docker image deployed to AWS ECR in the format `registry/repository:tag`.
    value: "${{ steps.push-docker-image.outputs.docker-image-remote-tag }}"

runs:
  using: composite
  steps:
  - name: Push Docker image
    id: push-docker-image
    uses: ./.github/actions/docker-image-push
    with:
      docker-image-tag: ${{ inputs.docker-image-tag }}

  - name: Pull Docker image
    uses: ./.github/actions/docker-image-pull
    with:
      docker-image-remote-tag: ${{ steps.push-docker-image.outputs.docker-image-remote-tag }}
