// Copyright 2024 Block, Inc. <btcm-sw-team@squareup.com>.
//
// File: miner_telemetry_api.proto
// Description: gRPC server-streaming API exposed by the on-rig
//              telemetry-service. Streams OTLP metrics and OTLP logs
//              aggregated from all services on the rig to an off-rig client
//              (otlp-bridge). Each batch carries a prost-encoded OTLP request
//              as opaque bytes so the bridge can pass it through to a
//              Prometheus / OTel collector without transcoding.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.22.5
// source: miner_telemetry_api.proto

package minertelemetry

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Minimum log severity a StreamLogs client wants forwarded. Services only
// publish INFO and above to the telemetry channel, so the meaningful floors
// are INFO/WARN/ERROR. The server maps these to OTLP severity numbers when
// filtering.
type LogSeverity int32

const (
	// Unset. The server applies its default floor (WARN), preserving the
	// behavior of clients that don't set min_severity.
	LogSeverity_LOG_SEVERITY_UNSPECIFIED LogSeverity = 0
	LogSeverity_LOG_SEVERITY_INFO        LogSeverity = 1
	LogSeverity_LOG_SEVERITY_WARN        LogSeverity = 2
	LogSeverity_LOG_SEVERITY_ERROR       LogSeverity = 3
)

// Enum value maps for LogSeverity.
var (
	LogSeverity_name = map[int32]string{
		0: "LOG_SEVERITY_UNSPECIFIED",
		1: "LOG_SEVERITY_INFO",
		2: "LOG_SEVERITY_WARN",
		3: "LOG_SEVERITY_ERROR",
	}
	LogSeverity_value = map[string]int32{
		"LOG_SEVERITY_UNSPECIFIED": 0,
		"LOG_SEVERITY_INFO":        1,
		"LOG_SEVERITY_WARN":        2,
		"LOG_SEVERITY_ERROR":       3,
	}
)

func (x LogSeverity) Enum() *LogSeverity {
	p := new(LogSeverity)
	*p = x
	return p
}

func (x LogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_miner_telemetry_api_proto_enumTypes[0].Descriptor()
}

func (LogSeverity) Type() protoreflect.EnumType {
	return &file_miner_telemetry_api_proto_enumTypes[0]
}

func (x LogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSeverity.Descriptor instead.
func (LogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_miner_telemetry_api_proto_rawDescGZIP(), []int{0}
}

type StreamMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional service-name filter. Empty list streams every service.
	ServiceNames  []string `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_miner_telemetry_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_miner_telemetry_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_miner_telemetry_api_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMetricsRequest) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

type MetricsBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prost-encoded
	// opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest.
	// Treated as opaque bytes on the wire so the rpc crate does not need the
	// OTLP message types compiled in.
	OtlpPayload []byte `protobuf:"bytes,1,opt,name=otlp_payload,json=otlpPayload,proto3" json:"otlp_payload,omitempty"`
	// Server wall-clock time at which this batch was emitted.
	EmittedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsBatch) Reset() {
	*x = MetricsBatch{}
	mi := &file_miner_telemetry_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsBatch) ProtoMessage() {}

func (x *MetricsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_miner_telemetry_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsBatch.ProtoReflect.Descriptor instead.
func (*MetricsBatch) Descriptor() ([]byte, []int) {
	return file_miner_telemetry_api_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsBatch) GetOtlpPayload() []byte {
	if x != nil {
		return x.OtlpPayload
	}
	return nil
}

func (x *MetricsBatch) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

type StreamLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional service-name filter. Empty list streams every service.
	ServiceNames []string `protobuf:"bytes,1,rep,name=service_names,json=serviceNames,proto3" json:"service_names,omitempty"`
	// Minimum severity to include. Unset (UNSPECIFIED) means WARN.
	MinSeverity   LogSeverity `protobuf:"varint,2,opt,name=min_severity,json=minSeverity,proto3,enum=miner_telemetry_api.LogSeverity" json:"min_severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_miner_telemetry_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_miner_telemetry_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_miner_telemetry_api_proto_rawDescGZIP(), []int{2}
}

func (x *StreamLogsRequest) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

func (x *StreamLogsRequest) GetMinSeverity() LogSeverity {
	if x != nil {
		return x.MinSeverity
	}
	return LogSeverity_LOG_SEVERITY_UNSPECIFIED
}

type LogsBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prost-encoded
	// opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.
	OtlpPayload   []byte `protobuf:"bytes,1,opt,name=otlp_payload,json=otlpPayload,proto3" json:"otlp_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsBatch) Reset() {
	*x = LogsBatch{}
	mi := &file_miner_telemetry_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsBatch) ProtoMessage() {}

func (x *LogsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_miner_telemetry_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsBatch.ProtoReflect.Descriptor instead.
func (*LogsBatch) Descriptor() ([]byte, []int) {
	return file_miner_telemetry_api_proto_rawDescGZIP(), []int{3}
}

func (x *LogsBatch) GetOtlpPayload() []byte {
	if x != nil {
		return x.OtlpPayload
	}
	return nil
}

var File_miner_telemetry_api_proto protoreflect.FileDescriptor

var file_miner_telemetry_api_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61, 0x70, 0x69,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3b, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x6c,
	0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x74, 0x6c, 0x70, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x74, 0x6c, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x65, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x7d, 0x0a, 0x11,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x65,
	0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6d,
	0x69, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x0b,
	0x6d, 0x69, 0x6e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x09, 0x4c,
	0x6f, 0x67, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x74, 0x6c, 0x70,
	0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x6f, 0x74, 0x6c, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x71, 0x0a, 0x0b, 0x4c,
	0x6f, 0x67, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x18, 0x4c, 0x4f,
	0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x4f, 0x47, 0x5f,
	0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x01, 0x12,
	0x15, 0x0a, 0x11, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f,
	0x57, 0x41, 0x52, 0x4e, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x4f, 0x47, 0x5f, 0x53, 0x45,
	0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x32, 0xcc,
	0x01, 0x0a, 0x11, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x41, 0x70, 0x69, 0x12, 0x5f, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x29, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x30, 0x01, 0x12, 0x56, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4c,
	0x6f, 0x67, 0x73, 0x12, 0x26, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x30, 0x01, 0x42, 0x15, 0x5a,
	0x13, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6d, 0x69, 0x6e, 0x65, 0x72,
	0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_miner_telemetry_api_proto_rawDescOnce sync.Once
	file_miner_telemetry_api_proto_rawDescData []byte
)

func file_miner_telemetry_api_proto_rawDescGZIP() []byte {
	file_miner_telemetry_api_proto_rawDescOnce.Do(func() {
		file_miner_telemetry_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_miner_telemetry_api_proto_rawDesc), len(file_miner_telemetry_api_proto_rawDesc)))
	})
	return file_miner_telemetry_api_proto_rawDescData
}

var file_miner_telemetry_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_miner_telemetry_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_miner_telemetry_api_proto_goTypes = []any{
	(LogSeverity)(0),              // 0: miner_telemetry_api.LogSeverity
	(*StreamMetricsRequest)(nil),  // 1: miner_telemetry_api.StreamMetricsRequest
	(*MetricsBatch)(nil),          // 2: miner_telemetry_api.MetricsBatch
	(*StreamLogsRequest)(nil),     // 3: miner_telemetry_api.StreamLogsRequest
	(*LogsBatch)(nil),             // 4: miner_telemetry_api.LogsBatch
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_miner_telemetry_api_proto_depIdxs = []int32{
	5, // 0: miner_telemetry_api.MetricsBatch.emitted_at:type_name -> google.protobuf.Timestamp
	0, // 1: miner_telemetry_api.StreamLogsRequest.min_severity:type_name -> miner_telemetry_api.LogSeverity
	1, // 2: miner_telemetry_api.MinerTelemetryApi.StreamMetrics:input_type -> miner_telemetry_api.StreamMetricsRequest
	3, // 3: miner_telemetry_api.MinerTelemetryApi.StreamLogs:input_type -> miner_telemetry_api.StreamLogsRequest
	2, // 4: miner_telemetry_api.MinerTelemetryApi.StreamMetrics:output_type -> miner_telemetry_api.MetricsBatch
	4, // 5: miner_telemetry_api.MinerTelemetryApi.StreamLogs:output_type -> miner_telemetry_api.LogsBatch
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_miner_telemetry_api_proto_init() }
func file_miner_telemetry_api_proto_init() {
	if File_miner_telemetry_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_miner_telemetry_api_proto_rawDesc), len(file_miner_telemetry_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_miner_telemetry_api_proto_goTypes,
		DependencyIndexes: file_miner_telemetry_api_proto_depIdxs,
		EnumInfos:         file_miner_telemetry_api_proto_enumTypes,
		MessageInfos:      file_miner_telemetry_api_proto_msgTypes,
	}.Build()
	File_miner_telemetry_api_proto = out.File
	file_miner_telemetry_api_proto_goTypes = nil
	file_miner_telemetry_api_proto_depIdxs = nil
}
