// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/schedule/processor.go
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/schedule/mock_command_dispatcher_test.go -package=schedule -source=internal/domain/schedule/processor.go CommandDispatcher
//

// Package schedule is a generated GoMock package.
package schedule

import (
	context "context"
	reflect "reflect"

	minercommandv1 "github.com/block/proto-fleet/server/generated/grpc/minercommand/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandDispatcher is a mock of CommandDispatcher interface.
type MockCommandDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockCommandDispatcherMockRecorder
	isgomock struct{}
}

// MockCommandDispatcherMockRecorder is the mock recorder for MockCommandDispatcher.
type MockCommandDispatcherMockRecorder struct {
	mock *MockCommandDispatcher
}

// NewMockCommandDispatcher creates a new mock instance.
func NewMockCommandDispatcher(ctrl *gomock.Controller) *MockCommandDispatcher {
	mock := &MockCommandDispatcher{ctrl: ctrl}
	mock.recorder = &MockCommandDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandDispatcher) EXPECT() *MockCommandDispatcherMockRecorder {
	return m.recorder
}

// Reboot mocks base method.
func (m *MockCommandDispatcher) Reboot(ctx context.Context, selector *minercommandv1.DeviceSelector) (*minercommandv1.RebootResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx, selector)
	ret0, _ := ret[0].(*minercommandv1.RebootResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reboot indicates an expected call of Reboot.
func (mr *MockCommandDispatcherMockRecorder) Reboot(ctx, selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockCommandDispatcher)(nil).Reboot), ctx, selector)
}

// SetPowerTarget mocks base method.
func (m *MockCommandDispatcher) SetPowerTarget(ctx context.Context, selector *minercommandv1.DeviceSelector, mode minercommandv1.PerformanceMode) (*minercommandv1.SetPowerTargetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPowerTarget", ctx, selector, mode)
	ret0, _ := ret[0].(*minercommandv1.SetPowerTargetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPowerTarget indicates an expected call of SetPowerTarget.
func (mr *MockCommandDispatcherMockRecorder) SetPowerTarget(ctx, selector, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPowerTarget", reflect.TypeOf((*MockCommandDispatcher)(nil).SetPowerTarget), ctx, selector, mode)
}

// StopMining mocks base method.
func (m *MockCommandDispatcher) StopMining(ctx context.Context, selector *minercommandv1.DeviceSelector) (*minercommandv1.StopMiningResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx, selector)
	ret0, _ := ret[0].(*minercommandv1.StopMiningResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopMining indicates an expected call of StopMining.
func (mr *MockCommandDispatcherMockRecorder) StopMining(ctx, selector any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockCommandDispatcher)(nil).StopMining), ctx, selector)
}
