// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks/mock_client.go -package=mocks AntminerClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	antminer "github.com/block/proto-fleet/plugin/antminer/pkg/antminer"
	rpc "github.com/block/proto-fleet/plugin/antminer/pkg/antminer/rpc"
	web "github.com/block/proto-fleet/plugin/antminer/pkg/antminer/web"
	sdk "github.com/block/proto-fleet/server/sdk/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockAntminerClient is a mock of AntminerClient interface.
type MockAntminerClient struct {
	ctrl     *gomock.Controller
	recorder *MockAntminerClientMockRecorder
	isgomock struct{}
}

// MockAntminerClientMockRecorder is the mock recorder for MockAntminerClient.
type MockAntminerClientMockRecorder struct {
	mock *MockAntminerClient
}

// NewMockAntminerClient creates a new mock instance.
func NewMockAntminerClient(ctrl *gomock.Controller) *MockAntminerClient {
	mock := &MockAntminerClient{ctrl: ctrl}
	mock.recorder = &MockAntminerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAntminerClient) EXPECT() *MockAntminerClientMockRecorder {
	return m.recorder
}

// BlinkLED mocks base method.
func (m *MockAntminerClient) BlinkLED(ctx context.Context, duration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlinkLED", ctx, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlinkLED indicates an expected call of BlinkLED.
func (mr *MockAntminerClientMockRecorder) BlinkLED(ctx, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlinkLED", reflect.TypeOf((*MockAntminerClient)(nil).BlinkLED), ctx, duration)
}

// ChangePassword mocks base method.
func (m *MockAntminerClient) ChangePassword(ctx context.Context, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAntminerClientMockRecorder) ChangePassword(ctx, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAntminerClient)(nil).ChangePassword), ctx, currentPassword, newPassword)
}

// Close mocks base method.
func (m *MockAntminerClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAntminerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAntminerClient)(nil).Close))
}

// GetDeviceInfo mocks base method.
func (m *MockAntminerClient) GetDeviceInfo(ctx context.Context) (*antminer.DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceInfo", ctx)
	ret0, _ := ret[0].(*antminer.DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceInfo indicates an expected call of GetDeviceInfo.
func (mr *MockAntminerClientMockRecorder) GetDeviceInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceInfo", reflect.TypeOf((*MockAntminerClient)(nil).GetDeviceInfo), ctx)
}

// GetDevs mocks base method.
func (m *MockAntminerClient) GetDevs(ctx context.Context) (*rpc.DevsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevs", ctx)
	ret0, _ := ret[0].(*rpc.DevsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevs indicates an expected call of GetDevs.
func (mr *MockAntminerClientMockRecorder) GetDevs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevs", reflect.TypeOf((*MockAntminerClient)(nil).GetDevs), ctx)
}

// GetLogs mocks base method.
func (m *MockAntminerClient) GetLogs(ctx context.Context, since *time.Time, maxLines int) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", ctx, since, maxLines)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockAntminerClientMockRecorder) GetLogs(ctx, since, maxLines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockAntminerClient)(nil).GetLogs), ctx, since, maxLines)
}

// GetMinerConfig mocks base method.
func (m *MockAntminerClient) GetMinerConfig(ctx context.Context) (*web.MinerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerConfig", ctx)
	ret0, _ := ret[0].(*web.MinerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerConfig indicates an expected call of GetMinerConfig.
func (mr *MockAntminerClientMockRecorder) GetMinerConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerConfig", reflect.TypeOf((*MockAntminerClient)(nil).GetMinerConfig), ctx)
}

// GetPools mocks base method.
func (m *MockAntminerClient) GetPools(ctx context.Context) (*rpc.PoolsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPools", ctx)
	ret0, _ := ret[0].(*rpc.PoolsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPools indicates an expected call of GetPools.
func (mr *MockAntminerClientMockRecorder) GetPools(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPools", reflect.TypeOf((*MockAntminerClient)(nil).GetPools), ctx)
}

// GetStatsInfo mocks base method.
func (m *MockAntminerClient) GetStatsInfo(ctx context.Context) (*web.StatsInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsInfo", ctx)
	ret0, _ := ret[0].(*web.StatsInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsInfo indicates an expected call of GetStatsInfo.
func (mr *MockAntminerClientMockRecorder) GetStatsInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsInfo", reflect.TypeOf((*MockAntminerClient)(nil).GetStatsInfo), ctx)
}

// GetStatus mocks base method.
func (m *MockAntminerClient) GetStatus(ctx context.Context) (*antminer.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx)
	ret0, _ := ret[0].(*antminer.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockAntminerClientMockRecorder) GetStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockAntminerClient)(nil).GetStatus), ctx)
}

// GetSummary mocks base method.
func (m *MockAntminerClient) GetSummary(ctx context.Context) (*rpc.SummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx)
	ret0, _ := ret[0].(*rpc.SummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockAntminerClientMockRecorder) GetSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockAntminerClient)(nil).GetSummary), ctx)
}

// GetTelemetry mocks base method.
func (m *MockAntminerClient) GetTelemetry(ctx context.Context) (*antminer.Telemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetry", ctx)
	ret0, _ := ret[0].(*antminer.Telemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelemetry indicates an expected call of GetTelemetry.
func (mr *MockAntminerClientMockRecorder) GetTelemetry(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetry", reflect.TypeOf((*MockAntminerClient)(nil).GetTelemetry), ctx)
}

// GetVersion mocks base method.
func (m *MockAntminerClient) GetVersion(ctx context.Context) (*rpc.VersionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(*rpc.VersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockAntminerClientMockRecorder) GetVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockAntminerClient)(nil).GetVersion), ctx)
}

// Pair mocks base method.
func (m *MockAntminerClient) Pair(ctx context.Context, credentials sdk.UsernamePassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pair", ctx, credentials)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pair indicates an expected call of Pair.
func (mr *MockAntminerClientMockRecorder) Pair(ctx, credentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pair", reflect.TypeOf((*MockAntminerClient)(nil).Pair), ctx, credentials)
}

// Reboot mocks base method.
func (m *MockAntminerClient) Reboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockAntminerClientMockRecorder) Reboot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockAntminerClient)(nil).Reboot), ctx)
}

// SetCoolingMode mocks base method.
func (m *MockAntminerClient) SetCoolingMode(ctx context.Context, mode web.CoolingMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoolingMode", ctx, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoolingMode indicates an expected call of SetCoolingMode.
func (mr *MockAntminerClientMockRecorder) SetCoolingMode(ctx, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoolingMode", reflect.TypeOf((*MockAntminerClient)(nil).SetCoolingMode), ctx, mode)
}

// SetCredentials mocks base method.
func (m *MockAntminerClient) SetCredentials(credentials sdk.UsernamePassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCredentials", credentials)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCredentials indicates an expected call of SetCredentials.
func (mr *MockAntminerClientMockRecorder) SetCredentials(credentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCredentials", reflect.TypeOf((*MockAntminerClient)(nil).SetCredentials), credentials)
}

// SetMinerConfig mocks base method.
func (m *MockAntminerClient) SetMinerConfig(ctx context.Context, config *web.MinerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMinerConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMinerConfig indicates an expected call of SetMinerConfig.
func (mr *MockAntminerClientMockRecorder) SetMinerConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMinerConfig", reflect.TypeOf((*MockAntminerClient)(nil).SetMinerConfig), ctx, config)
}

// StartMining mocks base method.
func (m *MockAntminerClient) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockAntminerClientMockRecorder) StartMining(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockAntminerClient)(nil).StartMining), ctx)
}

// StopMining mocks base method.
func (m *MockAntminerClient) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockAntminerClientMockRecorder) StopMining(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockAntminerClient)(nil).StopMining), ctx)
}

// UpdatePools mocks base method.
func (m *MockAntminerClient) UpdatePools(ctx context.Context, pools []antminer.Pool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePools", ctx, pools)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePools indicates an expected call of UpdatePools.
func (mr *MockAntminerClientMockRecorder) UpdatePools(ctx, pools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePools", reflect.TypeOf((*MockAntminerClient)(nil).UpdatePools), ctx, pools)
}

// UploadFirmware mocks base method.
func (m *MockAntminerClient) UploadFirmware(ctx context.Context, firmware sdk.FirmwareFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFirmware", ctx, firmware)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFirmware indicates an expected call of UploadFirmware.
func (mr *MockAntminerClientMockRecorder) UploadFirmware(ctx, firmware any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFirmware", reflect.TypeOf((*MockAntminerClient)(nil).UploadFirmware), ctx, firmware)
}
