// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_web_api_client.go -package=mocks WebAPIClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	web "github.com/block/proto-fleet/plugin/antminer/pkg/antminer/web"
	sdk "github.com/block/proto-fleet/server/sdk/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockWebAPIClient is a mock of WebAPIClient interface.
type MockWebAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockWebAPIClientMockRecorder
	isgomock struct{}
}

// MockWebAPIClientMockRecorder is the mock recorder for MockWebAPIClient.
type MockWebAPIClientMockRecorder struct {
	mock *MockWebAPIClient
}

// NewMockWebAPIClient creates a new mock instance.
func NewMockWebAPIClient(ctrl *gomock.Controller) *MockWebAPIClient {
	mock := &MockWebAPIClient{ctrl: ctrl}
	mock.recorder = &MockWebAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebAPIClient) EXPECT() *MockWebAPIClientMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockWebAPIClient) ChangePassword(ctx context.Context, connInfo *web.AntminerConnectionInfo, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, connInfo, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockWebAPIClientMockRecorder) ChangePassword(ctx, connInfo, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockWebAPIClient)(nil).ChangePassword), ctx, connInfo, currentPassword, newPassword)
}

// GetKernelLog mocks base method.
func (m *MockWebAPIClient) GetKernelLog(ctx context.Context, connInfo *web.AntminerConnectionInfo) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKernelLog", ctx, connInfo)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKernelLog indicates an expected call of GetKernelLog.
func (mr *MockWebAPIClientMockRecorder) GetKernelLog(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKernelLog", reflect.TypeOf((*MockWebAPIClient)(nil).GetKernelLog), ctx, connInfo)
}

// GetMinerConfig mocks base method.
func (m *MockWebAPIClient) GetMinerConfig(ctx context.Context, connInfo *web.AntminerConnectionInfo) (*web.MinerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerConfig", ctx, connInfo)
	ret0, _ := ret[0].(*web.MinerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerConfig indicates an expected call of GetMinerConfig.
func (mr *MockWebAPIClientMockRecorder) GetMinerConfig(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerConfig", reflect.TypeOf((*MockWebAPIClient)(nil).GetMinerConfig), ctx, connInfo)
}

// GetMinerSummary mocks base method.
func (m *MockWebAPIClient) GetMinerSummary(ctx context.Context, connInfo *web.AntminerConnectionInfo) (*web.MinerSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerSummary", ctx, connInfo)
	ret0, _ := ret[0].(*web.MinerSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerSummary indicates an expected call of GetMinerSummary.
func (mr *MockWebAPIClientMockRecorder) GetMinerSummary(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerSummary", reflect.TypeOf((*MockWebAPIClient)(nil).GetMinerSummary), ctx, connInfo)
}

// GetNetworkInfo mocks base method.
func (m *MockWebAPIClient) GetNetworkInfo(ctx context.Context, connInfo *web.AntminerConnectionInfo) (*web.NetworkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkInfo", ctx, connInfo)
	ret0, _ := ret[0].(*web.NetworkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkInfo indicates an expected call of GetNetworkInfo.
func (mr *MockWebAPIClientMockRecorder) GetNetworkInfo(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkInfo", reflect.TypeOf((*MockWebAPIClient)(nil).GetNetworkInfo), ctx, connInfo)
}

// GetStatsInfo mocks base method.
func (m *MockWebAPIClient) GetStatsInfo(ctx context.Context, connInfo *web.AntminerConnectionInfo) (*web.StatsInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsInfo", ctx, connInfo)
	ret0, _ := ret[0].(*web.StatsInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsInfo indicates an expected call of GetStatsInfo.
func (mr *MockWebAPIClientMockRecorder) GetStatsInfo(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsInfo", reflect.TypeOf((*MockWebAPIClient)(nil).GetStatsInfo), ctx, connInfo)
}

// GetSystemInfo mocks base method.
func (m *MockWebAPIClient) GetSystemInfo(ctx context.Context, connInfo *web.AntminerConnectionInfo) (*web.SystemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemInfo", ctx, connInfo)
	ret0, _ := ret[0].(*web.SystemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemInfo indicates an expected call of GetSystemInfo.
func (mr *MockWebAPIClientMockRecorder) GetSystemInfo(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemInfo", reflect.TypeOf((*MockWebAPIClient)(nil).GetSystemInfo), ctx, connInfo)
}

// Reboot mocks base method.
func (m *MockWebAPIClient) Reboot(ctx context.Context, connInfo *web.AntminerConnectionInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx, connInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockWebAPIClientMockRecorder) Reboot(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockWebAPIClient)(nil).Reboot), ctx, connInfo)
}

// SetMinerConfig mocks base method.
func (m *MockWebAPIClient) SetMinerConfig(ctx context.Context, connInfo *web.AntminerConnectionInfo, config *web.MinerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMinerConfig", ctx, connInfo, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMinerConfig indicates an expected call of SetMinerConfig.
func (mr *MockWebAPIClientMockRecorder) SetMinerConfig(ctx, connInfo, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMinerConfig", reflect.TypeOf((*MockWebAPIClient)(nil).SetMinerConfig), ctx, connInfo, config)
}

// StartBlink mocks base method.
func (m *MockWebAPIClient) StartBlink(ctx context.Context, connInfo *web.AntminerConnectionInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBlink", ctx, connInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartBlink indicates an expected call of StartBlink.
func (mr *MockWebAPIClientMockRecorder) StartBlink(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBlink", reflect.TypeOf((*MockWebAPIClient)(nil).StartBlink), ctx, connInfo)
}

// StopBlink mocks base method.
func (m *MockWebAPIClient) StopBlink(ctx context.Context, connInfo *web.AntminerConnectionInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopBlink", ctx, connInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopBlink indicates an expected call of StopBlink.
func (mr *MockWebAPIClientMockRecorder) StopBlink(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopBlink", reflect.TypeOf((*MockWebAPIClient)(nil).StopBlink), ctx, connInfo)
}

// UploadFirmware mocks base method.
func (m *MockWebAPIClient) UploadFirmware(ctx context.Context, connInfo *web.AntminerConnectionInfo, firmware sdk.FirmwareFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFirmware", ctx, connInfo, firmware)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFirmware indicates an expected call of UploadFirmware.
func (mr *MockWebAPIClientMockRecorder) UploadFirmware(ctx, connInfo, firmware any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFirmware", reflect.TypeOf((*MockWebAPIClient)(nil).UploadFirmware), ctx, connInfo, firmware)
}
