// Code generated by MockGen. DO NOT EDIT.
// Source: ../interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	sdk "github.com/btc-mining/proto-fleet/server/sdk/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceCore is a mock of DeviceCore interface.
type MockDeviceCore struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceCoreMockRecorder
}

// MockDeviceCoreMockRecorder is the mock recorder for MockDeviceCore.
type MockDeviceCoreMockRecorder struct {
	mock *MockDeviceCore
}

// NewMockDeviceCore creates a new mock instance.
func NewMockDeviceCore(ctrl *gomock.Controller) *MockDeviceCore {
	mock := &MockDeviceCore{ctrl: ctrl}
	mock.recorder = &MockDeviceCoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceCore) EXPECT() *MockDeviceCoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDeviceCore) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeviceCoreMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDeviceCore)(nil).Close), ctx)
}

// DescribeDevice mocks base method.
func (m *MockDeviceCore) DescribeDevice(ctx context.Context) (sdk.DeviceInfo, sdk.Capabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDevice", ctx)
	ret0, _ := ret[0].(sdk.DeviceInfo)
	ret1, _ := ret[1].(sdk.Capabilities)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DescribeDevice indicates an expected call of DescribeDevice.
func (mr *MockDeviceCoreMockRecorder) DescribeDevice(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDevice", reflect.TypeOf((*MockDeviceCore)(nil).DescribeDevice), ctx)
}

// ID mocks base method.
func (m *MockDeviceCore) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDeviceCoreMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockDeviceCore)(nil).ID))
}

// Status mocks base method.
func (m *MockDeviceCore) Status(ctx context.Context) (sdk.DeviceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(sdk.DeviceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockDeviceCoreMockRecorder) Status(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockDeviceCore)(nil).Status), ctx)
}

// MockDeviceControl is a mock of DeviceControl interface.
type MockDeviceControl struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceControlMockRecorder
}

// MockDeviceControlMockRecorder is the mock recorder for MockDeviceControl.
type MockDeviceControlMockRecorder struct {
	mock *MockDeviceControl
}

// NewMockDeviceControl creates a new mock instance.
func NewMockDeviceControl(ctrl *gomock.Controller) *MockDeviceControl {
	mock := &MockDeviceControl{ctrl: ctrl}
	mock.recorder = &MockDeviceControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceControl) EXPECT() *MockDeviceControlMockRecorder {
	return m.recorder
}

// BlinkLED mocks base method.
func (m *MockDeviceControl) BlinkLED(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlinkLED", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlinkLED indicates an expected call of BlinkLED.
func (mr *MockDeviceControlMockRecorder) BlinkLED(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlinkLED", reflect.TypeOf((*MockDeviceControl)(nil).BlinkLED), ctx)
}

// Reboot mocks base method.
func (m *MockDeviceControl) Reboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockDeviceControlMockRecorder) Reboot(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockDeviceControl)(nil).Reboot), ctx)
}

// StartMining mocks base method.
func (m *MockDeviceControl) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockDeviceControlMockRecorder) StartMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockDeviceControl)(nil).StartMining), ctx)
}

// StopMining mocks base method.
func (m *MockDeviceControl) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockDeviceControlMockRecorder) StopMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockDeviceControl)(nil).StopMining), ctx)
}

// MockDeviceConfiguration is a mock of DeviceConfiguration interface.
type MockDeviceConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceConfigurationMockRecorder
}

// MockDeviceConfigurationMockRecorder is the mock recorder for MockDeviceConfiguration.
type MockDeviceConfigurationMockRecorder struct {
	mock *MockDeviceConfiguration
}

// NewMockDeviceConfiguration creates a new mock instance.
func NewMockDeviceConfiguration(ctrl *gomock.Controller) *MockDeviceConfiguration {
	mock := &MockDeviceConfiguration{ctrl: ctrl}
	mock.recorder = &MockDeviceConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceConfiguration) EXPECT() *MockDeviceConfigurationMockRecorder {
	return m.recorder
}

// SetCoolingMode mocks base method.
func (m *MockDeviceConfiguration) SetCoolingMode(ctx context.Context, mode sdk.CoolingMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoolingMode", ctx, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoolingMode indicates an expected call of SetCoolingMode.
func (mr *MockDeviceConfigurationMockRecorder) SetCoolingMode(ctx, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoolingMode", reflect.TypeOf((*MockDeviceConfiguration)(nil).SetCoolingMode), ctx, mode)
}

// UpdateMiningPools mocks base method.
func (m *MockDeviceConfiguration) UpdateMiningPools(ctx context.Context, pools []sdk.MiningPoolConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMiningPools", ctx, pools)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMiningPools indicates an expected call of UpdateMiningPools.
func (mr *MockDeviceConfigurationMockRecorder) UpdateMiningPools(ctx, pools interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMiningPools", reflect.TypeOf((*MockDeviceConfiguration)(nil).UpdateMiningPools), ctx, pools)
}

// MockDeviceMaintenance is a mock of DeviceMaintenance interface.
type MockDeviceMaintenance struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceMaintenanceMockRecorder
}

// MockDeviceMaintenanceMockRecorder is the mock recorder for MockDeviceMaintenance.
type MockDeviceMaintenanceMockRecorder struct {
	mock *MockDeviceMaintenance
}

// NewMockDeviceMaintenance creates a new mock instance.
func NewMockDeviceMaintenance(ctrl *gomock.Controller) *MockDeviceMaintenance {
	mock := &MockDeviceMaintenance{ctrl: ctrl}
	mock.recorder = &MockDeviceMaintenanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceMaintenance) EXPECT() *MockDeviceMaintenanceMockRecorder {
	return m.recorder
}

// DownloadLogs mocks base method.
func (m *MockDeviceMaintenance) DownloadLogs(ctx context.Context, since *time.Time, batchLogUUID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLogs", ctx, since, batchLogUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadLogs indicates an expected call of DownloadLogs.
func (mr *MockDeviceMaintenanceMockRecorder) DownloadLogs(ctx, since, batchLogUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLogs", reflect.TypeOf((*MockDeviceMaintenance)(nil).DownloadLogs), ctx, since, batchLogUUID)
}

// FirmwareUpdate mocks base method.
func (m *MockDeviceMaintenance) FirmwareUpdate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirmwareUpdate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirmwareUpdate indicates an expected call of FirmwareUpdate.
func (mr *MockDeviceMaintenanceMockRecorder) FirmwareUpdate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirmwareUpdate", reflect.TypeOf((*MockDeviceMaintenance)(nil).FirmwareUpdate), ctx)
}

// MockDeviceOptional is a mock of DeviceOptional interface.
type MockDeviceOptional struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceOptionalMockRecorder
}

// MockDeviceOptionalMockRecorder is the mock recorder for MockDeviceOptional.
type MockDeviceOptionalMockRecorder struct {
	mock *MockDeviceOptional
}

// NewMockDeviceOptional creates a new mock instance.
func NewMockDeviceOptional(ctrl *gomock.Controller) *MockDeviceOptional {
	mock := &MockDeviceOptional{ctrl: ctrl}
	mock.recorder = &MockDeviceOptionalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceOptional) EXPECT() *MockDeviceOptionalMockRecorder {
	return m.recorder
}

// TryBatchStatus mocks base method.
func (m *MockDeviceOptional) TryBatchStatus(ctx context.Context, ids []string) (map[string]sdk.DeviceMetrics, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryBatchStatus", ctx, ids)
	ret0, _ := ret[0].(map[string]sdk.DeviceMetrics)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryBatchStatus indicates an expected call of TryBatchStatus.
func (mr *MockDeviceOptionalMockRecorder) TryBatchStatus(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryBatchStatus", reflect.TypeOf((*MockDeviceOptional)(nil).TryBatchStatus), ctx, ids)
}

// TryGetTimeSeriesData mocks base method.
func (m *MockDeviceOptional) TryGetTimeSeriesData(ctx context.Context, metricNames []string, startTime, endTime time.Time, granularity *time.Duration, maxPoints int32, pageToken string) ([]sdk.DeviceMetrics, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetTimeSeriesData", ctx, metricNames, startTime, endTime, granularity, maxPoints, pageToken)
	ret0, _ := ret[0].([]sdk.DeviceMetrics)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// TryGetTimeSeriesData indicates an expected call of TryGetTimeSeriesData.
func (mr *MockDeviceOptionalMockRecorder) TryGetTimeSeriesData(ctx, metricNames, startTime, endTime, granularity, maxPoints, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetTimeSeriesData", reflect.TypeOf((*MockDeviceOptional)(nil).TryGetTimeSeriesData), ctx, metricNames, startTime, endTime, granularity, maxPoints, pageToken)
}

// TryGetWebViewURL mocks base method.
func (m *MockDeviceOptional) TryGetWebViewURL(ctx context.Context) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetWebViewURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryGetWebViewURL indicates an expected call of TryGetWebViewURL.
func (mr *MockDeviceOptionalMockRecorder) TryGetWebViewURL(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetWebViewURL", reflect.TypeOf((*MockDeviceOptional)(nil).TryGetWebViewURL), ctx)
}

// TrySubscribe mocks base method.
func (m *MockDeviceOptional) TrySubscribe(ctx context.Context, ids []string) (<-chan sdk.DeviceMetrics, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrySubscribe", ctx, ids)
	ret0, _ := ret[0].(<-chan sdk.DeviceMetrics)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TrySubscribe indicates an expected call of TrySubscribe.
func (mr *MockDeviceOptionalMockRecorder) TrySubscribe(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrySubscribe", reflect.TypeOf((*MockDeviceOptional)(nil).TrySubscribe), ctx, ids)
}

// MockDevice is a mock of Device interface.
type MockDevice struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceMockRecorder
}

// MockDeviceMockRecorder is the mock recorder for MockDevice.
type MockDeviceMockRecorder struct {
	mock *MockDevice
}

// NewMockDevice creates a new mock instance.
func NewMockDevice(ctrl *gomock.Controller) *MockDevice {
	mock := &MockDevice{ctrl: ctrl}
	mock.recorder = &MockDeviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevice) EXPECT() *MockDeviceMockRecorder {
	return m.recorder
}

// BlinkLED mocks base method.
func (m *MockDevice) BlinkLED(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlinkLED", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlinkLED indicates an expected call of BlinkLED.
func (mr *MockDeviceMockRecorder) BlinkLED(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlinkLED", reflect.TypeOf((*MockDevice)(nil).BlinkLED), ctx)
}

// Close mocks base method.
func (m *MockDevice) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeviceMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDevice)(nil).Close), ctx)
}

// DescribeDevice mocks base method.
func (m *MockDevice) DescribeDevice(ctx context.Context) (sdk.DeviceInfo, sdk.Capabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDevice", ctx)
	ret0, _ := ret[0].(sdk.DeviceInfo)
	ret1, _ := ret[1].(sdk.Capabilities)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DescribeDevice indicates an expected call of DescribeDevice.
func (mr *MockDeviceMockRecorder) DescribeDevice(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDevice", reflect.TypeOf((*MockDevice)(nil).DescribeDevice), ctx)
}

// DownloadLogs mocks base method.
func (m *MockDevice) DownloadLogs(ctx context.Context, since *time.Time, batchLogUUID string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLogs", ctx, since, batchLogUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadLogs indicates an expected call of DownloadLogs.
func (mr *MockDeviceMockRecorder) DownloadLogs(ctx, since, batchLogUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLogs", reflect.TypeOf((*MockDevice)(nil).DownloadLogs), ctx, since, batchLogUUID)
}

// FirmwareUpdate mocks base method.
func (m *MockDevice) FirmwareUpdate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirmwareUpdate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirmwareUpdate indicates an expected call of FirmwareUpdate.
func (mr *MockDeviceMockRecorder) FirmwareUpdate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirmwareUpdate", reflect.TypeOf((*MockDevice)(nil).FirmwareUpdate), ctx)
}

// ID mocks base method.
func (m *MockDevice) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDeviceMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockDevice)(nil).ID))
}

// Reboot mocks base method.
func (m *MockDevice) Reboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockDeviceMockRecorder) Reboot(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockDevice)(nil).Reboot), ctx)
}

// SetCoolingMode mocks base method.
func (m *MockDevice) SetCoolingMode(ctx context.Context, mode sdk.CoolingMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoolingMode", ctx, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoolingMode indicates an expected call of SetCoolingMode.
func (mr *MockDeviceMockRecorder) SetCoolingMode(ctx, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoolingMode", reflect.TypeOf((*MockDevice)(nil).SetCoolingMode), ctx, mode)
}

// StartMining mocks base method.
func (m *MockDevice) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockDeviceMockRecorder) StartMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockDevice)(nil).StartMining), ctx)
}

// Status mocks base method.
func (m *MockDevice) Status(ctx context.Context) (sdk.DeviceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(sdk.DeviceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockDeviceMockRecorder) Status(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockDevice)(nil).Status), ctx)
}

// StopMining mocks base method.
func (m *MockDevice) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockDeviceMockRecorder) StopMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockDevice)(nil).StopMining), ctx)
}

// TryBatchStatus mocks base method.
func (m *MockDevice) TryBatchStatus(ctx context.Context, ids []string) (map[string]sdk.DeviceMetrics, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryBatchStatus", ctx, ids)
	ret0, _ := ret[0].(map[string]sdk.DeviceMetrics)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryBatchStatus indicates an expected call of TryBatchStatus.
func (mr *MockDeviceMockRecorder) TryBatchStatus(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryBatchStatus", reflect.TypeOf((*MockDevice)(nil).TryBatchStatus), ctx, ids)
}

// TryGetTimeSeriesData mocks base method.
func (m *MockDevice) TryGetTimeSeriesData(ctx context.Context, metricNames []string, startTime, endTime time.Time, granularity *time.Duration, maxPoints int32, pageToken string) ([]sdk.DeviceMetrics, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetTimeSeriesData", ctx, metricNames, startTime, endTime, granularity, maxPoints, pageToken)
	ret0, _ := ret[0].([]sdk.DeviceMetrics)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// TryGetTimeSeriesData indicates an expected call of TryGetTimeSeriesData.
func (mr *MockDeviceMockRecorder) TryGetTimeSeriesData(ctx, metricNames, startTime, endTime, granularity, maxPoints, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetTimeSeriesData", reflect.TypeOf((*MockDevice)(nil).TryGetTimeSeriesData), ctx, metricNames, startTime, endTime, granularity, maxPoints, pageToken)
}

// TryGetWebViewURL mocks base method.
func (m *MockDevice) TryGetWebViewURL(ctx context.Context) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryGetWebViewURL", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TryGetWebViewURL indicates an expected call of TryGetWebViewURL.
func (mr *MockDeviceMockRecorder) TryGetWebViewURL(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryGetWebViewURL", reflect.TypeOf((*MockDevice)(nil).TryGetWebViewURL), ctx)
}

// TrySubscribe mocks base method.
func (m *MockDevice) TrySubscribe(ctx context.Context, ids []string) (<-chan sdk.DeviceMetrics, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrySubscribe", ctx, ids)
	ret0, _ := ret[0].(<-chan sdk.DeviceMetrics)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TrySubscribe indicates an expected call of TrySubscribe.
func (mr *MockDeviceMockRecorder) TrySubscribe(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrySubscribe", reflect.TypeOf((*MockDevice)(nil).TrySubscribe), ctx, ids)
}

// UpdateMiningPools mocks base method.
func (m *MockDevice) UpdateMiningPools(ctx context.Context, pools []sdk.MiningPoolConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMiningPools", ctx, pools)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMiningPools indicates an expected call of UpdateMiningPools.
func (mr *MockDeviceMockRecorder) UpdateMiningPools(ctx, pools interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMiningPools", reflect.TypeOf((*MockDevice)(nil).UpdateMiningPools), ctx, pools)
}

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// DescribeDriver mocks base method.
func (m *MockDriver) DescribeDriver(ctx context.Context) (sdk.DriverIdentifier, sdk.Capabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDriver", ctx)
	ret0, _ := ret[0].(sdk.DriverIdentifier)
	ret1, _ := ret[1].(sdk.Capabilities)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DescribeDriver indicates an expected call of DescribeDriver.
func (mr *MockDriverMockRecorder) DescribeDriver(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDriver", reflect.TypeOf((*MockDriver)(nil).DescribeDriver), ctx)
}

// DiscoverDevice mocks base method.
func (m *MockDriver) DiscoverDevice(ctx context.Context, ipAddress, port string) (sdk.DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverDevice", ctx, ipAddress, port)
	ret0, _ := ret[0].(sdk.DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverDevice indicates an expected call of DiscoverDevice.
func (mr *MockDriverMockRecorder) DiscoverDevice(ctx, ipAddress, port interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverDevice", reflect.TypeOf((*MockDriver)(nil).DiscoverDevice), ctx, ipAddress, port)
}

// Handshake mocks base method.
func (m *MockDriver) Handshake(ctx context.Context) (sdk.DriverIdentifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handshake", ctx)
	ret0, _ := ret[0].(sdk.DriverIdentifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handshake indicates an expected call of Handshake.
func (mr *MockDriverMockRecorder) Handshake(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handshake", reflect.TypeOf((*MockDriver)(nil).Handshake), ctx)
}

// NewDevice mocks base method.
func (m *MockDriver) NewDevice(ctx context.Context, deviceID string, deviceInfo sdk.DeviceInfo, secret sdk.SecretBundle) (sdk.NewDeviceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDevice", ctx, deviceID, deviceInfo, secret)
	ret0, _ := ret[0].(sdk.NewDeviceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDevice indicates an expected call of NewDevice.
func (mr *MockDriverMockRecorder) NewDevice(ctx, deviceID, deviceInfo, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDevice", reflect.TypeOf((*MockDriver)(nil).NewDevice), ctx, deviceID, deviceInfo, secret)
}

// PairDevice mocks base method.
func (m *MockDriver) PairDevice(ctx context.Context, device sdk.DeviceInfo, access sdk.SecretBundle) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PairDevice", ctx, device, access)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PairDevice indicates an expected call of PairDevice.
func (mr *MockDriverMockRecorder) PairDevice(ctx, device, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PairDevice", reflect.TypeOf((*MockDriver)(nil).PairDevice), ctx, device, access)
}
