// Code generated by MockGen. DO NOT EDIT.
// Source: miner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	dto "github.com/btc-mining/proto-fleet/server/internal/domain/miner/dto"
	models "github.com/btc-mining/proto-fleet/server/internal/domain/miner/models"
	models0 "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	networking "github.com/btc-mining/proto-fleet/server/internal/infrastructure/networking"
	gomock "github.com/golang/mock/gomock"
)

// MockMinerInfo is a mock of MinerInfo interface.
type MockMinerInfo struct {
	ctrl     *gomock.Controller
	recorder *MockMinerInfoMockRecorder
}

// MockMinerInfoMockRecorder is the mock recorder for MockMinerInfo.
type MockMinerInfoMockRecorder struct {
	mock *MockMinerInfo
}

// NewMockMinerInfo creates a new mock instance.
func NewMockMinerInfo(ctrl *gomock.Controller) *MockMinerInfo {
	mock := &MockMinerInfo{ctrl: ctrl}
	mock.recorder = &MockMinerInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerInfo) EXPECT() *MockMinerInfoMockRecorder {
	return m.recorder
}

// GetConnectionInfo mocks base method.
func (m *MockMinerInfo) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerInfoMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMinerInfo)(nil).GetConnectionInfo))
}

// GetID mocks base method.
func (m *MockMinerInfo) GetID() models.DeviceIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(models.DeviceIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMinerInfoMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMinerInfo)(nil).GetID))
}

// GetType mocks base method.
func (m *MockMinerInfo) GetType() models.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(models.Type)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockMinerInfoMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMinerInfo)(nil).GetType))
}

// GetWebViewURL mocks base method.
func (m *MockMinerInfo) GetWebViewURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebViewURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetWebViewURL indicates an expected call of GetWebViewURL.
func (mr *MockMinerInfoMockRecorder) GetWebViewURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebViewURL", reflect.TypeOf((*MockMinerInfo)(nil).GetWebViewURL))
}

// MockMiner is a mock of Miner interface.
type MockMiner struct {
	ctrl     *gomock.Controller
	recorder *MockMinerMockRecorder
}

// MockMinerMockRecorder is the mock recorder for MockMiner.
type MockMinerMockRecorder struct {
	mock *MockMiner
}

// NewMockMiner creates a new mock instance.
func NewMockMiner(ctrl *gomock.Controller) *MockMiner {
	mock := &MockMiner{ctrl: ctrl}
	mock.recorder = &MockMinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiner) EXPECT() *MockMinerMockRecorder {
	return m.recorder
}

// DownloadLogs mocks base method.
func (m *MockMiner) DownloadLogs(ctx context.Context, batchLogUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLogs", ctx, batchLogUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadLogs indicates an expected call of DownloadLogs.
func (mr *MockMinerMockRecorder) DownloadLogs(ctx, batchLogUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLogs", reflect.TypeOf((*MockMiner)(nil).DownloadLogs), ctx, batchLogUUID)
}

// GetConnectionInfo mocks base method.
func (m *MockMiner) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMiner)(nil).GetConnectionInfo))
}

// GetID mocks base method.
func (m *MockMiner) GetID() models.DeviceIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(models.DeviceIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMinerMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMiner)(nil).GetID))
}

// GetTelemetry mocks base method.
func (m *MockMiner) GetTelemetry(ctx context.Context, after time.Time) ([]models0.Telemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetry", ctx, after)
	ret0, _ := ret[0].([]models0.Telemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelemetry indicates an expected call of GetTelemetry.
func (mr *MockMinerMockRecorder) GetTelemetry(ctx, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetry", reflect.TypeOf((*MockMiner)(nil).GetTelemetry), ctx, after)
}

// GetType mocks base method.
func (m *MockMiner) GetType() models.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(models.Type)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockMinerMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMiner)(nil).GetType))
}

// GetWebViewURL mocks base method.
func (m *MockMiner) GetWebViewURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebViewURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetWebViewURL indicates an expected call of GetWebViewURL.
func (mr *MockMinerMockRecorder) GetWebViewURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebViewURL", reflect.TypeOf((*MockMiner)(nil).GetWebViewURL))
}

// SetCoolingMode mocks base method.
func (m *MockMiner) SetCoolingMode(ctx context.Context, payload dto.CoolingModePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoolingMode", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoolingMode indicates an expected call of SetCoolingMode.
func (mr *MockMinerMockRecorder) SetCoolingMode(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoolingMode", reflect.TypeOf((*MockMiner)(nil).SetCoolingMode), ctx, payload)
}

// StartMining mocks base method.
func (m *MockMiner) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockMinerMockRecorder) StartMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockMiner)(nil).StartMining), ctx)
}

// StopMining mocks base method.
func (m *MockMiner) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockMinerMockRecorder) StopMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockMiner)(nil).StopMining), ctx)
}

// UpdateMiningPools mocks base method.
func (m *MockMiner) UpdateMiningPools(ctx context.Context, payload dto.UpdateMiningPoolsPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMiningPools", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMiningPools indicates an expected call of UpdateMiningPools.
func (mr *MockMinerMockRecorder) UpdateMiningPools(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMiningPools", reflect.TypeOf((*MockMiner)(nil).UpdateMiningPools), ctx, payload)
}
