// Code generated by MockGen. DO NOT EDIT.
// Source: miner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/miner/models"
	models0 "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	networking "github.com/btc-mining/proto-fleet/server/internal/infrastructure/networking"
	gomock "github.com/golang/mock/gomock"
)

// MockMiner is a mock of Miner interface.
type MockMiner struct {
	ctrl     *gomock.Controller
	recorder *MockMinerMockRecorder
}

// MockMinerMockRecorder is the mock recorder for MockMiner.
type MockMinerMockRecorder struct {
	mock *MockMiner
}

// NewMockMiner creates a new mock instance.
func NewMockMiner(ctrl *gomock.Controller) *MockMiner {
	mock := &MockMiner{ctrl: ctrl}
	mock.recorder = &MockMinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiner) EXPECT() *MockMinerMockRecorder {
	return m.recorder
}

// GetConnectionInfo mocks base method.
func (m *MockMiner) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMiner)(nil).GetConnectionInfo))
}

// GetIdentifier mocks base method.
func (m *MockMiner) GetIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIdentifier indicates an expected call of GetIdentifier.
func (mr *MockMinerMockRecorder) GetIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentifier", reflect.TypeOf((*MockMiner)(nil).GetIdentifier))
}

// GetPairingInfo mocks base method.
func (m *MockMiner) GetPairingInfo(ctx context.Context) (*models.PairingInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPairingInfo", ctx)
	ret0, _ := ret[0].(*models.PairingInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPairingInfo indicates an expected call of GetPairingInfo.
func (mr *MockMinerMockRecorder) GetPairingInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPairingInfo", reflect.TypeOf((*MockMiner)(nil).GetPairingInfo), ctx)
}

// GetTelemetry mocks base method.
func (m *MockMiner) GetTelemetry(ctx context.Context, after time.Time) ([]models0.Telemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetry", ctx, after)
	ret0, _ := ret[0].([]models0.Telemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelemetry indicates an expected call of GetTelemetry.
func (mr *MockMinerMockRecorder) GetTelemetry(ctx, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetry", reflect.TypeOf((*MockMiner)(nil).GetTelemetry), ctx, after)
}

// GetType mocks base method.
func (m *MockMiner) GetType() models.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(models.Type)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockMinerMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMiner)(nil).GetType))
}

// StartMining mocks base method.
func (m *MockMiner) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockMinerMockRecorder) StartMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockMiner)(nil).StartMining), ctx)
}

// StopMining mocks base method.
func (m *MockMiner) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockMinerMockRecorder) StopMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockMiner)(nil).StopMining), ctx)
}
