// Code generated by MockGen. DO NOT EDIT.
// Source: miner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/diagnostics/models"
	dto "github.com/btc-mining/proto-fleet/server/internal/domain/miner/dto"
	models0 "github.com/btc-mining/proto-fleet/server/internal/domain/miner/models"
	models1 "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	models2 "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models/v2"
	networking "github.com/btc-mining/proto-fleet/server/internal/infrastructure/networking"
	gomock "github.com/golang/mock/gomock"
)

// MockMinerInfo is a mock of MinerInfo interface.
type MockMinerInfo struct {
	ctrl     *gomock.Controller
	recorder *MockMinerInfoMockRecorder
}

// MockMinerInfoMockRecorder is the mock recorder for MockMinerInfo.
type MockMinerInfoMockRecorder struct {
	mock *MockMinerInfo
}

// NewMockMinerInfo creates a new mock instance.
func NewMockMinerInfo(ctrl *gomock.Controller) *MockMinerInfo {
	mock := &MockMinerInfo{ctrl: ctrl}
	mock.recorder = &MockMinerInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerInfo) EXPECT() *MockMinerInfoMockRecorder {
	return m.recorder
}

// GetConnectionInfo mocks base method.
func (m *MockMinerInfo) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerInfoMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMinerInfo)(nil).GetConnectionInfo))
}

// GetID mocks base method.
func (m *MockMinerInfo) GetID() models0.DeviceIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(models0.DeviceIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMinerInfoMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMinerInfo)(nil).GetID))
}

// GetOrgID mocks base method.
func (m *MockMinerInfo) GetOrgID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetOrgID indicates an expected call of GetOrgID.
func (mr *MockMinerInfoMockRecorder) GetOrgID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgID", reflect.TypeOf((*MockMinerInfo)(nil).GetOrgID))
}

// GetSerialNumber mocks base method.
func (m *MockMinerInfo) GetSerialNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSerialNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSerialNumber indicates an expected call of GetSerialNumber.
func (mr *MockMinerInfoMockRecorder) GetSerialNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSerialNumber", reflect.TypeOf((*MockMinerInfo)(nil).GetSerialNumber))
}

// GetType mocks base method.
func (m *MockMinerInfo) GetType() models0.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(models0.Type)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockMinerInfoMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMinerInfo)(nil).GetType))
}

// GetWebViewURL mocks base method.
func (m *MockMinerInfo) GetWebViewURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebViewURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetWebViewURL indicates an expected call of GetWebViewURL.
func (mr *MockMinerInfoMockRecorder) GetWebViewURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebViewURL", reflect.TypeOf((*MockMinerInfo)(nil).GetWebViewURL))
}

// MockMiner is a mock of Miner interface.
type MockMiner struct {
	ctrl     *gomock.Controller
	recorder *MockMinerMockRecorder
}

// MockMinerMockRecorder is the mock recorder for MockMiner.
type MockMinerMockRecorder struct {
	mock *MockMiner
}

// NewMockMiner creates a new mock instance.
func NewMockMiner(ctrl *gomock.Controller) *MockMiner {
	mock := &MockMiner{ctrl: ctrl}
	mock.recorder = &MockMinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiner) EXPECT() *MockMinerMockRecorder {
	return m.recorder
}

// BlinkLED mocks base method.
func (m *MockMiner) BlinkLED(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlinkLED", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlinkLED indicates an expected call of BlinkLED.
func (mr *MockMinerMockRecorder) BlinkLED(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlinkLED", reflect.TypeOf((*MockMiner)(nil).BlinkLED), ctx)
}

// DownloadLogs mocks base method.
func (m *MockMiner) DownloadLogs(ctx context.Context, batchLogUUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLogs", ctx, batchLogUUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadLogs indicates an expected call of DownloadLogs.
func (mr *MockMinerMockRecorder) DownloadLogs(ctx, batchLogUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLogs", reflect.TypeOf((*MockMiner)(nil).DownloadLogs), ctx, batchLogUUID)
}

// FirmwareUpdate mocks base method.
func (m *MockMiner) FirmwareUpdate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirmwareUpdate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FirmwareUpdate indicates an expected call of FirmwareUpdate.
func (mr *MockMinerMockRecorder) FirmwareUpdate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirmwareUpdate", reflect.TypeOf((*MockMiner)(nil).FirmwareUpdate), ctx)
}

// GetConnectionInfo mocks base method.
func (m *MockMiner) GetConnectionInfo() networking.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionInfo")
	ret0, _ := ret[0].(networking.ConnectionInfo)
	return ret0
}

// GetConnectionInfo indicates an expected call of GetConnectionInfo.
func (mr *MockMinerMockRecorder) GetConnectionInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionInfo", reflect.TypeOf((*MockMiner)(nil).GetConnectionInfo))
}

// GetDeviceMetrics mocks base method.
func (m *MockMiner) GetDeviceMetrics(ctx context.Context) (models2.DeviceMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceMetrics", ctx)
	ret0, _ := ret[0].(models2.DeviceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceMetrics indicates an expected call of GetDeviceMetrics.
func (mr *MockMinerMockRecorder) GetDeviceMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceMetrics", reflect.TypeOf((*MockMiner)(nil).GetDeviceMetrics), ctx)
}

// GetDeviceStatus mocks base method.
func (m *MockMiner) GetDeviceStatus(ctx context.Context) (models0.MinerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceStatus", ctx)
	ret0, _ := ret[0].(models0.MinerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceStatus indicates an expected call of GetDeviceStatus.
func (mr *MockMinerMockRecorder) GetDeviceStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceStatus", reflect.TypeOf((*MockMiner)(nil).GetDeviceStatus), ctx)
}

// GetErrors mocks base method.
func (m *MockMiner) GetErrors(ctx context.Context) (models.DeviceErrors, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrors", ctx)
	ret0, _ := ret[0].(models.DeviceErrors)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrors indicates an expected call of GetErrors.
func (mr *MockMinerMockRecorder) GetErrors(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrors", reflect.TypeOf((*MockMiner)(nil).GetErrors), ctx)
}

// GetID mocks base method.
func (m *MockMiner) GetID() models0.DeviceIdentifier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(models0.DeviceIdentifier)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockMinerMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockMiner)(nil).GetID))
}

// GetOrgID mocks base method.
func (m *MockMiner) GetOrgID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetOrgID indicates an expected call of GetOrgID.
func (mr *MockMinerMockRecorder) GetOrgID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgID", reflect.TypeOf((*MockMiner)(nil).GetOrgID))
}

// GetSerialNumber mocks base method.
func (m *MockMiner) GetSerialNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSerialNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSerialNumber indicates an expected call of GetSerialNumber.
func (mr *MockMinerMockRecorder) GetSerialNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSerialNumber", reflect.TypeOf((*MockMiner)(nil).GetSerialNumber))
}

// GetTelemetry mocks base method.
func (m *MockMiner) GetTelemetry(ctx context.Context, after time.Time) ([]models1.Telemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetry", ctx, after)
	ret0, _ := ret[0].([]models1.Telemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelemetry indicates an expected call of GetTelemetry.
func (mr *MockMinerMockRecorder) GetTelemetry(ctx, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetry", reflect.TypeOf((*MockMiner)(nil).GetTelemetry), ctx, after)
}

// GetType mocks base method.
func (m *MockMiner) GetType() models0.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(models0.Type)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockMinerMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockMiner)(nil).GetType))
}

// GetWebViewURL mocks base method.
func (m *MockMiner) GetWebViewURL() *url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebViewURL")
	ret0, _ := ret[0].(*url.URL)
	return ret0
}

// GetWebViewURL indicates an expected call of GetWebViewURL.
func (mr *MockMinerMockRecorder) GetWebViewURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebViewURL", reflect.TypeOf((*MockMiner)(nil).GetWebViewURL))
}

// Reboot mocks base method.
func (m *MockMiner) Reboot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reboot indicates an expected call of Reboot.
func (mr *MockMinerMockRecorder) Reboot(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockMiner)(nil).Reboot), ctx)
}

// SetCoolingMode mocks base method.
func (m *MockMiner) SetCoolingMode(ctx context.Context, payload dto.CoolingModePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoolingMode", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoolingMode indicates an expected call of SetCoolingMode.
func (mr *MockMinerMockRecorder) SetCoolingMode(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoolingMode", reflect.TypeOf((*MockMiner)(nil).SetCoolingMode), ctx, payload)
}

// SetPowerTarget mocks base method.
func (m *MockMiner) SetPowerTarget(ctx context.Context, payload dto.PowerTargetPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPowerTarget", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPowerTarget indicates an expected call of SetPowerTarget.
func (mr *MockMinerMockRecorder) SetPowerTarget(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPowerTarget", reflect.TypeOf((*MockMiner)(nil).SetPowerTarget), ctx, payload)
}

// StartMining mocks base method.
func (m *MockMiner) StartMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartMining indicates an expected call of StartMining.
func (mr *MockMinerMockRecorder) StartMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMining", reflect.TypeOf((*MockMiner)(nil).StartMining), ctx)
}

// StopMining mocks base method.
func (m *MockMiner) StopMining(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopMining", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopMining indicates an expected call of StopMining.
func (mr *MockMinerMockRecorder) StopMining(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopMining", reflect.TypeOf((*MockMiner)(nil).StopMining), ctx)
}

// Unpair mocks base method.
func (m *MockMiner) Unpair(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpair", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unpair indicates an expected call of Unpair.
func (mr *MockMinerMockRecorder) Unpair(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpair", reflect.TypeOf((*MockMiner)(nil).Unpair), ctx)
}

// UpdateMiningPools mocks base method.
func (m *MockMiner) UpdateMiningPools(ctx context.Context, payload dto.UpdateMiningPoolsPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMiningPools", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMiningPools indicates an expected call of UpdateMiningPools.
func (mr *MockMinerMockRecorder) UpdateMiningPools(ctx, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMiningPools", reflect.TypeOf((*MockMiner)(nil).UpdateMiningPools), ctx, payload)
}
