services:
  fleet-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    environment:
      AUTH_SECRET_KEY: "00000000000000000000000000000000000000000000"
      AUTH_EXPIRATION_PERIOD: "15m"
      DB_NAME: "fleet"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      DB_ADDRESS: "mysql:3306"
      HTTP_STATIC_ASSET_PATH: "/app/static/"
      HTTP_LISTEN_ADDRESS: ":8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_LOG_CONSOLE: "1"
      MYSQL_INITDB_SKIP_TZINFO: "1" # Including TZ info slows down initialisation quite a bit
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "fleet"
    ports:
      - "3306:3306"
    command: --sql-mode= --log-bin --binlog-format=ROW --server-id=1 --skip-name-resolve --explicit-defaults-for-timestamp=ON
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql --host=localhost --user=root --execute='SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql: