lint:
  buf lint
  golangci-lint run -c .golangci.yaml

build-all:
    go build -v ./...

install:
    go install -v ./cmd/fleetd

run: db-up install
     ../.hermit/go/bin/fleetd

test:
    go test ./...

format:
  goimports -w .

gen: gen-protos gen-db-queries

gen-protos:
  buf generate

  goimports -w generated/grpc

gen-db-queries:
  sqlc generate
  goimports -w generated/sqlc

db-up:
  docker compose up -d

db-down:
  docker compose down

db-clean:
  docker compose down -v

db-shell:
  mysql -h 127.0.0.1 -u root --database fleet
