// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mock ErrorPoller,OrgIDLister
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	diagnostics "github.com/block/proto-fleet/server/internal/domain/diagnostics"
	interfaces "github.com/block/proto-fleet/server/internal/domain/miner/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockErrorPoller is a mock of ErrorPoller interface.
type MockErrorPoller struct {
	ctrl     *gomock.Controller
	recorder *MockErrorPollerMockRecorder
	isgomock struct{}
}

// MockErrorPollerMockRecorder is the mock recorder for MockErrorPoller.
type MockErrorPollerMockRecorder struct {
	mock *MockErrorPoller
}

// NewMockErrorPoller creates a new mock instance.
func NewMockErrorPoller(ctrl *gomock.Controller) *MockErrorPoller {
	mock := &MockErrorPoller{ctrl: ctrl}
	mock.recorder = &MockErrorPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorPoller) EXPECT() *MockErrorPollerMockRecorder {
	return m.recorder
}

// PollErrors mocks base method.
func (m *MockErrorPoller) PollErrors(ctx context.Context, miners ...interfaces.Miner) diagnostics.PollResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range miners {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PollErrors", varargs...)
	ret0, _ := ret[0].(diagnostics.PollResult)
	return ret0
}

// PollErrors indicates an expected call of PollErrors.
func (mr *MockErrorPollerMockRecorder) PollErrors(ctx any, miners ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, miners...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollErrors", reflect.TypeOf((*MockErrorPoller)(nil).PollErrors), varargs...)
}

// MockOrgIDLister is a mock of OrgIDLister interface.
type MockOrgIDLister struct {
	ctrl     *gomock.Controller
	recorder *MockOrgIDListerMockRecorder
	isgomock struct{}
}

// MockOrgIDListerMockRecorder is the mock recorder for MockOrgIDLister.
type MockOrgIDListerMockRecorder struct {
	mock *MockOrgIDLister
}

// NewMockOrgIDLister creates a new mock instance.
func NewMockOrgIDLister(ctrl *gomock.Controller) *MockOrgIDLister {
	mock := &MockOrgIDLister{ctrl: ctrl}
	mock.recorder = &MockOrgIDListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgIDLister) EXPECT() *MockOrgIDListerMockRecorder {
	return m.recorder
}

// ListOrgIDsForSnapshots mocks base method.
func (m *MockOrgIDLister) ListOrgIDsForSnapshots(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgIDsForSnapshots", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgIDsForSnapshots indicates an expected call of ListOrgIDsForSnapshots.
func (mr *MockOrgIDListerMockRecorder) ListOrgIDsForSnapshots(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgIDsForSnapshots", reflect.TypeOf((*MockOrgIDLister)(nil).ListOrgIDsForSnapshots), ctx)
}
