// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUpdateScheduler is a mock of UpdateScheduler interface.
type MockUpdateScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSchedulerMockRecorder
}

// MockUpdateSchedulerMockRecorder is the mock recorder for MockUpdateScheduler.
type MockUpdateSchedulerMockRecorder struct {
	mock *MockUpdateScheduler
}

// NewMockUpdateScheduler creates a new mock instance.
func NewMockUpdateScheduler(ctrl *gomock.Controller) *MockUpdateScheduler {
	mock := &MockUpdateScheduler{ctrl: ctrl}
	mock.recorder = &MockUpdateSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateScheduler) EXPECT() *MockUpdateSchedulerMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockUpdateScheduler) AddDevices(ctx context.Context, device ...models.Device) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range device {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddDevices(ctx interface{}, device ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, device...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddDevices), varargs...)
}

// AddNewDevices mocks base method.
func (m *MockUpdateScheduler) AddNewDevices(ctx context.Context, deviceID ...models.DeviceID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddNewDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewDevices indicates an expected call of AddNewDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddNewDevices(ctx interface{}, deviceID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddNewDevices), varargs...)
}

// FetchDevices mocks base method.
func (m *MockUpdateScheduler) FetchDevices(ctx context.Context, after time.Time) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDevices", ctx, after)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDevices indicates an expected call of FetchDevices.
func (mr *MockUpdateSchedulerMockRecorder) FetchDevices(ctx, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).FetchDevices), ctx, after)
}

// RemoveDevices mocks base method.
func (m *MockUpdateScheduler) RemoveDevices(ctx context.Context, deviceID ...models.DeviceID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDevices indicates an expected call of RemoveDevices.
func (mr *MockUpdateSchedulerMockRecorder) RemoveDevices(ctx interface{}, deviceID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).RemoveDevices), varargs...)
}

// MockTelemetryDataStore is a mock of TelemetryDataStore interface.
type MockTelemetryDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryDataStoreMockRecorder
}

// MockTelemetryDataStoreMockRecorder is the mock recorder for MockTelemetryDataStore.
type MockTelemetryDataStoreMockRecorder struct {
	mock *MockTelemetryDataStore
}

// NewMockTelemetryDataStore creates a new mock instance.
func NewMockTelemetryDataStore(ctrl *gomock.Controller) *MockTelemetryDataStore {
	mock := &MockTelemetryDataStore{ctrl: ctrl}
	mock.recorder = &MockTelemetryDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryDataStore) EXPECT() *MockTelemetryDataStoreMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockTelemetryDataStore) Store(ctx context.Context, data ...models.Telemetry) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range data {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Store", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTelemetryDataStoreMockRecorder) Store(ctx interface{}, data ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, data...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTelemetryDataStore)(nil).Store), varargs...)
}

// MockMinerManager is a mock of MinerManager interface.
type MockMinerManager struct {
	ctrl     *gomock.Controller
	recorder *MockMinerManagerMockRecorder
}

// MockMinerManagerMockRecorder is the mock recorder for MockMinerManager.
type MockMinerManagerMockRecorder struct {
	mock *MockMinerManager
}

// NewMockMinerManager creates a new mock instance.
func NewMockMinerManager(ctrl *gomock.Controller) *MockMinerManager {
	mock := &MockMinerManager{ctrl: ctrl}
	mock.recorder = &MockMinerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerManager) EXPECT() *MockMinerManagerMockRecorder {
	return m.recorder
}

// GetMinerFromDeviceID mocks base method.
func (m *MockMinerManager) GetMinerFromDeviceID(ctx context.Context, deviceID models.DeviceID) (models.Miner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerFromDeviceID", ctx, deviceID)
	ret0, _ := ret[0].(models.Miner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerFromDeviceID indicates an expected call of GetMinerFromDeviceID.
func (mr *MockMinerManagerMockRecorder) GetMinerFromDeviceID(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerFromDeviceID", reflect.TypeOf((*MockMinerManager)(nil).GetMinerFromDeviceID), ctx, deviceID)
}
