// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	interfaces "github.com/btc-mining/proto-fleet/server/internal/domain/miner/interfaces"
	models "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUpdateScheduler is a mock of UpdateScheduler interface.
type MockUpdateScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateSchedulerMockRecorder
}

// MockUpdateSchedulerMockRecorder is the mock recorder for MockUpdateScheduler.
type MockUpdateSchedulerMockRecorder struct {
	mock *MockUpdateScheduler
}

// NewMockUpdateScheduler creates a new mock instance.
func NewMockUpdateScheduler(ctrl *gomock.Controller) *MockUpdateScheduler {
	mock := &MockUpdateScheduler{ctrl: ctrl}
	mock.recorder = &MockUpdateSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateScheduler) EXPECT() *MockUpdateSchedulerMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockUpdateScheduler) AddDevices(ctx context.Context, devices ...models.Device) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range devices {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddDevices(ctx interface{}, devices ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, devices...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddDevices), varargs...)
}

// AddFailedDevices mocks base method.
func (m *MockUpdateScheduler) AddFailedDevices(ctx context.Context, devices ...models.Device) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range devices {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFailedDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFailedDevices indicates an expected call of AddFailedDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddFailedDevices(ctx interface{}, devices ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, devices...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFailedDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddFailedDevices), varargs...)
}

// AddNewDevices mocks base method.
func (m *MockUpdateScheduler) AddNewDevices(ctx context.Context, deviceID ...models.DeviceID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddNewDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewDevices indicates an expected call of AddNewDevices.
func (mr *MockUpdateSchedulerMockRecorder) AddNewDevices(ctx interface{}, deviceID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).AddNewDevices), varargs...)
}

// FetchDevices mocks base method.
func (m *MockUpdateScheduler) FetchDevices(ctx context.Context, after time.Time) ([]models.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDevices", ctx, after)
	ret0, _ := ret[0].([]models.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDevices indicates an expected call of FetchDevices.
func (mr *MockUpdateSchedulerMockRecorder) FetchDevices(ctx, after interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).FetchDevices), ctx, after)
}

// RemoveDevices mocks base method.
func (m *MockUpdateScheduler) RemoveDevices(ctx context.Context, deviceID ...models.DeviceID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDevices indicates an expected call of RemoveDevices.
func (mr *MockUpdateSchedulerMockRecorder) RemoveDevices(ctx interface{}, deviceID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevices", reflect.TypeOf((*MockUpdateScheduler)(nil).RemoveDevices), varargs...)
}

// MockTelemetryDataStore is a mock of TelemetryDataStore interface.
type MockTelemetryDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockTelemetryDataStoreMockRecorder
}

// MockTelemetryDataStoreMockRecorder is the mock recorder for MockTelemetryDataStore.
type MockTelemetryDataStoreMockRecorder struct {
	mock *MockTelemetryDataStore
}

// NewMockTelemetryDataStore creates a new mock instance.
func NewMockTelemetryDataStore(ctrl *gomock.Controller) *MockTelemetryDataStore {
	mock := &MockTelemetryDataStore{ctrl: ctrl}
	mock.recorder = &MockTelemetryDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelemetryDataStore) EXPECT() *MockTelemetryDataStoreMockRecorder {
	return m.recorder
}

// GetAggregatedTelemetry mocks base method.
func (m *MockTelemetryDataStore) GetAggregatedTelemetry(ctx context.Context, query models.AggregationQuery) ([]models.AggregatedTelemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedTelemetry", ctx, query)
	ret0, _ := ret[0].([]models.AggregatedTelemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedTelemetry indicates an expected call of GetAggregatedTelemetry.
func (mr *MockTelemetryDataStoreMockRecorder) GetAggregatedTelemetry(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedTelemetry", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetAggregatedTelemetry), ctx, query)
}

// GetLatestTelemetry mocks base method.
func (m *MockTelemetryDataStore) GetLatestTelemetry(ctx context.Context, query models.LatestTelemetryQuery) ([]models.Telemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestTelemetry", ctx, query)
	ret0, _ := ret[0].([]models.Telemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestTelemetry indicates an expected call of GetLatestTelemetry.
func (mr *MockTelemetryDataStoreMockRecorder) GetLatestTelemetry(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTelemetry", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetLatestTelemetry), ctx, query)
}

// GetTelemetryMetadata mocks base method.
func (m *MockTelemetryDataStore) GetTelemetryMetadata(ctx context.Context, query models.MetadataQuery) ([]models.DeviceMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelemetryMetadata", ctx, query)
	ret0, _ := ret[0].([]models.DeviceMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTelemetryMetadata indicates an expected call of GetTelemetryMetadata.
func (mr *MockTelemetryDataStoreMockRecorder) GetTelemetryMetadata(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelemetryMetadata", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetTelemetryMetadata), ctx, query)
}

// GetTimeSeriesTelemetry mocks base method.
func (m *MockTelemetryDataStore) GetTimeSeriesTelemetry(ctx context.Context, query models.TimeSeriesTelemetryQuery) ([]models.Telemetry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSeriesTelemetry", ctx, query)
	ret0, _ := ret[0].([]models.Telemetry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSeriesTelemetry indicates an expected call of GetTimeSeriesTelemetry.
func (mr *MockTelemetryDataStoreMockRecorder) GetTimeSeriesTelemetry(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSeriesTelemetry", reflect.TypeOf((*MockTelemetryDataStore)(nil).GetTimeSeriesTelemetry), ctx, query)
}

// Store mocks base method.
func (m *MockTelemetryDataStore) Store(ctx context.Context, data ...models.Telemetry) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range data {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Store", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTelemetryDataStoreMockRecorder) Store(ctx interface{}, data ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, data...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTelemetryDataStore)(nil).Store), varargs...)
}

// StreamTelemetryUpdates mocks base method.
func (m *MockTelemetryDataStore) StreamTelemetryUpdates(ctx context.Context, query models.StreamQuery) (<-chan models.TelemetryUpdate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamTelemetryUpdates", ctx, query)
	ret0, _ := ret[0].(<-chan models.TelemetryUpdate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamTelemetryUpdates indicates an expected call of StreamTelemetryUpdates.
func (mr *MockTelemetryDataStoreMockRecorder) StreamTelemetryUpdates(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamTelemetryUpdates", reflect.TypeOf((*MockTelemetryDataStore)(nil).StreamTelemetryUpdates), ctx, query)
}

// MockMinerManager is a mock of MinerManager interface.
type MockMinerManager struct {
	ctrl     *gomock.Controller
	recorder *MockMinerManagerMockRecorder
}

// MockMinerManagerMockRecorder is the mock recorder for MockMinerManager.
type MockMinerManagerMockRecorder struct {
	mock *MockMinerManager
}

// NewMockMinerManager creates a new mock instance.
func NewMockMinerManager(ctrl *gomock.Controller) *MockMinerManager {
	mock := &MockMinerManager{ctrl: ctrl}
	mock.recorder = &MockMinerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerManager) EXPECT() *MockMinerManagerMockRecorder {
	return m.recorder
}

// GetMinerFromDeviceID mocks base method.
func (m *MockMinerManager) GetMinerFromDeviceID(ctx context.Context, deviceID models.DeviceID) (interfaces.Miner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerFromDeviceID", ctx, deviceID)
	ret0, _ := ret[0].(interfaces.Miner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerFromDeviceID indicates an expected call of GetMinerFromDeviceID.
func (mr *MockMinerManagerMockRecorder) GetMinerFromDeviceID(ctx, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerFromDeviceID", reflect.TypeOf((*MockMinerManager)(nil).GetMinerFromDeviceID), ctx, deviceID)
}
