// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mock ErrorPoller
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	diagnostics "github.com/block/proto-fleet/server/internal/domain/diagnostics"
	interfaces "github.com/block/proto-fleet/server/internal/domain/miner/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockErrorPoller is a mock of ErrorPoller interface.
type MockErrorPoller struct {
	ctrl     *gomock.Controller
	recorder *MockErrorPollerMockRecorder
	isgomock struct{}
}

// MockErrorPollerMockRecorder is the mock recorder for MockErrorPoller.
type MockErrorPollerMockRecorder struct {
	mock *MockErrorPoller
}

// NewMockErrorPoller creates a new mock instance.
func NewMockErrorPoller(ctrl *gomock.Controller) *MockErrorPoller {
	mock := &MockErrorPoller{ctrl: ctrl}
	mock.recorder = &MockErrorPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorPoller) EXPECT() *MockErrorPollerMockRecorder {
	return m.recorder
}

// PollErrors mocks base method.
func (m *MockErrorPoller) PollErrors(ctx context.Context, miners ...interfaces.Miner) diagnostics.PollResult {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range miners {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PollErrors", varargs...)
	ret0, _ := ret[0].(diagnostics.PollResult)
	return ret0
}

// PollErrors indicates an expected call of PollErrors.
func (mr *MockErrorPollerMockRecorder) PollErrors(ctx any, miners ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, miners...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollErrors", reflect.TypeOf((*MockErrorPoller)(nil).PollErrors), varargs...)
}
