CREATE TABLE organization
(
    id         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    org_id     VARCHAR(36)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT uq_organization_org_id UNIQUE (org_id)
);
