// Code generated by MockGen. DO NOT EDIT.
// Source: scanner.go
//
// Generated by this command:
//
//	mockgen -source=scanner.go -destination=mocks/mock_scanner.go -package=mocks DeviceIdentityCheckService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/minerdiscovery/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceIdentityCheckService is a mock of DeviceIdentityCheckService interface.
type MockDeviceIdentityCheckService struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceIdentityCheckServiceMockRecorder
	isgomock struct{}
}

// MockDeviceIdentityCheckServiceMockRecorder is the mock recorder for MockDeviceIdentityCheckService.
type MockDeviceIdentityCheckServiceMockRecorder struct {
	mock *MockDeviceIdentityCheckService
}

// NewMockDeviceIdentityCheckService creates a new mock instance.
func NewMockDeviceIdentityCheckService(ctrl *gomock.Controller) *MockDeviceIdentityCheckService {
	mock := &MockDeviceIdentityCheckService{ctrl: ctrl}
	mock.recorder = &MockDeviceIdentityCheckServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceIdentityCheckService) EXPECT() *MockDeviceIdentityCheckServiceMockRecorder {
	return m.recorder
}

// IsSameDevice mocks base method.
func (m *MockDeviceIdentityCheckService) IsSameDevice(ctx context.Context, newDiscoveredDevice *models.DiscoveredDevice, pairedDeviceIdentifier string, orgID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSameDevice", ctx, newDiscoveredDevice, pairedDeviceIdentifier, orgID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSameDevice indicates an expected call of IsSameDevice.
func (mr *MockDeviceIdentityCheckServiceMockRecorder) IsSameDevice(ctx, newDiscoveredDevice, pairedDeviceIdentifier, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSameDevice", reflect.TypeOf((*MockDeviceIdentityCheckService)(nil).IsSameDevice), ctx, newDiscoveredDevice, pairedDeviceIdentifier, orgID)
}
