run:
  go: '1.24'
  timeout: 15m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  print-issued-lines: false

linters:
  enable-all: true
  disable:
    - perfsprint # performance is not our primary concern, and sprint(f) makes strings easier to read
    - mnd
    - depguard # re-enable in future, see https://github.com/golangci/golangci-lint/issues/3906
    - tagalign
    - gosimple
    - staticcheck
    - unused
    - lll
    - typecheck # `go build` catches this, and it doesn't currently work with Go 1.11 modules
    - goimports # horrendously slow with go modules :(
    - dupl # has never been actually useful
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - whitespace
    - godox
    - wsl
    - dogsled
    - gocognit
    - testpackage
    - nestif
    - nolintlint
    - err113
    - godot
    - gci # completely broken and unmaintained: https://github.com/daixiang0/gci/issues
    - gofumpt # a bit excessive
    - nlreturn
    - noctx # Nice idea, but don't have time. It would be good to re-enable and fix at some point.
    - errorlint # Nice idea, but don't have time. It would be good to re-enable and fix at some point.
    - forbidigo
    - paralleltest
    - prealloc # annoying
    - tagliatelle # annoying
    - varnamelen # annoying
    - nonamedreturns # annoying
    - nilnil # annoying
    - maintidx # annoying
    - ireturn # annoying
    - exhaustruct # annoying
    - cyclop # annoying
    - thelper # annoying
    - errname # annoying
    - gocyclo # annoying
    - gomoddirectives # annoying
    - contextcheck # requires context passed to every method with a context
    - nosprintfhostport
    - musttag # Slows down the overall process significantly
    - protogetter # annoying and slow
    - tenv # deprecated

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 8
    min-occurrences: 3
  gocyclo:
    min-complexity: 20
  gocritic:
    disabled-checks:
      - ifElseChain

  forbidigo:
    forbid:
      - 'fmt\.Errorf'

  wrapcheck:
    # An array of glob patterns which, if any match the package of the function
    # returning the error, will skip wrapcheck analysis for this error.
    #
    # N.B. This matches the "package of the function returning the error" not
    # the package of the code calling the function returning the error. So adding
    # a package glob here does not ignore inside that package. It ignores all
    # callsites where that package is called.
    #
    # wrapcheck is useful for defending against unwrapped errors from 3rd-party
    # libraries. These errors don't necessarily have stack traces attached and
    # so, unwrapped, they are difficult to debug. All errors from gap packages
    # should have stack traces attached (see https://github.com/squareup/gap-errors).
    # It's less necessary to wrap those errors.
    ignorePackageGlobs:
      # It's expected that all errors returned by packages which start with
      # github.com/btc-mining/miner-firmware already have their errors wrapped
      # and so do not need to be re-wrapped.
      - github.com/btc-mining/miner-firmware/*

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - goconst
    # hamilton - don't warn about parameters being unused in fakes
    - path: apps/hamilton/(.*)/fake_(.*)\.go
      text: "parameter '.+' seems to be unused, consider removing or renaming it as _"

  exclude:
    # gosec overenthusiasm
    - '^(G104|G204|G307|G306|G404):'
    # Very commonly not checked.
    - 'Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*Unlock|.*Print(f|ln|)|os\.(Un)?Setenv|.*\.Rollback). is not checked'
    # Weird error only seen on Kochiku...
    - 'internal error: no range for'
    - 'exported method `.*\.(MarshalJSON|UnmarshalJSON|URN|Payload|GoString|Close|Provides|Requires|ExcludeFromHash|MarshalText|UnmarshalText|Description|Check|Poll|Severity)` should have comment or be unexported'
    - 'composite literal uses unkeyed fields'
    - 'declaration of "err" shadows declaration'
    - 'by other packages, and that stutters'
    - 'Potential file inclusion via variable'
    - 'at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
    # errors.As() is error-prone and difficult to use.
    - 'Use errors.As to check for specific errors'
    - 'should have comment or be unexported'
    - '`ctx` is unused' # method signatures shouldnt change because they need to log something.
    - 'parameter ''ctx'' seems to be unused'
  exclude-dirs:
    - generated
