services:
  fleet-api:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "4000:8080"
    environment:
      AUTH_SECRET_KEY: "00000000000000000000000000000000000000000000"
      AUTH_EXPIRATION_PERIOD: "15m"
      DB_NAME: "fleet"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      DB_ADDRESS: "mysql:3306"
      HTTP_STATIC_ASSET_PATH: "/app/static/"
      HTTP_LISTEN_ADDRESS: ":8080"
      HTTP_SUPPRESS_CORS: "true"
      LOG_LEVEL: "DEBUG"
      PAIRING_SECRET_KEY: "00000000000000000000000000000000000000000000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fleet-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
  mms-1:
    build:
      context: ../miner-firmware
      dockerfile: docker/sim/Dockerfile
    ports:
      - "4100:8080"
    environment:
      PORT: 8080
    networks:
      - fleet-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
  mms-2:
    build:
      context: ../miner-firmware
      dockerfile: docker/sim/Dockerfile
    ports:
      - "4200:8080"
    environment:
      PORT: 8080
    networks:
      - fleet-network
    cap_add:
      - NET_ADMIN
      - NET_RAW
  mysql:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_LOG_CONSOLE: "1"
      MYSQL_INITDB_SKIP_TZINFO: "1" # Including TZ info slows down initialisation quite a bit
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "fleet"
    ports:
      - "3306:3306"
    command: --sql-mode= --log-bin --binlog-format=ROW --server-id=1 --skip-name-resolve --explicit-defaults-for-timestamp=ON
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - fleet-network

volumes:
  mysql:

networks:
  fleet-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"
