### Run health chcek
GET {{host}}/health

### Onboarding: Create Admin User
GRPC {{host}}/onboarding.v1.OnboardingService/CreateAdminLogin

{
  "username": "mcharles@block.xyz",
  "password": "00000000000000000000000000000000000000000000"
}

### Authenticate
GRPC {{host}}/auth.v1.AuthService/Authenticate

{
  "username": "mcharles@block.xyz",
  "password": "00000000000000000000000000000000000000000000"
}

### Run mdns discovery
GRPC {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}

{
  "mdns": {
    "service_type": "_http._tcp",
    "domain": "fleet_fleet-network.",
    "timeout_seconds": 15
  }
}

### Run nmap discovery
GRPC {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}

{
  "nmap": {
    "target": "192.168.2.0/24",
    "ports": [
      "2121"
    ],
    "fast_scan": false
  }
}

### Run ip range discovery

GRPC {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}

{
  "ip_range": {
    "start_ip": "10.0.0.248",
    "end_ip": "10.0.0.250",
    "ports": [
      "2121"
    ]
  }
}

### Run ip list discovery

GRPC {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}

{
  "ip_list": {
    "ip_addresses": [ "mms-1", "mms-2", "miner-1.miner.fleetdev.proto.xyz", "miner-2.miner.fleetdev.proto.xyz", "miner-3.miner.fleetdev.proto.xyz" ],
    "ports": [
      "2121"
    ]
  }
}

### run pairing query
GRPC {{host}}/pairing.v1.PairingService/Pair
Authorization: Bearer {{auth_token}}

{
  "device_identifier": ["43f9baf4-65e7-4611-a363-2de4d2294cc0", "83037515-ae70-4519-b527-de79f31001b0" ]
}

### list paired devices
GRPC {{host}}/fleetmanagement.v1.FleetManagementService/ListPairedMiners
Authorization: Bearer {{auth_token}}

{
  "page_size": 10
}

### Run network info

GRPC {{host}}/networkinfo.v1.NetworkInfoService/GetNetworkInfo
Authorization: Bearer {{auth_token}}

{

}

### Run Create Pool

GRPC {{host}}/fleetmanagement.v1.FleetManagementService/CreatePool
Authorization: Bearer {{auth_token}}

{
  "pool_config": {
    "url": "https://example.xyz",
    "username": "bob",
    "password": "secret",
    "pool_name": "backup"
  }
}

### Run Set Default Pool

GRPC {{host}}/fleetmanagement.v1.FleetManagementService/SetDefaultPool
Authorization: Bearer {{auth_token}}

{
  "pool_id": "10"
}

### Run List Pool

GRPC {{host}}/fleetmanagement.v1.FleetManagementService/ListPools
Authorization: Bearer {{auth_token}}

{
}

### Run Update Pool Priority

GRPC {{host}}/fleetmanagement.v1.FleetManagementService/UpdatePoolPriority
Authorization: Bearer {{auth_token}}

{
  "pool_priorities": [
    { "priority": 1, "id": "9"},
    { "priority": 2, "id": "10"}
  ]
}

### Run Update Pool

GRPC {{host}}/fleetmanagement.v1.FleetManagementService/UpdatePool
Authorization: Bearer {{auth_token}}

{
  "id": "9",
  "password": "default default"
}

### Stop mining

GRPC {{host}}/minercommand.v1.MinerCommandService/StopMining
Authorization: Bearer {{auth_token}}

{
  "device_identifiers": [
    "9a830907-3a08-4c92-baff-cc94235f53ec",
    "67ee965e-09b5-46b8-ad5a-21b1a51be7e9",
    "a1a64dc4-9f28-42e8-88c7-3baa9e26b938"
  ]
}

### Start mining

GRPC {{host}}/minercommand.v1.MinerCommandService/StartMining
Authorization: Bearer {{auth_token}}

{
  "device_identifiers": [
    "9a830907-3a08-4c92-baff-cc94235f53ec",
    "67ee965e-09b5-46b8-ad5a-21b1a51be7e9",
    "a1a64dc4-9f28-42e8-88c7-3baa9e26b938"
  ]
}

###

GRPC grpcs://miner-1.miner.fleetdev.proto.xyz:2121/miner_command_api.MinerCommandApi/StopMining

{
}

###

GRPC grpcs://miner-1.miner.fleetdev.proto.xyz:2121/miner_command_api.MinerCommandApi/StartMining

{
}

###

GRPC localhost:2121/miner_command_api.MinerCommandApi/StartMining

{
}

### Onboarding: Create Admin User
GRPC {{host}}/onboarding.v1.OnboardingService/GetFleetOnboardingStatus
Authorization: Bearer {{auth_token}}

{

}
