@host = http://localhost:4000

### Run health check
GET {{host}}/health

### Onboarding: Create Admin User
POST {{host}}/onboarding.v1.OnboardingService/CreateAdminLogin
Content-Type: application/json

{
  "username": "admin",
  "password": "proto"
}

### Authenticate
# @name authenticate
POST {{host}}/auth.v1.AuthService/Authenticate
Content-Type: application/json

{
  "username": "admin",
  "password": "proto"
}

### Set auth token
@auth_token = {{authenticate.response.body.token}}

### Run mdns discovery
POST {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}
Content-Type: application/grpc+json

{
  "mdns": {
    "service_type": "_http._tcp",
    "domain": "fleet_fleet-network.",
    "timeout_seconds": 15
  }
}

### Run nmap discovery

POST {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}
Content-Type: application/grpc+json

{
  "nmap": {
    "target": "192.168.2.0/24",
    "ports": [
      "2121"
    ],
    "fast_scan": false
  }
}

### Run ip range discovery

POST {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}
Content-Type: application/grpc+json

{
  "ip_range": {
    "start_ip": "10.0.0.248",
    "end_ip": "10.0.0.250",
    "ports": [
      "2121"
    ]
  }
}

### Run ip list discovery

POST {{host}}/pairing.v1.PairingService/Discover
Authorization: Bearer {{auth_token}}
Content-Type: application/grpc+json

{
  "ip_list": {
    "ip_addresses": [ "mms-1", "mms-2", "miner-1.miner.fleetdev.proto.xyz", "miner-2.miner.fleetdev.proto.xyz", "miner-3.miner.fleetdev.proto.xyz" ],
    "ports": [
      "2121"
    ]
  }
}

### run pairing query

POST {{host}}/pairing.v1.PairingService/Pair
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "device_identifiers": ["c9ea3eea-60b6-414f-9207-88bf3a1154d2", "eb6993d9-85c4-4ed9-865b-7833aac82af4" ]
}

### list unpaired devices

POST {{host}}/fleetmanagement.v1.FleetManagementService/ListUnpairedDevices
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "page_size": 10
}

### list paired miner state snapshots

POST {{host}}/fleetmanagement.v1.FleetManagementService/ListMinerStateSnapshots
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "page_size": 10
}

### stream miner updates

POST {{host}}/fleetmanagement.v1.FleetManagementService/StreamMinerUpdates HTTP/2
Authorization: Bearer {{auth_token}}
Content-Type: application/grpc+json; charset=utf-8
Accept: application/grpc+json

{
  "device_identifiers": ["eb6993d9-85c4-4ed9-865b-7833aac82af4", "c9ea3eea-60b6-414f-9207-88bf3a1154d2"],
  "measurement_types": [1, 2, 3, 4],
  "include_status_updates": true,
  "heartbeat_interval_seconds": 5
}

### Run network info

POST {{host}}/networkinfo.v1.NetworkInfoService/GetNetworkInfo
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{

}

### Run Create Pool

POST {{host}}/fleetmanagement.v1.FleetManagementService/CreatePool
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "pool_config": {
    "url": "https://example.xyz",
    "username": "bob",
    "password": "secret",
    "pool_name": "backup"
  }
}

### Run Set Default Pool

POST {{host}}/fleetmanagement.v1.FleetManagementService/SetDefaultPool
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "pool_id": "10"
}

### Run List Pool

POST {{host}}/fleetmanagement.v1.FleetManagementService/ListPools
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
}

### Run Update Pool Priority

POST {{host}}/fleetmanagement.v1.FleetManagementService/UpdatePoolPriority
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "pool_priorities": [
    { "priority": 1, "id": "9"},
    { "priority": 2, "id": "10"}
  ]
}

### Run Update Pool

POST {{host}}/fleetmanagement.v1.FleetManagementService/UpdatePool
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "9",
  "password": "default default"
}

### Stop mining

POST {{host}}/minercommand.v1.MinerCommandService/StopMining
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "device_identifiers": [
    "9a830907-3a08-4c92-baff-cc94235f53ec",
    "67ee965e-09b5-46b8-ad5a-21b1a51be7e9",
    "a1a64dc4-9f28-42e8-88c7-3baa9e26b938"
  ]
}

### Start mining

POST {{host}}/minercommand.v1.MinerCommandService/StartMining
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "device_identifiers": [
    "9a830907-3a08-4c92-baff-cc94235f53ec",
    "67ee965e-09b5-46b8-ad5a-21b1a51be7e9",
    "a1a64dc4-9f28-42e8-88c7-3baa9e26b938"
  ]
}

###

POST https://miner-1.miner.fleetdev.proto.xyz:2121/miner_command_api.MinerCommandApi/StopMining
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
}

###

POST https://miner-1.miner.fleetdev.proto.xyz:2121/miner_command_api.MinerCommandApi/StartMining
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
}

###

POST localhost:2122/miner_command_api.MinerCommandApi/StartMining
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
}

### Onboarding: Create Admin User
POST {{host}}/onboarding.v1.OnboardingService/GetFleetOnboardingStatus
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{

}
