// Copyright 2024 Block, Inc. <btcm-sw-team@squareup.com>.
//
// File: miner_telemetry_api.proto
// Description: gRPC server-streaming API exposed by the on-rig
//              telemetry-service. Streams OTLP metrics and OTLP logs
//              aggregated from all services on the rig to an off-rig client
//              (otlp-bridge). Each batch carries a prost-encoded OTLP request
//              as opaque bytes so the bridge can pass it through to a
//              Prometheus / OTel collector without transcoding.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.5
// source: miner_telemetry_api.proto

package minertelemetry

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MinerTelemetryApi_StreamMetrics_FullMethodName = "/miner_telemetry_api.MinerTelemetryApi/StreamMetrics"
	MinerTelemetryApi_StreamLogs_FullMethodName    = "/miner_telemetry_api.MinerTelemetryApi/StreamLogs"
)

// MinerTelemetryApiClient is the client API for MinerTelemetryApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinerTelemetryApiClient interface {
	// Server-streaming. The server emits an immediate snapshot, then a fresh
	// MetricsBatch on every NATS ingestion update for any matching service.
	// service_names may filter the stream (empty = all services).
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (MinerTelemetryApi_StreamMetricsClient, error)
	// Server-streaming. The server follows live log entries as they arrive on
	// NATS. Logs emitted while no client is connected are not replayed.
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (MinerTelemetryApi_StreamLogsClient, error)
}

type minerTelemetryApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMinerTelemetryApiClient(cc grpc.ClientConnInterface) MinerTelemetryApiClient {
	return &minerTelemetryApiClient{cc}
}

func (c *minerTelemetryApiClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (MinerTelemetryApi_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MinerTelemetryApi_ServiceDesc.Streams[0], MinerTelemetryApi_StreamMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &minerTelemetryApiStreamMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MinerTelemetryApi_StreamMetricsClient interface {
	Recv() (*MetricsBatch, error)
	grpc.ClientStream
}

type minerTelemetryApiStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *minerTelemetryApiStreamMetricsClient) Recv() (*MetricsBatch, error) {
	m := new(MetricsBatch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *minerTelemetryApiClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (MinerTelemetryApi_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MinerTelemetryApi_ServiceDesc.Streams[1], MinerTelemetryApi_StreamLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &minerTelemetryApiStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MinerTelemetryApi_StreamLogsClient interface {
	Recv() (*LogsBatch, error)
	grpc.ClientStream
}

type minerTelemetryApiStreamLogsClient struct {
	grpc.ClientStream
}

func (x *minerTelemetryApiStreamLogsClient) Recv() (*LogsBatch, error) {
	m := new(LogsBatch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MinerTelemetryApiServer is the server API for MinerTelemetryApi service.
// All implementations must embed UnimplementedMinerTelemetryApiServer
// for forward compatibility
type MinerTelemetryApiServer interface {
	// Server-streaming. The server emits an immediate snapshot, then a fresh
	// MetricsBatch on every NATS ingestion update for any matching service.
	// service_names may filter the stream (empty = all services).
	StreamMetrics(*StreamMetricsRequest, MinerTelemetryApi_StreamMetricsServer) error
	// Server-streaming. The server follows live log entries as they arrive on
	// NATS. Logs emitted while no client is connected are not replayed.
	StreamLogs(*StreamLogsRequest, MinerTelemetryApi_StreamLogsServer) error
	mustEmbedUnimplementedMinerTelemetryApiServer()
}

// UnimplementedMinerTelemetryApiServer must be embedded to have forward compatible implementations.
type UnimplementedMinerTelemetryApiServer struct {
}

func (UnimplementedMinerTelemetryApiServer) StreamMetrics(*StreamMetricsRequest, MinerTelemetryApi_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedMinerTelemetryApiServer) StreamLogs(*StreamLogsRequest, MinerTelemetryApi_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedMinerTelemetryApiServer) mustEmbedUnimplementedMinerTelemetryApiServer() {}

// UnsafeMinerTelemetryApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinerTelemetryApiServer will
// result in compilation errors.
type UnsafeMinerTelemetryApiServer interface {
	mustEmbedUnimplementedMinerTelemetryApiServer()
}

func RegisterMinerTelemetryApiServer(s grpc.ServiceRegistrar, srv MinerTelemetryApiServer) {
	s.RegisterService(&MinerTelemetryApi_ServiceDesc, srv)
}

func _MinerTelemetryApi_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinerTelemetryApiServer).StreamMetrics(m, &minerTelemetryApiStreamMetricsServer{stream})
}

type MinerTelemetryApi_StreamMetricsServer interface {
	Send(*MetricsBatch) error
	grpc.ServerStream
}

type minerTelemetryApiStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *minerTelemetryApiStreamMetricsServer) Send(m *MetricsBatch) error {
	return x.ServerStream.SendMsg(m)
}

func _MinerTelemetryApi_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinerTelemetryApiServer).StreamLogs(m, &minerTelemetryApiStreamLogsServer{stream})
}

type MinerTelemetryApi_StreamLogsServer interface {
	Send(*LogsBatch) error
	grpc.ServerStream
}

type minerTelemetryApiStreamLogsServer struct {
	grpc.ServerStream
}

func (x *minerTelemetryApiStreamLogsServer) Send(m *LogsBatch) error {
	return x.ServerStream.SendMsg(m)
}

// MinerTelemetryApi_ServiceDesc is the grpc.ServiceDesc for MinerTelemetryApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinerTelemetryApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "miner_telemetry_api.MinerTelemetryApi",
	HandlerType: (*MinerTelemetryApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _MinerTelemetryApi_StreamMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _MinerTelemetryApi_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "miner_telemetry_api.proto",
}
