// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks Listener,CapabilitiesProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	capabilitiesv1 "github.com/proto-at-block/proto-fleet/server/generated/grpc/capabilities/v1"
	pairingv1 "github.com/proto-at-block/proto-fleet/server/generated/grpc/pairing/v1"
	models "github.com/proto-at-block/proto-fleet/server/internal/domain/telemetry/models"
	gomock "go.uber.org/mock/gomock"
)

// MockListener is a mock of Listener interface.
type MockListener struct {
	ctrl     *gomock.Controller
	recorder *MockListenerMockRecorder
	isgomock struct{}
}

// MockListenerMockRecorder is the mock recorder for MockListener.
type MockListenerMockRecorder struct {
	mock *MockListener
}

// NewMockListener creates a new mock instance.
func NewMockListener(ctrl *gomock.Controller) *MockListener {
	mock := &MockListener{ctrl: ctrl}
	mock.recorder = &MockListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListener) EXPECT() *MockListenerMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockListener) AddDevices(ctx context.Context, deviceID ...models.DeviceIdentifier) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockListenerMockRecorder) AddDevices(ctx any, deviceID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockListener)(nil).AddDevices), varargs...)
}

// MockCapabilitiesProvider is a mock of CapabilitiesProvider interface.
type MockCapabilitiesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilitiesProviderMockRecorder
	isgomock struct{}
}

// MockCapabilitiesProviderMockRecorder is the mock recorder for MockCapabilitiesProvider.
type MockCapabilitiesProviderMockRecorder struct {
	mock *MockCapabilitiesProvider
}

// NewMockCapabilitiesProvider creates a new mock instance.
func NewMockCapabilitiesProvider(ctrl *gomock.Controller) *MockCapabilitiesProvider {
	mock := &MockCapabilitiesProvider{ctrl: ctrl}
	mock.recorder = &MockCapabilitiesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapabilitiesProvider) EXPECT() *MockCapabilitiesProviderMockRecorder {
	return m.recorder
}

// GetMinerCapabilitiesForDevice mocks base method.
func (m *MockCapabilitiesProvider) GetMinerCapabilitiesForDevice(ctx context.Context, device *pairingv1.Device) *capabilitiesv1.MinerCapabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerCapabilitiesForDevice", ctx, device)
	ret0, _ := ret[0].(*capabilitiesv1.MinerCapabilities)
	return ret0
}

// GetMinerCapabilitiesForDevice indicates an expected call of GetMinerCapabilitiesForDevice.
func (mr *MockCapabilitiesProviderMockRecorder) GetMinerCapabilitiesForDevice(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerCapabilitiesForDevice", reflect.TypeOf((*MockCapabilitiesProvider)(nil).GetMinerCapabilitiesForDevice), ctx, device)
}
