// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go -package=mocks Listener,CapabilitiesProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	capabilitiesv1 "github.com/block/proto-fleet/server/generated/grpc/capabilities/v1"
	pairingv1 "github.com/block/proto-fleet/server/generated/grpc/pairing/v1"
	models "github.com/block/proto-fleet/server/internal/domain/telemetry/models"
	gomock "go.uber.org/mock/gomock"
)

// MockListener is a mock of Listener interface.
type MockListener struct {
	ctrl     *gomock.Controller
	recorder *MockListenerMockRecorder
	isgomock struct{}
}

// MockListenerMockRecorder is the mock recorder for MockListener.
type MockListenerMockRecorder struct {
	mock *MockListener
}

// NewMockListener creates a new mock instance.
func NewMockListener(ctrl *gomock.Controller) *MockListener {
	mock := &MockListener{ctrl: ctrl}
	mock.recorder = &MockListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListener) EXPECT() *MockListenerMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockListener) AddDevices(ctx context.Context, deviceID ...models.DeviceIdentifier) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockListenerMockRecorder) AddDevices(ctx any, deviceID ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockListener)(nil).AddDevices), varargs...)
}

// MockdevicePairingStatusProvider is a mock of devicePairingStatusProvider interface.
type MockdevicePairingStatusProvider struct {
	ctrl     *gomock.Controller
	recorder *MockdevicePairingStatusProviderMockRecorder
	isgomock struct{}
}

// MockdevicePairingStatusProviderMockRecorder is the mock recorder for MockdevicePairingStatusProvider.
type MockdevicePairingStatusProviderMockRecorder struct {
	mock *MockdevicePairingStatusProvider
}

// NewMockdevicePairingStatusProvider creates a new mock instance.
func NewMockdevicePairingStatusProvider(ctrl *gomock.Controller) *MockdevicePairingStatusProvider {
	mock := &MockdevicePairingStatusProvider{ctrl: ctrl}
	mock.recorder = &MockdevicePairingStatusProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdevicePairingStatusProvider) EXPECT() *MockdevicePairingStatusProviderMockRecorder {
	return m.recorder
}

// GetDevicePairingStatusByIdentifier mocks base method.
func (m *MockdevicePairingStatusProvider) GetDevicePairingStatusByIdentifier(ctx context.Context, deviceIdentifier string, orgID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevicePairingStatusByIdentifier", ctx, deviceIdentifier, orgID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevicePairingStatusByIdentifier indicates an expected call of GetDevicePairingStatusByIdentifier.
func (mr *MockdevicePairingStatusProviderMockRecorder) GetDevicePairingStatusByIdentifier(ctx, deviceIdentifier, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevicePairingStatusByIdentifier", reflect.TypeOf((*MockdevicePairingStatusProvider)(nil).GetDevicePairingStatusByIdentifier), ctx, deviceIdentifier, orgID)
}

// MockCapabilitiesProvider is a mock of CapabilitiesProvider interface.
type MockCapabilitiesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCapabilitiesProviderMockRecorder
	isgomock struct{}
}

// MockCapabilitiesProviderMockRecorder is the mock recorder for MockCapabilitiesProvider.
type MockCapabilitiesProviderMockRecorder struct {
	mock *MockCapabilitiesProvider
}

// NewMockCapabilitiesProvider creates a new mock instance.
func NewMockCapabilitiesProvider(ctrl *gomock.Controller) *MockCapabilitiesProvider {
	mock := &MockCapabilitiesProvider{ctrl: ctrl}
	mock.recorder = &MockCapabilitiesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapabilitiesProvider) EXPECT() *MockCapabilitiesProviderMockRecorder {
	return m.recorder
}

// GetDefaultDiscoveryPorts mocks base method.
func (m *MockCapabilitiesProvider) GetDefaultDiscoveryPorts(ctx context.Context) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultDiscoveryPorts", ctx)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDefaultDiscoveryPorts indicates an expected call of GetDefaultDiscoveryPorts.
func (mr *MockCapabilitiesProviderMockRecorder) GetDefaultDiscoveryPorts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultDiscoveryPorts", reflect.TypeOf((*MockCapabilitiesProvider)(nil).GetDefaultDiscoveryPorts), ctx)
}

// GetDiscoveryPorts mocks base method.
func (m *MockCapabilitiesProvider) GetDiscoveryPorts(ctx context.Context) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscoveryPorts", ctx)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDiscoveryPorts indicates an expected call of GetDiscoveryPorts.
func (mr *MockCapabilitiesProviderMockRecorder) GetDiscoveryPorts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscoveryPorts", reflect.TypeOf((*MockCapabilitiesProvider)(nil).GetDiscoveryPorts), ctx)
}

// GetMinerCapabilitiesForDevice mocks base method.
func (m *MockCapabilitiesProvider) GetMinerCapabilitiesForDevice(ctx context.Context, device *pairingv1.Device) *capabilitiesv1.MinerCapabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerCapabilitiesForDevice", ctx, device)
	ret0, _ := ret[0].(*capabilitiesv1.MinerCapabilities)
	return ret0
}

// GetMinerCapabilitiesForDevice indicates an expected call of GetMinerCapabilitiesForDevice.
func (mr *MockCapabilitiesProviderMockRecorder) GetMinerCapabilitiesForDevice(ctx, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerCapabilitiesForDevice", reflect.TypeOf((*MockCapabilitiesProvider)(nil).GetMinerCapabilitiesForDevice), ctx, device)
}
