// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	gomock "github.com/golang/mock/gomock"
)

// MockListener is a mock of Listener interface.
type MockListener struct {
	ctrl     *gomock.Controller
	recorder *MockListenerMockRecorder
}

// MockListenerMockRecorder is the mock recorder for MockListener.
type MockListenerMockRecorder struct {
	mock *MockListener
}

// NewMockListener creates a new mock instance.
func NewMockListener(ctrl *gomock.Controller) *MockListener {
	mock := &MockListener{ctrl: ctrl}
	mock.recorder = &MockListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListener) EXPECT() *MockListenerMockRecorder {
	return m.recorder
}

// AddDevices mocks base method.
func (m *MockListener) AddDevices(ctx context.Context, deviceID ...models.DeviceIdentifier) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range deviceID {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddDevices", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDevices indicates an expected call of AddDevices.
func (mr *MockListenerMockRecorder) AddDevices(ctx interface{}, deviceID ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, deviceID...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevices", reflect.TypeOf((*MockListener)(nil).AddDevices), varargs...)
}
