// Code generated by MockGen. DO NOT EDIT.
// Source: collection.go
//
// Generated by this command:
//
//	mockgen -source=collection.go -destination=mocks/mock_collection_store.go -package=mocks CollectionStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	collectionv1 "github.com/btc-mining/proto-fleet/server/generated/grpc/collection/v1"
	interfaces "github.com/btc-mining/proto-fleet/server/internal/domain/stores/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionStore is a mock of CollectionStore interface.
type MockCollectionStore struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionStoreMockRecorder
	isgomock struct{}
}

// MockCollectionStoreMockRecorder is the mock recorder for MockCollectionStore.
type MockCollectionStoreMockRecorder struct {
	mock *MockCollectionStore
}

// NewMockCollectionStore creates a new mock instance.
func NewMockCollectionStore(ctrl *gomock.Controller) *MockCollectionStore {
	mock := &MockCollectionStore{ctrl: ctrl}
	mock.recorder = &MockCollectionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionStore) EXPECT() *MockCollectionStoreMockRecorder {
	return m.recorder
}

// AddDevicesToCollection mocks base method.
func (m *MockCollectionStore) AddDevicesToCollection(ctx context.Context, orgID, collectionID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDevicesToCollection", ctx, orgID, collectionID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDevicesToCollection indicates an expected call of AddDevicesToCollection.
func (mr *MockCollectionStoreMockRecorder) AddDevicesToCollection(ctx, orgID, collectionID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDevicesToCollection", reflect.TypeOf((*MockCollectionStore)(nil).AddDevicesToCollection), ctx, orgID, collectionID, deviceIdentifiers)
}

// ClearRackSlotPosition mocks base method.
func (m *MockCollectionStore) ClearRackSlotPosition(ctx context.Context, collectionID int64, deviceIdentifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRackSlotPosition", ctx, collectionID, deviceIdentifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearRackSlotPosition indicates an expected call of ClearRackSlotPosition.
func (mr *MockCollectionStoreMockRecorder) ClearRackSlotPosition(ctx, collectionID, deviceIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRackSlotPosition", reflect.TypeOf((*MockCollectionStore)(nil).ClearRackSlotPosition), ctx, collectionID, deviceIdentifier)
}

// CollectionBelongsToOrg mocks base method.
func (m *MockCollectionStore) CollectionBelongsToOrg(ctx context.Context, collectionID, orgID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectionBelongsToOrg", ctx, collectionID, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectionBelongsToOrg indicates an expected call of CollectionBelongsToOrg.
func (mr *MockCollectionStoreMockRecorder) CollectionBelongsToOrg(ctx, collectionID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectionBelongsToOrg", reflect.TypeOf((*MockCollectionStore)(nil).CollectionBelongsToOrg), ctx, collectionID, orgID)
}

// CreateCollection mocks base method.
func (m *MockCollectionStore) CreateCollection(ctx context.Context, orgID int64, collectionType collectionv1.CollectionType, label, description string) (*collectionv1.DeviceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollection", ctx, orgID, collectionType, label, description)
	ret0, _ := ret[0].(*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollection indicates an expected call of CreateCollection.
func (mr *MockCollectionStoreMockRecorder) CreateCollection(ctx, orgID, collectionType, label, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollection", reflect.TypeOf((*MockCollectionStore)(nil).CreateCollection), ctx, orgID, collectionType, label, description)
}

// CreateRackExtension mocks base method.
func (m *MockCollectionStore) CreateRackExtension(ctx context.Context, collectionID int64, location string, rows, columns int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRackExtension", ctx, collectionID, location, rows, columns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRackExtension indicates an expected call of CreateRackExtension.
func (mr *MockCollectionStoreMockRecorder) CreateRackExtension(ctx, collectionID, location, rows, columns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRackExtension", reflect.TypeOf((*MockCollectionStore)(nil).CreateRackExtension), ctx, collectionID, location, rows, columns)
}

// GetCollection mocks base method.
func (m *MockCollectionStore) GetCollection(ctx context.Context, orgID, collectionID int64) (*collectionv1.DeviceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollection", ctx, orgID, collectionID)
	ret0, _ := ret[0].(*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollection indicates an expected call of GetCollection.
func (mr *MockCollectionStoreMockRecorder) GetCollection(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollection", reflect.TypeOf((*MockCollectionStore)(nil).GetCollection), ctx, orgID, collectionID)
}

// GetCollectionType mocks base method.
func (m *MockCollectionStore) GetCollectionType(ctx context.Context, orgID, collectionID int64) (collectionv1.CollectionType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollectionType", ctx, orgID, collectionID)
	ret0, _ := ret[0].(collectionv1.CollectionType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionType indicates an expected call of GetCollectionType.
func (mr *MockCollectionStoreMockRecorder) GetCollectionType(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionType", reflect.TypeOf((*MockCollectionStore)(nil).GetCollectionType), ctx, orgID, collectionID)
}

// GetDeviceCollections mocks base method.
func (m *MockCollectionStore) GetDeviceCollections(ctx context.Context, orgID int64, deviceIdentifier string, collectionType collectionv1.CollectionType) ([]*collectionv1.DeviceCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCollections", ctx, orgID, deviceIdentifier, collectionType)
	ret0, _ := ret[0].([]*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCollections indicates an expected call of GetDeviceCollections.
func (mr *MockCollectionStoreMockRecorder) GetDeviceCollections(ctx, orgID, deviceIdentifier, collectionType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCollections", reflect.TypeOf((*MockCollectionStore)(nil).GetDeviceCollections), ctx, orgID, deviceIdentifier, collectionType)
}

// GetGroupLabelsForDevices mocks base method.
func (m *MockCollectionStore) GetGroupLabelsForDevices(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupLabelsForDevices", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupLabelsForDevices indicates an expected call of GetGroupLabelsForDevices.
func (mr *MockCollectionStoreMockRecorder) GetGroupLabelsForDevices(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupLabelsForDevices", reflect.TypeOf((*MockCollectionStore)(nil).GetGroupLabelsForDevices), ctx, orgID, deviceIdentifiers)
}

// GetRackInfo mocks base method.
func (m *MockCollectionStore) GetRackInfo(ctx context.Context, collectionID int64) (*collectionv1.RackInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackInfo", ctx, collectionID)
	ret0, _ := ret[0].(*collectionv1.RackInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackInfo indicates an expected call of GetRackInfo.
func (mr *MockCollectionStoreMockRecorder) GetRackInfo(ctx, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackInfo", reflect.TypeOf((*MockCollectionStore)(nil).GetRackInfo), ctx, collectionID)
}

// GetRackLabelsForDevices mocks base method.
func (m *MockCollectionStore) GetRackLabelsForDevices(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackLabelsForDevices", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackLabelsForDevices indicates an expected call of GetRackLabelsForDevices.
func (mr *MockCollectionStoreMockRecorder) GetRackLabelsForDevices(ctx, orgID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackLabelsForDevices", reflect.TypeOf((*MockCollectionStore)(nil).GetRackLabelsForDevices), ctx, orgID, deviceIdentifiers)
}

// GetRackSlots mocks base method.
func (m *MockCollectionStore) GetRackSlots(ctx context.Context, collectionID int64) ([]*collectionv1.RackSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRackSlots", ctx, collectionID)
	ret0, _ := ret[0].([]*collectionv1.RackSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRackSlots indicates an expected call of GetRackSlots.
func (mr *MockCollectionStoreMockRecorder) GetRackSlots(ctx, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRackSlots", reflect.TypeOf((*MockCollectionStore)(nil).GetRackSlots), ctx, collectionID)
}

// ListCollectionMembers mocks base method.
func (m *MockCollectionStore) ListCollectionMembers(ctx context.Context, orgID, collectionID int64, pageSize int32, pageToken string) ([]*collectionv1.CollectionMember, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectionMembers", ctx, orgID, collectionID, pageSize, pageToken)
	ret0, _ := ret[0].([]*collectionv1.CollectionMember)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCollectionMembers indicates an expected call of ListCollectionMembers.
func (mr *MockCollectionStoreMockRecorder) ListCollectionMembers(ctx, orgID, collectionID, pageSize, pageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectionMembers", reflect.TypeOf((*MockCollectionStore)(nil).ListCollectionMembers), ctx, orgID, collectionID, pageSize, pageToken)
}

// ListCollections mocks base method.
func (m *MockCollectionStore) ListCollections(ctx context.Context, orgID int64, collectionType collectionv1.CollectionType, pageSize int32, pageToken string, sort *interfaces.SortConfig) ([]*collectionv1.DeviceCollection, string, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollections", ctx, orgID, collectionType, pageSize, pageToken, sort)
	ret0, _ := ret[0].([]*collectionv1.DeviceCollection)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int32)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListCollections indicates an expected call of ListCollections.
func (mr *MockCollectionStoreMockRecorder) ListCollections(ctx, orgID, collectionType, pageSize, pageToken, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollections", reflect.TypeOf((*MockCollectionStore)(nil).ListCollections), ctx, orgID, collectionType, pageSize, pageToken, sort)
}

// RemoveAllDevicesFromCollection mocks base method.
func (m *MockCollectionStore) RemoveAllDevicesFromCollection(ctx context.Context, orgID, collectionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllDevicesFromCollection", ctx, orgID, collectionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAllDevicesFromCollection indicates an expected call of RemoveAllDevicesFromCollection.
func (mr *MockCollectionStoreMockRecorder) RemoveAllDevicesFromCollection(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllDevicesFromCollection", reflect.TypeOf((*MockCollectionStore)(nil).RemoveAllDevicesFromCollection), ctx, orgID, collectionID)
}

// RemoveDevicesFromCollection mocks base method.
func (m *MockCollectionStore) RemoveDevicesFromCollection(ctx context.Context, orgID, collectionID int64, deviceIdentifiers []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDevicesFromCollection", ctx, orgID, collectionID, deviceIdentifiers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDevicesFromCollection indicates an expected call of RemoveDevicesFromCollection.
func (mr *MockCollectionStoreMockRecorder) RemoveDevicesFromCollection(ctx, orgID, collectionID, deviceIdentifiers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDevicesFromCollection", reflect.TypeOf((*MockCollectionStore)(nil).RemoveDevicesFromCollection), ctx, orgID, collectionID, deviceIdentifiers)
}

// SetRackSlotPosition mocks base method.
func (m *MockCollectionStore) SetRackSlotPosition(ctx context.Context, collectionID int64, deviceIdentifier string, row, column int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRackSlotPosition", ctx, collectionID, deviceIdentifier, row, column)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRackSlotPosition indicates an expected call of SetRackSlotPosition.
func (mr *MockCollectionStoreMockRecorder) SetRackSlotPosition(ctx, collectionID, deviceIdentifier, row, column any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRackSlotPosition", reflect.TypeOf((*MockCollectionStore)(nil).SetRackSlotPosition), ctx, collectionID, deviceIdentifier, row, column)
}

// SoftDeleteCollection mocks base method.
func (m *MockCollectionStore) SoftDeleteCollection(ctx context.Context, orgID, collectionID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteCollection", ctx, orgID, collectionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteCollection indicates an expected call of SoftDeleteCollection.
func (mr *MockCollectionStoreMockRecorder) SoftDeleteCollection(ctx, orgID, collectionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteCollection", reflect.TypeOf((*MockCollectionStore)(nil).SoftDeleteCollection), ctx, orgID, collectionID)
}

// UpdateCollection mocks base method.
func (m *MockCollectionStore) UpdateCollection(ctx context.Context, orgID, collectionID int64, label, description *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollection", ctx, orgID, collectionID, label, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCollection indicates an expected call of UpdateCollection.
func (mr *MockCollectionStoreMockRecorder) UpdateCollection(ctx, orgID, collectionID, label, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollection", reflect.TypeOf((*MockCollectionStore)(nil).UpdateCollection), ctx, orgID, collectionID, label, description)
}

// UpdateRackInfo mocks base method.
func (m *MockCollectionStore) UpdateRackInfo(ctx context.Context, collectionID int64, location string, rows, columns int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRackInfo", ctx, collectionID, location, rows, columns)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRackInfo indicates an expected call of UpdateRackInfo.
func (mr *MockCollectionStoreMockRecorder) UpdateRackInfo(ctx, collectionID, location, rows, columns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRackInfo", reflect.TypeOf((*MockCollectionStore)(nil).UpdateRackInfo), ctx, collectionID, location, rows, columns)
}
