// Code generated by MockGen. DO NOT EDIT.
// Source: note.go
//
// Generated by this command:
//
//	mockgen -source=note.go -destination=mocks/mock_note_store.go -package=mocks NoteStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/notes/models"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteStore is a mock of NoteStore interface.
type MockNoteStore struct {
	ctrl     *gomock.Controller
	recorder *MockNoteStoreMockRecorder
	isgomock struct{}
}

// MockNoteStoreMockRecorder is the mock recorder for MockNoteStore.
type MockNoteStoreMockRecorder struct {
	mock *MockNoteStore
}

// NewMockNoteStore creates a new mock instance.
func NewMockNoteStore(ctrl *gomock.Controller) *MockNoteStore {
	mock := &MockNoteStore{ctrl: ctrl}
	mock.recorder = &MockNoteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteStore) EXPECT() *MockNoteStoreMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockNoteStore) CreateNote(ctx context.Context, orgID, userID int64, content string) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, orgID, userID, content)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteStoreMockRecorder) CreateNote(ctx, orgID, userID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteStore)(nil).CreateNote), ctx, orgID, userID, content)
}

// GetNote mocks base method.
func (m *MockNoteStore) GetNote(ctx context.Context, orgID, id int64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, orgID, id)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockNoteStoreMockRecorder) GetNote(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockNoteStore)(nil).GetNote), ctx, orgID, id)
}

// ListNotes mocks base method.
func (m *MockNoteStore) ListNotes(ctx context.Context, params models.ListNotesParams) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotes", ctx, params)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotes indicates an expected call of ListNotes.
func (mr *MockNoteStoreMockRecorder) ListNotes(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotes", reflect.TypeOf((*MockNoteStore)(nil).ListNotes), ctx, params)
}

// SoftDeleteNote mocks base method.
func (m *MockNoteStore) SoftDeleteNote(ctx context.Context, orgID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteNote", ctx, orgID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteNote indicates an expected call of SoftDeleteNote.
func (mr *MockNoteStoreMockRecorder) SoftDeleteNote(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteNote", reflect.TypeOf((*MockNoteStore)(nil).SoftDeleteNote), ctx, orgID, id)
}

// UpdateNoteContent mocks base method.
func (m *MockNoteStore) UpdateNoteContent(ctx context.Context, orgID, id, authorUserID int64, content string) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNoteContent", ctx, orgID, id, authorUserID, content)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNoteContent indicates an expected call of UpdateNoteContent.
func (mr *MockNoteStoreMockRecorder) UpdateNoteContent(ctx, orgID, id, authorUserID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNoteContent", reflect.TypeOf((*MockNoteStore)(nil).UpdateNoteContent), ctx, orgID, id, authorUserID, content)
}
