// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go
//
// Generated by this command:
//
//	mockgen -source=activity.go -destination=mocks/mock_activity_store.go -package=mocks ActivityStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/activity/models"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityStore is a mock of ActivityStore interface.
type MockActivityStore struct {
	ctrl     *gomock.Controller
	recorder *MockActivityStoreMockRecorder
	isgomock struct{}
}

// MockActivityStoreMockRecorder is the mock recorder for MockActivityStore.
type MockActivityStoreMockRecorder struct {
	mock *MockActivityStore
}

// NewMockActivityStore creates a new mock instance.
func NewMockActivityStore(ctrl *gomock.Controller) *MockActivityStore {
	mock := &MockActivityStore{ctrl: ctrl}
	mock.recorder = &MockActivityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityStore) EXPECT() *MockActivityStoreMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockActivityStore) Count(ctx context.Context, filter models.Filter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockActivityStoreMockRecorder) Count(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockActivityStore)(nil).Count), ctx, filter)
}

// GetDistinctEventTypes mocks base method.
func (m *MockActivityStore) GetDistinctEventTypes(ctx context.Context, orgID int64) ([]models.EventTypeInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctEventTypes", ctx, orgID)
	ret0, _ := ret[0].([]models.EventTypeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctEventTypes indicates an expected call of GetDistinctEventTypes.
func (mr *MockActivityStoreMockRecorder) GetDistinctEventTypes(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctEventTypes", reflect.TypeOf((*MockActivityStore)(nil).GetDistinctEventTypes), ctx, orgID)
}

// GetDistinctScopeTypes mocks base method.
func (m *MockActivityStore) GetDistinctScopeTypes(ctx context.Context, orgID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctScopeTypes", ctx, orgID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctScopeTypes indicates an expected call of GetDistinctScopeTypes.
func (mr *MockActivityStoreMockRecorder) GetDistinctScopeTypes(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctScopeTypes", reflect.TypeOf((*MockActivityStore)(nil).GetDistinctScopeTypes), ctx, orgID)
}

// GetDistinctUsers mocks base method.
func (m *MockActivityStore) GetDistinctUsers(ctx context.Context, orgID int64) ([]models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctUsers", ctx, orgID)
	ret0, _ := ret[0].([]models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctUsers indicates an expected call of GetDistinctUsers.
func (mr *MockActivityStoreMockRecorder) GetDistinctUsers(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctUsers", reflect.TypeOf((*MockActivityStore)(nil).GetDistinctUsers), ctx, orgID)
}

// Insert mocks base method.
func (m *MockActivityStore) Insert(ctx context.Context, event *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockActivityStoreMockRecorder) Insert(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockActivityStore)(nil).Insert), ctx, event)
}

// List mocks base method.
func (m *MockActivityStore) List(ctx context.Context, filter models.Filter) ([]models.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]models.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockActivityStoreMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActivityStore)(nil).List), ctx, filter)
}
