// Code generated by MockGen. DO NOT EDIT.
// Source: device.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	fleetmanagementv1 "github.com/btc-mining/proto-fleet/server/generated/grpc/fleetmanagement/v1"
	pairingv1 "github.com/btc-mining/proto-fleet/server/generated/grpc/pairing/v1"
	telemetryv1 "github.com/btc-mining/proto-fleet/server/generated/grpc/telemetry/v1"
	models "github.com/btc-mining/proto-fleet/server/internal/domain/miner/models"
	minerdiscovery "github.com/btc-mining/proto-fleet/server/internal/domain/minerdiscovery"
	interfaces "github.com/btc-mining/proto-fleet/server/internal/domain/stores/interfaces"
	models0 "github.com/btc-mining/proto-fleet/server/internal/domain/telemetry/models"
	secrets "github.com/btc-mining/proto-fleet/server/internal/infrastructure/secrets"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceStore is a mock of DeviceStore interface.
type MockDeviceStore struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStoreMockRecorder
}

// MockDeviceStoreMockRecorder is the mock recorder for MockDeviceStore.
type MockDeviceStoreMockRecorder struct {
	mock *MockDeviceStore
}

// NewMockDeviceStore creates a new mock instance.
func NewMockDeviceStore(ctrl *gomock.Controller) *MockDeviceStore {
	mock := &MockDeviceStore{ctrl: ctrl}
	mock.recorder = &MockDeviceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceStore) EXPECT() *MockDeviceStoreMockRecorder {
	return m.recorder
}

// GetAllPairedDeviceIdentifiers mocks base method.
func (m *MockDeviceStore) GetAllPairedDeviceIdentifiers(ctx context.Context) ([]models0.DeviceIdentifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPairedDeviceIdentifiers", ctx)
	ret0, _ := ret[0].([]models0.DeviceIdentifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPairedDeviceIdentifiers indicates an expected call of GetAllPairedDeviceIdentifiers.
func (mr *MockDeviceStoreMockRecorder) GetAllPairedDeviceIdentifiers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPairedDeviceIdentifiers", reflect.TypeOf((*MockDeviceStore)(nil).GetAllPairedDeviceIdentifiers), ctx)
}

// GetAvailableMinerTypes mocks base method.
func (m *MockDeviceStore) GetAvailableMinerTypes(ctx context.Context, orgID int64) ([]models.Type, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableMinerTypes", ctx, orgID)
	ret0, _ := ret[0].([]models.Type)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableMinerTypes indicates an expected call of GetAvailableMinerTypes.
func (mr *MockDeviceStoreMockRecorder) GetAvailableMinerTypes(ctx, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableMinerTypes", reflect.TypeOf((*MockDeviceStore)(nil).GetAvailableMinerTypes), ctx, orgID)
}

// GetDeviceByDeviceIdentifier mocks base method.
func (m *MockDeviceStore) GetDeviceByDeviceIdentifier(ctx context.Context, identifier string, orgID int64) (*pairingv1.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByDeviceIdentifier", ctx, identifier, orgID)
	ret0, _ := ret[0].(*pairingv1.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByDeviceIdentifier indicates an expected call of GetDeviceByDeviceIdentifier.
func (mr *MockDeviceStoreMockRecorder) GetDeviceByDeviceIdentifier(ctx, identifier, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByDeviceIdentifier", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceByDeviceIdentifier), ctx, identifier, orgID)
}

// GetDeviceStatusForDeviceIdentifiers mocks base method.
func (m *MockDeviceStore) GetDeviceStatusForDeviceIdentifiers(ctx context.Context, deviceIdentifiers []models0.DeviceIdentifier) (map[models0.DeviceIdentifier]models.MinerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceStatusForDeviceIdentifiers", ctx, deviceIdentifiers)
	ret0, _ := ret[0].(map[models0.DeviceIdentifier]models.MinerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceStatusForDeviceIdentifiers indicates an expected call of GetDeviceStatusForDeviceIdentifiers.
func (mr *MockDeviceStoreMockRecorder) GetDeviceStatusForDeviceIdentifiers(ctx, deviceIdentifiers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceStatusForDeviceIdentifiers", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceStatusForDeviceIdentifiers), ctx, deviceIdentifiers)
}

// GetDeviceWithIPAssignment mocks base method.
func (m *MockDeviceStore) GetDeviceWithIPAssignment(ctx context.Context, deviceIdentifier string, orgID int64) (*minerdiscovery.DiscoveredDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceWithIPAssignment", ctx, deviceIdentifier, orgID)
	ret0, _ := ret[0].(*minerdiscovery.DiscoveredDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceWithIPAssignment indicates an expected call of GetDeviceWithIPAssignment.
func (mr *MockDeviceStoreMockRecorder) GetDeviceWithIPAssignment(ctx, deviceIdentifier, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceWithIPAssignment", reflect.TypeOf((*MockDeviceStore)(nil).GetDeviceWithIPAssignment), ctx, deviceIdentifier, orgID)
}

// GetMinerCredentials mocks base method.
func (m *MockDeviceStore) GetMinerCredentials(ctx context.Context, device *pairingv1.Device, orgID int64) (*pairingv1.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerCredentials", ctx, device, orgID)
	ret0, _ := ret[0].(*pairingv1.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerCredentials indicates an expected call of GetMinerCredentials.
func (mr *MockDeviceStoreMockRecorder) GetMinerCredentials(ctx, device, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerCredentials", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerCredentials), ctx, device, orgID)
}

// GetMinerStateCounts mocks base method.
func (m *MockDeviceStore) GetMinerStateCounts(ctx context.Context, orgID int64, filter *interfaces.MinerFilter) (*telemetryv1.MinerStateCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinerStateCounts", ctx, orgID, filter)
	ret0, _ := ret[0].(*telemetryv1.MinerStateCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinerStateCounts indicates an expected call of GetMinerStateCounts.
func (mr *MockDeviceStoreMockRecorder) GetMinerStateCounts(ctx, orgID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinerStateCounts", reflect.TypeOf((*MockDeviceStore)(nil).GetMinerStateCounts), ctx, orgID, filter)
}

// GetTotalPairedDevices mocks base method.
func (m *MockDeviceStore) GetTotalPairedDevices(ctx context.Context, orgID int64, filter *interfaces.MinerFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalPairedDevices", ctx, orgID, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalPairedDevices indicates an expected call of GetTotalPairedDevices.
func (mr *MockDeviceStoreMockRecorder) GetTotalPairedDevices(ctx, orgID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalPairedDevices", reflect.TypeOf((*MockDeviceStore)(nil).GetTotalPairedDevices), ctx, orgID, filter)
}

// ListPairedDevices mocks base method.
func (m *MockDeviceStore) ListPairedDevices(ctx context.Context, cursor string, pageSize int32) ([]*fleetmanagementv1.PairedDevice, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPairedDevices", ctx, cursor, pageSize)
	ret0, _ := ret[0].([]*fleetmanagementv1.PairedDevice)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPairedDevices indicates an expected call of ListPairedDevices.
func (mr *MockDeviceStoreMockRecorder) ListPairedDevices(ctx, cursor, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPairedDevices", reflect.TypeOf((*MockDeviceStore)(nil).ListPairedDevices), ctx, cursor, pageSize)
}

// ListPairedMinersWithStatus mocks base method.
func (m *MockDeviceStore) ListPairedMinersWithStatus(ctx context.Context, orgID int64, cursor string, pageSize int32, filter *interfaces.MinerFilter) ([]*pairingv1.Device, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPairedMinersWithStatus", ctx, orgID, cursor, pageSize, filter)
	ret0, _ := ret[0].([]*pairingv1.Device)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPairedMinersWithStatus indicates an expected call of ListPairedMinersWithStatus.
func (mr *MockDeviceStoreMockRecorder) ListPairedMinersWithStatus(ctx, orgID, cursor, pageSize, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPairedMinersWithStatus", reflect.TypeOf((*MockDeviceStore)(nil).ListPairedMinersWithStatus), ctx, orgID, cursor, pageSize, filter)
}

// UpsertDevice mocks base method.
func (m *MockDeviceStore) UpsertDevice(ctx context.Context, device *pairingv1.Device, orgID int64, deviceType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevice", ctx, device, orgID, deviceType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDevice indicates an expected call of UpsertDevice.
func (mr *MockDeviceStoreMockRecorder) UpsertDevice(ctx, device, orgID, deviceType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevice", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDevice), ctx, device, orgID, deviceType)
}

// UpsertDeviceIPAssignment mocks base method.
func (m *MockDeviceStore) UpsertDeviceIPAssignment(ctx context.Context, device *pairingv1.Device, orgID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDeviceIPAssignment", ctx, device, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDeviceIPAssignment indicates an expected call of UpsertDeviceIPAssignment.
func (mr *MockDeviceStoreMockRecorder) UpsertDeviceIPAssignment(ctx, device, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDeviceIPAssignment", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDeviceIPAssignment), ctx, device, orgID)
}

// UpsertDevicePairing mocks base method.
func (m *MockDeviceStore) UpsertDevicePairing(ctx context.Context, device *pairingv1.Device, orgID int64, pairingStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDevicePairing", ctx, device, orgID, pairingStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDevicePairing indicates an expected call of UpsertDevicePairing.
func (mr *MockDeviceStoreMockRecorder) UpsertDevicePairing(ctx, device, orgID, pairingStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDevicePairing", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDevicePairing), ctx, device, orgID, pairingStatus)
}

// UpsertDeviceStatus mocks base method.
func (m *MockDeviceStore) UpsertDeviceStatus(ctx context.Context, deviceIdentifier models0.DeviceIdentifier, status models.MinerStatus, details string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDeviceStatus", ctx, deviceIdentifier, status, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDeviceStatus indicates an expected call of UpsertDeviceStatus.
func (mr *MockDeviceStoreMockRecorder) UpsertDeviceStatus(ctx, deviceIdentifier, status, details interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDeviceStatus", reflect.TypeOf((*MockDeviceStore)(nil).UpsertDeviceStatus), ctx, deviceIdentifier, status, details)
}

// UpsertMinerCredentials mocks base method.
func (m *MockDeviceStore) UpsertMinerCredentials(ctx context.Context, device *pairingv1.Device, orgID int64, usernameEnc string, passwordEnc *secrets.Text) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMinerCredentials", ctx, device, orgID, usernameEnc, passwordEnc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMinerCredentials indicates an expected call of UpsertMinerCredentials.
func (mr *MockDeviceStoreMockRecorder) UpsertMinerCredentials(ctx, device, orgID, usernameEnc, passwordEnc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMinerCredentials", reflect.TypeOf((*MockDeviceStore)(nil).UpsertMinerCredentials), ctx, device, orgID, usernameEnc, passwordEnc)
}
