// Code generated by MockGen. DO NOT EDIT.
// Source: discovered_device.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/minerdiscovery/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDiscoveredDeviceStore is a mock of DiscoveredDeviceStore interface.
type MockDiscoveredDeviceStore struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveredDeviceStoreMockRecorder
}

// MockDiscoveredDeviceStoreMockRecorder is the mock recorder for MockDiscoveredDeviceStore.
type MockDiscoveredDeviceStoreMockRecorder struct {
	mock *MockDiscoveredDeviceStore
}

// NewMockDiscoveredDeviceStore creates a new mock instance.
func NewMockDiscoveredDeviceStore(ctrl *gomock.Controller) *MockDiscoveredDeviceStore {
	mock := &MockDiscoveredDeviceStore{ctrl: ctrl}
	mock.recorder = &MockDiscoveredDeviceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveredDeviceStore) EXPECT() *MockDiscoveredDeviceStoreMockRecorder {
	return m.recorder
}

// CountActiveUnpairedDevices mocks base method.
func (m *MockDiscoveredDeviceStore) CountActiveUnpairedDevices(ctx context.Context, orgID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveUnpairedDevices", ctx, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveUnpairedDevices indicates an expected call of CountActiveUnpairedDevices.
func (mr *MockDiscoveredDeviceStoreMockRecorder) CountActiveUnpairedDevices(ctx, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveUnpairedDevices", reflect.TypeOf((*MockDiscoveredDeviceStore)(nil).CountActiveUnpairedDevices), ctx, orgID)
}

// GetActiveUnpairedDevices mocks base method.
func (m *MockDiscoveredDeviceStore) GetActiveUnpairedDevices(ctx context.Context, orgID int64, cursor string, limit int32) ([]*models.DiscoveredDevice, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUnpairedDevices", ctx, orgID, cursor, limit)
	ret0, _ := ret[0].([]*models.DiscoveredDevice)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetActiveUnpairedDevices indicates an expected call of GetActiveUnpairedDevices.
func (mr *MockDiscoveredDeviceStoreMockRecorder) GetActiveUnpairedDevices(ctx, orgID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUnpairedDevices", reflect.TypeOf((*MockDiscoveredDeviceStore)(nil).GetActiveUnpairedDevices), ctx, orgID, cursor, limit)
}

// GetDatabaseID mocks base method.
func (m *MockDiscoveredDeviceStore) GetDatabaseID(ctx context.Context, doi models.DeviceOrgIdentifier) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseID", ctx, doi)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseID indicates an expected call of GetDatabaseID.
func (mr *MockDiscoveredDeviceStoreMockRecorder) GetDatabaseID(ctx, doi interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseID", reflect.TypeOf((*MockDiscoveredDeviceStore)(nil).GetDatabaseID), ctx, doi)
}

// GetDevice mocks base method.
func (m *MockDiscoveredDeviceStore) GetDevice(ctx context.Context, doi models.DeviceOrgIdentifier) (*models.DiscoveredDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", ctx, doi)
	ret0, _ := ret[0].(*models.DiscoveredDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockDiscoveredDeviceStoreMockRecorder) GetDevice(ctx, doi interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockDiscoveredDeviceStore)(nil).GetDevice), ctx, doi)
}

// Save mocks base method.
func (m *MockDiscoveredDeviceStore) Save(ctx context.Context, doi models.DeviceOrgIdentifier, device *models.DiscoveredDevice) (*models.DiscoveredDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, doi, device)
	ret0, _ := ret[0].(*models.DiscoveredDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockDiscoveredDeviceStoreMockRecorder) Save(ctx, doi, device interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDiscoveredDeviceStore)(nil).Save), ctx, doi, device)
}
