// Code generated by MockGen. DO NOT EDIT.
// Source: error.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/diagnostics/models"
	gomock "github.com/golang/mock/gomock"
)

// MockErrorStore is a mock of ErrorStore interface.
type MockErrorStore struct {
	ctrl     *gomock.Controller
	recorder *MockErrorStoreMockRecorder
}

// MockErrorStoreMockRecorder is the mock recorder for MockErrorStore.
type MockErrorStoreMockRecorder struct {
	mock *MockErrorStore
}

// NewMockErrorStore creates a new mock instance.
func NewMockErrorStore(ctrl *gomock.Controller) *MockErrorStore {
	mock := &MockErrorStore{ctrl: ctrl}
	mock.recorder = &MockErrorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorStore) EXPECT() *MockErrorStoreMockRecorder {
	return m.recorder
}

// CloseStaleErrors mocks base method.
func (m *MockErrorStore) CloseStaleErrors(ctx context.Context, threshold time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseStaleErrors", ctx, threshold)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseStaleErrors indicates an expected call of CloseStaleErrors.
func (mr *MockErrorStoreMockRecorder) CloseStaleErrors(ctx, threshold interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseStaleErrors", reflect.TypeOf((*MockErrorStore)(nil).CloseStaleErrors), ctx, threshold)
}

// CountComponents mocks base method.
func (m *MockErrorStore) CountComponents(ctx context.Context, opts *models.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountComponents", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountComponents indicates an expected call of CountComponents.
func (mr *MockErrorStoreMockRecorder) CountComponents(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountComponents", reflect.TypeOf((*MockErrorStore)(nil).CountComponents), ctx, opts)
}

// CountDevices mocks base method.
func (m *MockErrorStore) CountDevices(ctx context.Context, opts *models.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDevices", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDevices indicates an expected call of CountDevices.
func (mr *MockErrorStoreMockRecorder) CountDevices(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDevices", reflect.TypeOf((*MockErrorStore)(nil).CountDevices), ctx, opts)
}

// CountErrors mocks base method.
func (m *MockErrorStore) CountErrors(ctx context.Context, opts *models.QueryOptions) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountErrors", ctx, opts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountErrors indicates an expected call of CountErrors.
func (mr *MockErrorStoreMockRecorder) CountErrors(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountErrors", reflect.TypeOf((*MockErrorStore)(nil).CountErrors), ctx, opts)
}

// GetDeviceErrorSummaries mocks base method.
func (m *MockErrorStore) GetDeviceErrorSummaries(ctx context.Context, orgID int64, deviceIdentifiers []string) (map[string]models.DeviceErrorSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceErrorSummaries", ctx, orgID, deviceIdentifiers)
	ret0, _ := ret[0].(map[string]models.DeviceErrorSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceErrorSummaries indicates an expected call of GetDeviceErrorSummaries.
func (mr *MockErrorStoreMockRecorder) GetDeviceErrorSummaries(ctx, orgID, deviceIdentifiers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceErrorSummaries", reflect.TypeOf((*MockErrorStore)(nil).GetDeviceErrorSummaries), ctx, orgID, deviceIdentifiers)
}

// GetErrorByErrorID mocks base method.
func (m *MockErrorStore) GetErrorByErrorID(ctx context.Context, orgID int64, errorID string) (*models.ErrorMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorByErrorID", ctx, orgID, errorID)
	ret0, _ := ret[0].(*models.ErrorMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorByErrorID indicates an expected call of GetErrorByErrorID.
func (mr *MockErrorStoreMockRecorder) GetErrorByErrorID(ctx, orgID, errorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorByErrorID", reflect.TypeOf((*MockErrorStore)(nil).GetErrorByErrorID), ctx, orgID, errorID)
}

// QueryComponentKeys mocks base method.
func (m *MockErrorStore) QueryComponentKeys(ctx context.Context, opts *models.QueryOptions) ([]models.ComponentKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryComponentKeys", ctx, opts)
	ret0, _ := ret[0].([]models.ComponentKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryComponentKeys indicates an expected call of QueryComponentKeys.
func (mr *MockErrorStoreMockRecorder) QueryComponentKeys(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryComponentKeys", reflect.TypeOf((*MockErrorStore)(nil).QueryComponentKeys), ctx, opts)
}

// QueryDeviceKeys mocks base method.
func (m *MockErrorStore) QueryDeviceKeys(ctx context.Context, opts *models.QueryOptions) ([]models.DeviceKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryDeviceKeys", ctx, opts)
	ret0, _ := ret[0].([]models.DeviceKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryDeviceKeys indicates an expected call of QueryDeviceKeys.
func (mr *MockErrorStoreMockRecorder) QueryDeviceKeys(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryDeviceKeys", reflect.TypeOf((*MockErrorStore)(nil).QueryDeviceKeys), ctx, opts)
}

// QueryErrors mocks base method.
func (m *MockErrorStore) QueryErrors(ctx context.Context, opts *models.QueryOptions) ([]models.ErrorMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryErrors", ctx, opts)
	ret0, _ := ret[0].([]models.ErrorMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryErrors indicates an expected call of QueryErrors.
func (mr *MockErrorStoreMockRecorder) QueryErrors(ctx, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryErrors", reflect.TypeOf((*MockErrorStore)(nil).QueryErrors), ctx, opts)
}

// UpsertError mocks base method.
func (m *MockErrorStore) UpsertError(ctx context.Context, orgID int64, deviceIdentifier string, errMsg *models.ErrorMessage) (*models.ErrorMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertError", ctx, orgID, deviceIdentifier, errMsg)
	ret0, _ := ret[0].(*models.ErrorMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertError indicates an expected call of UpsertError.
func (mr *MockErrorStoreMockRecorder) UpsertError(ctx, orgID, deviceIdentifier, errMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertError", reflect.TypeOf((*MockErrorStore)(nil).UpsertError), ctx, orgID, deviceIdentifier, errMsg)
}
