// Code generated by MockGen. DO NOT EDIT.
// Source: ../user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	interfaces "github.com/btc-mining/proto-fleet/server/internal/domain/stores/interfaces"
	gomock "github.com/golang/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// CreateAdminUserWithOrganization mocks base method.
func (m *MockUserStore) CreateAdminUserWithOrganization(ctx context.Context, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUserWithOrganization", ctx, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdminUserWithOrganization indicates an expected call of CreateAdminUserWithOrganization.
func (mr *MockUserStoreMockRecorder) CreateAdminUserWithOrganization(ctx, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUserWithOrganization", reflect.TypeOf((*MockUserStore)(nil).CreateAdminUserWithOrganization), ctx, userID, username, passwordHash, orgName, orgID, minerAuthPrivateKey, roleName, roleDescription)
}

// GetOrganizationPrivateKey mocks base method.
func (m *MockUserStore) GetOrganizationPrivateKey(ctx context.Context, orgID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationPrivateKey", ctx, orgID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationPrivateKey indicates an expected call of GetOrganizationPrivateKey.
func (mr *MockUserStoreMockRecorder) GetOrganizationPrivateKey(ctx, orgID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationPrivateKey", reflect.TypeOf((*MockUserStore)(nil).GetOrganizationPrivateKey), ctx, orgID)
}

// GetOrganizationsForUser mocks base method.
func (m *MockUserStore) GetOrganizationsForUser(ctx context.Context, userID int64) ([]interfaces.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationsForUser", ctx, userID)
	ret0, _ := ret[0].([]interfaces.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationsForUser indicates an expected call of GetOrganizationsForUser.
func (mr *MockUserStoreMockRecorder) GetOrganizationsForUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationsForUser", reflect.TypeOf((*MockUserStore)(nil).GetOrganizationsForUser), ctx, userID)
}

// GetUserByID mocks base method.
func (m *MockUserStore) GetUserByID(ctx context.Context, userID int64) (interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserStoreMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserStore)(nil).GetUserByID), ctx, userID)
}

// GetUserByUsername mocks base method.
func (m *MockUserStore) GetUserByUsername(ctx context.Context, username string) (interfaces.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(interfaces.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserStoreMockRecorder) GetUserByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserStore)(nil).GetUserByUsername), ctx, username)
}

// HasUser mocks base method.
func (m *MockUserStore) HasUser(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasUser", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasUser indicates an expected call of HasUser.
func (mr *MockUserStoreMockRecorder) HasUser(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasUser", reflect.TypeOf((*MockUserStore)(nil).HasUser), ctx)
}

// PasswordUpdatedAt mocks base method.
func (m *MockUserStore) PasswordUpdatedAt(ctx context.Context, userID int64) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordUpdatedAt", ctx, userID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordUpdatedAt indicates an expected call of PasswordUpdatedAt.
func (mr *MockUserStoreMockRecorder) PasswordUpdatedAt(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordUpdatedAt", reflect.TypeOf((*MockUserStore)(nil).PasswordUpdatedAt), ctx, userID)
}

// UpdateUserPassword mocks base method.
func (m *MockUserStore) UpdateUserPassword(ctx context.Context, userID int64, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockUserStoreMockRecorder) UpdateUserPassword(ctx, userID, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockUserStore)(nil).UpdateUserPassword), ctx, userID, passwordHash)
}

// UpdateUserUsername mocks base method.
func (m *MockUserStore) UpdateUserUsername(ctx context.Context, userID int64, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserUsername", ctx, userID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserUsername indicates an expected call of UpdateUserUsername.
func (mr *MockUserStoreMockRecorder) UpdateUserUsername(ctx, userID, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserUsername", reflect.TypeOf((*MockUserStore)(nil).UpdateUserUsername), ctx, userID, username)
}
