// Code generated by MockGen. DO NOT EDIT.
// Source: maintenance.go
//
// Generated by this command:
//
//	mockgen -source=maintenance.go -destination=mocks/mock_maintenance_store.go -package=mocks MaintenanceStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/block/proto-fleet/server/internal/domain/maintenance/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMaintenanceStore is a mock of MaintenanceStore interface.
type MockMaintenanceStore struct {
	ctrl     *gomock.Controller
	recorder *MockMaintenanceStoreMockRecorder
	isgomock struct{}
}

// MockMaintenanceStoreMockRecorder is the mock recorder for MockMaintenanceStore.
type MockMaintenanceStoreMockRecorder struct {
	mock *MockMaintenanceStore
}

// NewMockMaintenanceStore creates a new mock instance.
func NewMockMaintenanceStore(ctrl *gomock.Controller) *MockMaintenanceStore {
	mock := &MockMaintenanceStore{ctrl: ctrl}
	mock.recorder = &MockMaintenanceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaintenanceStore) EXPECT() *MockMaintenanceStoreMockRecorder {
	return m.recorder
}

// AvgTicketAgeHours mocks base method.
func (m *MockMaintenanceStore) AvgTicketAgeHours(ctx context.Context, orgID int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvgTicketAgeHours", ctx, orgID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AvgTicketAgeHours indicates an expected call of AvgTicketAgeHours.
func (mr *MockMaintenanceStoreMockRecorder) AvgTicketAgeHours(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvgTicketAgeHours", reflect.TypeOf((*MockMaintenanceStore)(nil).AvgTicketAgeHours), ctx, orgID)
}

// BulkAssignTickets mocks base method.
func (m *MockMaintenanceStore) BulkAssignTickets(ctx context.Context, orgID int64, ticketIDs []int64, assigneeUserID *int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAssignTickets", ctx, orgID, ticketIDs, assigneeUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAssignTickets indicates an expected call of BulkAssignTickets.
func (mr *MockMaintenanceStoreMockRecorder) BulkAssignTickets(ctx, orgID, ticketIDs, assigneeUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAssignTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).BulkAssignTickets), ctx, orgID, ticketIDs, assigneeUserID)
}

// BulkCloseTickets mocks base method.
func (m *MockMaintenanceStore) BulkCloseTickets(ctx context.Context, orgID int64, ticketIDs []int64, resolution, repairLocation int16, notes *string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCloseTickets", ctx, orgID, ticketIDs, resolution, repairLocation, notes)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkCloseTickets indicates an expected call of BulkCloseTickets.
func (mr *MockMaintenanceStoreMockRecorder) BulkCloseTickets(ctx, orgID, ticketIDs, resolution, repairLocation, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCloseTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).BulkCloseTickets), ctx, orgID, ticketIDs, resolution, repairLocation, notes)
}

// BulkMarkUrgent mocks base method.
func (m *MockMaintenanceStore) BulkMarkUrgent(ctx context.Context, orgID int64, ticketIDs []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkUrgent", ctx, orgID, ticketIDs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkUrgent indicates an expected call of BulkMarkUrgent.
func (mr *MockMaintenanceStoreMockRecorder) BulkMarkUrgent(ctx, orgID, ticketIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkUrgent", reflect.TypeOf((*MockMaintenanceStore)(nil).BulkMarkUrgent), ctx, orgID, ticketIDs)
}

// BulkUpdateTicketStatus mocks base method.
func (m *MockMaintenanceStore) BulkUpdateTicketStatus(ctx context.Context, orgID int64, ticketIDs []int64, newStatus int16) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateTicketStatus", ctx, orgID, ticketIDs, newStatus)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUpdateTicketStatus indicates an expected call of BulkUpdateTicketStatus.
func (mr *MockMaintenanceStoreMockRecorder) BulkUpdateTicketStatus(ctx, orgID, ticketIDs, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateTicketStatus", reflect.TypeOf((*MockMaintenanceStore)(nil).BulkUpdateTicketStatus), ctx, orgID, ticketIDs, newStatus)
}

// CountOverdueTickets mocks base method.
func (m *MockMaintenanceStore) CountOverdueTickets(ctx context.Context, orgID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOverdueTickets", ctx, orgID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOverdueTickets indicates an expected call of CountOverdueTickets.
func (mr *MockMaintenanceStoreMockRecorder) CountOverdueTickets(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOverdueTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).CountOverdueTickets), ctx, orgID)
}

// CountRepairTickets mocks base method.
func (m *MockMaintenanceStore) CountRepairTickets(ctx context.Context, filter models.ListFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRepairTickets", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRepairTickets indicates an expected call of CountRepairTickets.
func (mr *MockMaintenanceStoreMockRecorder) CountRepairTickets(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRepairTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).CountRepairTickets), ctx, filter)
}

// CountTicketsByStatus mocks base method.
func (m *MockMaintenanceStore) CountTicketsByStatus(ctx context.Context, orgID int64) (map[int16]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTicketsByStatus", ctx, orgID)
	ret0, _ := ret[0].(map[int16]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTicketsByStatus indicates an expected call of CountTicketsByStatus.
func (mr *MockMaintenanceStoreMockRecorder) CountTicketsByStatus(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTicketsByStatus", reflect.TypeOf((*MockMaintenanceStore)(nil).CountTicketsByStatus), ctx, orgID)
}

// CountUnassignedTickets mocks base method.
func (m *MockMaintenanceStore) CountUnassignedTickets(ctx context.Context, orgID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnassignedTickets", ctx, orgID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnassignedTickets indicates an expected call of CountUnassignedTickets.
func (mr *MockMaintenanceStoreMockRecorder) CountUnassignedTickets(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnassignedTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).CountUnassignedTickets), ctx, orgID)
}

// CountUrgentTickets mocks base method.
func (m *MockMaintenanceStore) CountUrgentTickets(ctx context.Context, orgID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUrgentTickets", ctx, orgID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUrgentTickets indicates an expected call of CountUrgentTickets.
func (mr *MockMaintenanceStoreMockRecorder) CountUrgentTickets(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUrgentTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).CountUrgentTickets), ctx, orgID)
}

// CreateRepairTicket mocks base method.
func (m *MockMaintenanceStore) CreateRepairTicket(ctx context.Context, params models.CreateParams, ticketNumber string) (*models.RepairTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRepairTicket", ctx, params, ticketNumber)
	ret0, _ := ret[0].(*models.RepairTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRepairTicket indicates an expected call of CreateRepairTicket.
func (mr *MockMaintenanceStoreMockRecorder) CreateRepairTicket(ctx, params, ticketNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRepairTicket", reflect.TypeOf((*MockMaintenanceStore)(nil).CreateRepairTicket), ctx, params, ticketNumber)
}

// CreateTicketComment mocks base method.
func (m *MockMaintenanceStore) CreateTicketComment(ctx context.Context, orgID, ticketID, userID int64, userName, text string) (*models.TicketComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTicketComment", ctx, orgID, ticketID, userID, userName, text)
	ret0, _ := ret[0].(*models.TicketComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTicketComment indicates an expected call of CreateTicketComment.
func (mr *MockMaintenanceStoreMockRecorder) CreateTicketComment(ctx, orgID, ticketID, userID, userName, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTicketComment", reflect.TypeOf((*MockMaintenanceStore)(nil).CreateTicketComment), ctx, orgID, ticketID, userID, userName, text)
}

// GetRepairTicket mocks base method.
func (m *MockMaintenanceStore) GetRepairTicket(ctx context.Context, orgID, id int64) (*models.RepairTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepairTicket", ctx, orgID, id)
	ret0, _ := ret[0].(*models.RepairTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepairTicket indicates an expected call of GetRepairTicket.
func (mr *MockMaintenanceStoreMockRecorder) GetRepairTicket(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepairTicket", reflect.TypeOf((*MockMaintenanceStore)(nil).GetRepairTicket), ctx, orgID, id)
}

// InsertTicketPart mocks base method.
func (m *MockMaintenanceStore) InsertTicketPart(ctx context.Context, orgID, ticketID int64, partName string, quantity int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTicketPart", ctx, orgID, ticketID, partName, quantity)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTicketPart indicates an expected call of InsertTicketPart.
func (mr *MockMaintenanceStoreMockRecorder) InsertTicketPart(ctx, orgID, ticketID, partName, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTicketPart", reflect.TypeOf((*MockMaintenanceStore)(nil).InsertTicketPart), ctx, orgID, ticketID, partName, quantity)
}

// ListCompletedTickets mocks base method.
func (m *MockMaintenanceStore) ListCompletedTickets(ctx context.Context, filter models.CompletedFilter) ([]models.RepairTicketSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompletedTickets", ctx, filter)
	ret0, _ := ret[0].([]models.RepairTicketSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompletedTickets indicates an expected call of ListCompletedTickets.
func (mr *MockMaintenanceStoreMockRecorder) ListCompletedTickets(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompletedTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).ListCompletedTickets), ctx, filter)
}

// ListRepairTickets mocks base method.
func (m *MockMaintenanceStore) ListRepairTickets(ctx context.Context, filter models.ListFilter) ([]models.RepairTicketSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepairTickets", ctx, filter)
	ret0, _ := ret[0].([]models.RepairTicketSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepairTickets indicates an expected call of ListRepairTickets.
func (mr *MockMaintenanceStoreMockRecorder) ListRepairTickets(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepairTickets", reflect.TypeOf((*MockMaintenanceStore)(nil).ListRepairTickets), ctx, filter)
}

// ListTicketComments mocks base method.
func (m *MockMaintenanceStore) ListTicketComments(ctx context.Context, orgID, ticketID int64) ([]models.TicketComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTicketComments", ctx, orgID, ticketID)
	ret0, _ := ret[0].([]models.TicketComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTicketComments indicates an expected call of ListTicketComments.
func (mr *MockMaintenanceStoreMockRecorder) ListTicketComments(ctx, orgID, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTicketComments", reflect.TypeOf((*MockMaintenanceStore)(nil).ListTicketComments), ctx, orgID, ticketID)
}

// ListTicketParts mocks base method.
func (m *MockMaintenanceStore) ListTicketParts(ctx context.Context, orgID, ticketID int64) ([]models.PartUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTicketParts", ctx, orgID, ticketID)
	ret0, _ := ret[0].([]models.PartUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTicketParts indicates an expected call of ListTicketParts.
func (mr *MockMaintenanceStoreMockRecorder) ListTicketParts(ctx, orgID, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTicketParts", reflect.TypeOf((*MockMaintenanceStore)(nil).ListTicketParts), ctx, orgID, ticketID)
}

// ListTicketsByMiner mocks base method.
func (m *MockMaintenanceStore) ListTicketsByMiner(ctx context.Context, orgID int64, minerIdentifier string) ([]models.RepairTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTicketsByMiner", ctx, orgID, minerIdentifier)
	ret0, _ := ret[0].([]models.RepairTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTicketsByMiner indicates an expected call of ListTicketsByMiner.
func (mr *MockMaintenanceStoreMockRecorder) ListTicketsByMiner(ctx, orgID, minerIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTicketsByMiner", reflect.TypeOf((*MockMaintenanceStore)(nil).ListTicketsByMiner), ctx, orgID, minerIdentifier)
}

// ListTicketsByRack mocks base method.
func (m *MockMaintenanceStore) ListTicketsByRack(ctx context.Context, orgID, rackID int64) ([]models.RepairTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTicketsByRack", ctx, orgID, rackID)
	ret0, _ := ret[0].([]models.RepairTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTicketsByRack indicates an expected call of ListTicketsByRack.
func (mr *MockMaintenanceStoreMockRecorder) ListTicketsByRack(ctx, orgID, rackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTicketsByRack", reflect.TypeOf((*MockMaintenanceStore)(nil).ListTicketsByRack), ctx, orgID, rackID)
}

// NextTicketNumber mocks base method.
func (m *MockMaintenanceStore) NextTicketNumber(ctx context.Context, orgID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextTicketNumber", ctx, orgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextTicketNumber indicates an expected call of NextTicketNumber.
func (mr *MockMaintenanceStoreMockRecorder) NextTicketNumber(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextTicketNumber", reflect.TypeOf((*MockMaintenanceStore)(nil).NextTicketNumber), ctx, orgID)
}

// SetTicketParts mocks base method.
func (m *MockMaintenanceStore) SetTicketParts(ctx context.Context, orgID, ticketID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTicketParts", ctx, orgID, ticketID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTicketParts indicates an expected call of SetTicketParts.
func (mr *MockMaintenanceStoreMockRecorder) SetTicketParts(ctx, orgID, ticketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTicketParts", reflect.TypeOf((*MockMaintenanceStore)(nil).SetTicketParts), ctx, orgID, ticketID)
}

// SoftDeleteRepairTicket mocks base method.
func (m *MockMaintenanceStore) SoftDeleteRepairTicket(ctx context.Context, orgID, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteRepairTicket", ctx, orgID, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteRepairTicket indicates an expected call of SoftDeleteRepairTicket.
func (mr *MockMaintenanceStoreMockRecorder) SoftDeleteRepairTicket(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteRepairTicket", reflect.TypeOf((*MockMaintenanceStore)(nil).SoftDeleteRepairTicket), ctx, orgID, id)
}

// SoftDeleteTicketComment mocks base method.
func (m *MockMaintenanceStore) SoftDeleteTicketComment(ctx context.Context, orgID, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteTicketComment", ctx, orgID, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteTicketComment indicates an expected call of SoftDeleteTicketComment.
func (mr *MockMaintenanceStoreMockRecorder) SoftDeleteTicketComment(ctx, orgID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteTicketComment", reflect.TypeOf((*MockMaintenanceStore)(nil).SoftDeleteTicketComment), ctx, orgID, id)
}

// UpdateRepairTicket mocks base method.
func (m *MockMaintenanceStore) UpdateRepairTicket(ctx context.Context, params models.UpdateParams) (*models.RepairTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRepairTicket", ctx, params)
	ret0, _ := ret[0].(*models.RepairTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRepairTicket indicates an expected call of UpdateRepairTicket.
func (mr *MockMaintenanceStoreMockRecorder) UpdateRepairTicket(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRepairTicket", reflect.TypeOf((*MockMaintenanceStore)(nil).UpdateRepairTicket), ctx, params)
}
