// Code generated by MockGen. DO NOT EDIT.
// Source: error.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/btc-mining/proto-fleet/server/internal/domain/diagnostics/models"
	gomock "github.com/golang/mock/gomock"
)

// MockErrorStore is a mock of ErrorStore interface.
type MockErrorStore struct {
	ctrl     *gomock.Controller
	recorder *MockErrorStoreMockRecorder
}

// MockErrorStoreMockRecorder is the mock recorder for MockErrorStore.
type MockErrorStoreMockRecorder struct {
	mock *MockErrorStore
}

// NewMockErrorStore creates a new mock instance.
func NewMockErrorStore(ctrl *gomock.Controller) *MockErrorStore {
	mock := &MockErrorStore{ctrl: ctrl}
	mock.recorder = &MockErrorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorStore) EXPECT() *MockErrorStoreMockRecorder {
	return m.recorder
}

// GetErrorByErrorID mocks base method.
func (m *MockErrorStore) GetErrorByErrorID(ctx context.Context, orgID int64, errorID string) (*models.ErrorMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetErrorByErrorID", ctx, orgID, errorID)
	ret0, _ := ret[0].(*models.ErrorMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetErrorByErrorID indicates an expected call of GetErrorByErrorID.
func (mr *MockErrorStoreMockRecorder) GetErrorByErrorID(ctx, orgID, errorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetErrorByErrorID", reflect.TypeOf((*MockErrorStore)(nil).GetErrorByErrorID), ctx, orgID, errorID)
}

// UpsertError mocks base method.
func (m *MockErrorStore) UpsertError(ctx context.Context, orgID int64, deviceIdentifier string, errMsg *models.ErrorMessage) (*models.ErrorMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertError", ctx, orgID, deviceIdentifier, errMsg)
	ret0, _ := ret[0].(*models.ErrorMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertError indicates an expected call of UpsertError.
func (mr *MockErrorStoreMockRecorder) UpsertError(ctx, orgID, deviceIdentifier, errMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertError", reflect.TypeOf((*MockErrorStore)(nil).UpsertError), ctx, orgID, deviceIdentifier, errMsg)
}
