// Code generated by MockGen. DO NOT EDIT.
// Source: execution_service.go
//
// Generated by this command:
//
//	mockgen -source=execution_service.go -destination=mocks/mock_miner_getter.go -package=mocks MinerGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/proto-at-block/proto-fleet/server/internal/domain/miner/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockMinerGetter is a mock of MinerGetter interface.
type MockMinerGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMinerGetterMockRecorder
	isgomock struct{}
}

// MockMinerGetterMockRecorder is the mock recorder for MockMinerGetter.
type MockMinerGetterMockRecorder struct {
	mock *MockMinerGetter
}

// NewMockMinerGetter creates a new mock instance.
func NewMockMinerGetter(ctrl *gomock.Controller) *MockMinerGetter {
	mock := &MockMinerGetter{ctrl: ctrl}
	mock.recorder = &MockMinerGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinerGetter) EXPECT() *MockMinerGetterMockRecorder {
	return m.recorder
}

// GetMiner mocks base method.
func (m *MockMinerGetter) GetMiner(ctx context.Context, deviceID int64) (interfaces.Miner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMiner", ctx, deviceID)
	ret0, _ := ret[0].(interfaces.Miner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMiner indicates an expected call of GetMiner.
func (mr *MockMinerGetterMockRecorder) GetMiner(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMiner", reflect.TypeOf((*MockMinerGetter)(nil).GetMiner), ctx, deviceID)
}
