package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// ErrorVariant represents a Rust enum variant with its fields
type ErrorVariant struct {
	Name   string
	Fields []Field
}

// Field represents a field in a Rust struct variant
type Field struct {
	Name     string
	Type     string
	GoType   string
	JSONType string
}

// ParsedData holds all parsed error information
type ParsedData struct {
	Variants []ErrorVariant
}

func main() {
	var (
		inputFile  = flag.String("input", "", "Path to error_details.rs")
		outputFile = flag.String("output", "", "Path to output definitions.go")
	)
	flag.Parse()

	// Use default paths if not specified
	if *inputFile == "" {
		*inputFile = filepath.Join("..", "..", "..", "miner-firmware", "crates", "miner_utils", "src", "error_details.rs")
	}
	if *outputFile == "" {
		*outputFile = filepath.Join("internal", "errors", "definitions_generated.go")
	}

	// Read input file
	content, err := os.ReadFile(*inputFile)
	if err != nil {
		log.Fatalf("Failed to read input file: %v", err)
	}

	// Parse the Rust enum
	data := parseRustEnum(string(content))

	// Generate Go code
	if err := generateGoCode(data, *outputFile); err != nil {
		log.Fatalf("Failed to generate Go code: %v", err)
	}

	fmt.Printf("Generated %s from %s\n", *outputFile, *inputFile)
}

func parseRustEnum(content string) ParsedData {
	var data ParsedData

	// Regular expression to match enum variants
	// Matches patterns like:
	// VariantName { field1: Type1, field2: Type2 }
	// VariantName {}
	variantRegex := regexp.MustCompile(`(?m)^\s*(\w+)\s*\{([^}]*)\}`)
	fieldRegex := regexp.MustCompile(`(\w+):\s*([^,]+)`)

	// Find the ErrorDetails enum
	enumStart := strings.Index(content, "pub enum ErrorDetails {")
	if enumStart == -1 {
		log.Fatal("Could not find ErrorDetails enum")
	}

	// Find the end of the enum (matching closing brace)
	braceCount := 0
	enumEnd := enumStart
	inEnum := false
	for i := enumStart; i < len(content); i++ {
		if content[i] == '{' {
			braceCount++
			inEnum = true
		} else if content[i] == '}' {
			braceCount--
			if inEnum && braceCount == 0 {
				enumEnd = i
				break
			}
		}
	}

	enumContent := content[enumStart:enumEnd]

	// Parse each variant
	matches := variantRegex.FindAllStringSubmatch(enumContent, -1)
	for _, match := range matches {
		variantName := match[1]
		fieldsStr := match[2]

		// Skip the None variant
		if variantName == "None" {
			continue
		}

		variant := ErrorVariant{
			Name: variantName,
		}

		// Parse fields
		if strings.TrimSpace(fieldsStr) != "" {
			fieldMatches := fieldRegex.FindAllStringSubmatch(fieldsStr, -1)
			for _, fieldMatch := range fieldMatches {
				fieldName := fieldMatch[1]
				fieldType := strings.TrimSpace(fieldMatch[2])

				field := Field{
					Name:     fieldName,
					Type:     fieldType,
					GoType:   rustTypeToGoType(fieldType),
					JSONType: rustTypeToJSONType(fieldType),
				}
				variant.Fields = append(variant.Fields, field)
			}
		}

		data.Variants = append(data.Variants, variant)
	}

	return data
}

func rustTypeToGoType(rustType string) string {
	switch {
	case rustType == "u8", rustType == "u16", rustType == "u32", rustType == "usize":
		return "number"
	case rustType == "u64":
		return "number"
	case rustType == "i8", rustType == "i16", rustType == "i32", rustType == "i64":
		return "number"
	case rustType == "f32", rustType == "f64":
		return "number"
	case rustType == "bool":
		return "boolean"
	case rustType == "String":
		return "string"
	case strings.HasPrefix(rustType, "Vec<"):
		return "array"
	case rustType == "PsuFault":
		return "object"
	default:
		return "string"
	}
}

func rustTypeToJSONType(rustType string) string {
	// For JSON representation in details field
	switch {
	case rustType == "u8", rustType == "u16", rustType == "u32", rustType == "usize":
		return "int"
	case rustType == "f32", rustType == "f64":
		return "float"
	case rustType == "bool":
		return "bool"
	case rustType == "String":
		return "string"
	case strings.HasPrefix(rustType, "Vec<"):
		return "array"
	default:
		return "interface{}"
	}
}

func generateGoCode(data ParsedData, outputFile string) error {
	tmpl := `// Code generated by cmd/generate/main.go. DO NOT EDIT.
// Source: miner-firmware/crates/miner_utils/src/error_details.rs

package errors

// GetGeneratedErrorDefinitions returns error definitions generated from Rust source
// These match the ErrorDetails enum in miner-firmware
func GetGeneratedErrorDefinitions() []ErrorDefinition {
	return []ErrorDefinition{
{{range .Variants}}		{
			Code:         "{{.Name}}",
			Name:         "{{formatName .Name}}",
			Description:  "{{formatDescription .Name}}",
			Category:     "{{getCategory .Name}}",
			DefaultLevel: "{{getDefaultLevel .Name}}",
			Parameters: []ParameterDefinition{
{{range .Fields}}				{Name: "{{.Name}}", Type: "{{.GoType}}", Required: true, Description: "{{formatFieldDescription .Name}}"},
{{end}}			},
		},
{{end}}	}
}

// GetAllErrorDefinitions combines hardcoded and generated definitions
func GetAllErrorDefinitions() []ErrorDefinition {
	// Start with generated definitions
	defs := GetGeneratedErrorDefinitions()

	// Add any custom definitions that aren't in the Rust source
	// (currently none, but this allows for extension)

	return defs
}
`

	funcMap := template.FuncMap{
		"formatName":             formatName,
		"formatDescription":      formatDescription,
		"formatFieldDescription": formatFieldDescription,
		"getCategory":            getCategory,
		"getDefaultLevel":        getDefaultLevel,
	}

	t, err := template.New("definitions").Funcs(funcMap).Parse(tmpl)
	if err != nil {
		return fmt.Errorf("failed to parse template: %v", err)
	}

	// Create output file
	outFile, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %v", err)
	}
	defer outFile.Close()

	// Execute template
	if err := t.Execute(outFile, data); err != nil {
		return fmt.Errorf("failed to execute template: %v", err)
	}

	return nil
}

// Helper functions for template
func formatName(variantName string) string {
	// Convert CamelCase to Title Case
	// e.g., "FanSlow" -> "Fan Slow"
	result := ""
	for i, r := range variantName {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result += " "
		}
		result += string(r)
	}
	return result
}

func formatDescription(variantName string) string {
	descriptions := map[string]string{
		"AsicOverTemp":               "ASIC temperature exceeds safe operating limits",
		"AsicUnderTemp":              "ASIC temperature is below minimum operating threshold",
		"AsicOverVoltage":            "ASIC voltage exceeds safe operating limits",
		"AsicUnderVoltage":           "ASIC voltage is below minimum operating threshold",
		"AsicEcc":                    "ASIC ECC errors detected",
		"AsicEnumeration":            "Failed to enumerate expected number of ASICs",
		"AsicNotHashing":             "One or more ASICs are not producing valid hashes",
		"FanSlow":                    "Fan RPM is below expected speed",
		"FanNotSpinning":             "Fan has stopped spinning",
		"FanConnectedInImmersion":    "Fan connected while in immersion cooling mode",
		"HashboardOverheat":          "Hashboard temperature exceeds safe operating limits",
		"HashboardOverVoltage":       "Hashboard voltage exceeds safe operating limits",
		"HashboardUnderVoltage":      "Hashboard voltage is below minimum operating threshold",
		"HashboardOverCurrent":       "Hashboard current exceeds safe operating limits",
		"HashboardPowerLost":         "Hashboard has lost power",
		"HashboardUsbConnectionLost": "Lost USB connection to hashboard",
		"PoolConnectionLost":         "Lost connection to mining pool",
		"NoPoolConfigured":           "No mining pool has been configured",
		"PsuHardwareFault":           "Power supply unit has detected a hardware fault",
		"PsuCommsLost":               "Lost communication with power supply unit",
		"MixedHashboardTypesInBay":   "Different hashboard types detected in the same system",
		"InsufficientCooling":        "Not enough operational fans for adequate cooling",
		"PsuRecoveryInProgress":      "PSU recovery in progress",
		"HbRecoveryInProgress":       "Hashboard recovery in progress",
	}

	if desc, ok := descriptions[variantName]; ok {
		return desc
	}
	return formatName(variantName)
}

func formatFieldDescription(fieldName string) string {
	descriptions := map[string]string{
		"hb_slot":               "Hashboard slot number",
		"hb_sn":                 "Hashboard serial number",
		"asic_index":            "ASIC index",
		"temperature":           "Temperature in Celsius",
		"voltage":               "Voltage",
		"current":               "Current in Amperes",
		"asics":                 "Array of ASIC indices",
		"fan_bay_index":         "Fan bay index",
		"fan_id":                "Fan identifier",
		"fan_pwm_target_pct":    "Target PWM percentage",
		"fan_rpm_tach":          "Actual fan RPM from tachometer",
		"pool_id":               "Pool identifier",
		"pool_url":              "Pool URL",
		"psu_bay_index":         "PSU bay index",
		"psu_index":             "PSU index",
		"psu_sn":                "PSU serial number",
		"fault":                 "Fault information",
		"faults":                "List of fault types",
		"errors":                "List of error types",
		"hashboards":            "List of hashboard information",
		"bay_index":             "Bay index",
		"num_operational_fans":  "Number of operational fans",
		"num_expected_fans":     "Number of expected fans",
		"failed_fans":           "Array of failed fan IDs",
		"required_fans":         "Array of required fan IDs",
	}

	if desc, ok := descriptions[fieldName]; ok {
		return desc
	}

	// Convert snake_case to Title Case for unknown fields
	parts := strings.Split(fieldName, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, " ")
}

func getCategory(variantName string) string {
	switch {
	case strings.HasPrefix(variantName, "Asic"):
		return "ASIC"
	case strings.HasPrefix(variantName, "Fan") || strings.Contains(variantName, "Cooling"):
		return "Cooling"
	case strings.HasPrefix(variantName, "Hashboard") || strings.HasPrefix(variantName, "Hb"):
		return "Hashboard"
	case strings.HasPrefix(variantName, "Psu"):
		return "PSU"
	case strings.Contains(variantName, "Pool"):
		return "Pool"
	default:
		return "System"
	}
}

func getDefaultLevel(variantName string) string {
	// Warning-level errors (less critical)
	warnings := []string{
		"AsicOverTemp",
		"AsicUnderTemp",
		"FanSlow",
		"AsicNotHashing",
		"PsuRecoveryInProgress",
		"HbRecoveryInProgress",
	}

	for _, warning := range warnings {
		if variantName == warning {
			return "Warning"
		}
	}

	// Everything else is an Error
	return "Error"
}