CREATE TABLE discovered_device (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    org_id BIGINT NOT NULL,
    device_identifier VARCHAR(255) NOT NULL,
    model VARCHAR(255) NULL,
    manufacturer VARCHAR(255) NULL,
    type VARCHAR(50) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    port VARCHAR(10) NOT NULL,
    url_scheme VARCHAR(10) NOT NULL,
    discovery_metadata TEXT NULL,
    first_discovered TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    last_seen TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,

    CONSTRAINT fk_discovered_device_org FOREIGN KEY (org_id) REFERENCES organization(id),
    UNIQUE KEY uk_discovered_device_org_identifier (org_id, device_identifier),
    INDEX idx_discovered_device_org (org_id),
    INDEX idx_discovered_device_type (org_id, type),
    INDEX idx_discovered_device_org_active (org_id, is_active, deleted_at),
    INDEX idx_discovered_device_ip (ip_address, port, url_scheme),
    INDEX idx_discovered_device_identifier (device_identifier)
);
