DROP VIEW IF EXISTS firmware_rollout_suppressed_device;
DROP VIEW IF EXISTS release_channel_conflict;
DROP VIEW IF EXISTS release_channel_member;
DROP VIEW IF EXISTS release_channel_resolution;
DROP VIEW IF EXISTS release_channel_match;
DROP VIEW IF EXISTS release_channel_placement;
DROP TRIGGER IF EXISTS device_firmware_deployment_updated ON device_firmware_deployment;
DROP TRIGGER IF EXISTS device_firmware_deployment_inserted ON device_firmware_deployment;
DROP TABLE IF EXISTS device_firmware_deployment;
DROP TRIGGER IF EXISTS firmware_rollout_device_updated ON firmware_rollout_device;
DROP TRIGGER IF EXISTS firmware_rollout_device_inserted ON firmware_rollout_device;
DROP FUNCTION IF EXISTS firmware_rollout_touch_from_rows();
DROP TABLE IF EXISTS firmware_rollout_device;
DROP TRIGGER IF EXISTS firmware_rollout_revision ON firmware_rollout;
DROP FUNCTION IF EXISTS firmware_rollout_bump_revision();
DROP TABLE IF EXISTS firmware_rollout;
DROP TABLE IF EXISTS release_channel_firmware;
DROP TABLE IF EXISTS release_channel_target;
DROP TABLE IF EXISTS release_channel;
DROP FUNCTION IF EXISTS release_channel_pair_key(text);
