export const mockInfraDevices = [
  {
    id: "fan-aus-1-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 1",
    ipAddress: "10.0.2.201",
    status: "online",
    rpm: 3200,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 120,
    temperatureC: 42,
    firmware: "v2.1.4",
    lastSeen: "Just now",
  },
  {
    id: "fan-aus-1-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 1",
    ipAddress: "10.0.2.202",
    status: "online",
    rpm: 3200,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 118,
    temperatureC: 43,
    firmware: "v2.1.4",
    lastSeen: "Just now",
  },
  {
    id: "fan-aus-1-3",
    name: "Fan Unit 3",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 1",
    ipAddress: "10.0.2.203",
    status: "offline",
    rpm: 0,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 0,
    temperatureC: null,
    firmware: "v2.1.4",
    lastSeen: "3d ago",
  },
  {
    id: "fan-aus-2-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 2",
    ipAddress: "10.0.2.211",
    status: "online",
    rpm: 3100,
    model: "Delta EFB0812EH",
    issues: 0,
    powerW: 115,
    temperatureC: 41,
    firmware: "v2.0.8",
    lastSeen: "Just now",
  },
  {
    id: "fan-aus-2-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Austin",
    buildingName: "Building 2",
    ipAddress: "10.0.2.212",
    status: "online",
    rpm: 3100,
    model: "Delta EFB0812EH",
    issues: 0,
    powerW: 116,
    temperatureC: 42,
    firmware: "v2.0.8",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-1-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 1",
    ipAddress: "10.0.3.201",
    status: "online",
    rpm: 2800,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 95,
    temperatureC: 38,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-1-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 1",
    ipAddress: "10.0.3.202",
    status: "online",
    rpm: 2800,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 95,
    temperatureC: 38,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-2-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 2",
    ipAddress: "10.0.3.211",
    status: "online",
    rpm: 2900,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 96,
    temperatureC: 39,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-5-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 5",
    ipAddress: "10.0.3.251",
    status: "online",
    rpm: 2750,
    model: "Nidec V12E12BMM9",
    issues: 0,
    powerW: 94,
    temperatureC: 37,
    firmware: "v3.0.1",
    lastSeen: "Just now",
  },
  {
    id: "fan-den-5-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Denver",
    buildingName: "Building 5",
    ipAddress: "10.0.3.252",
    status: "degraded",
    rpm: 1200,
    model: "Nidec V12E12BMM9",
    issues: 1,
    powerW: 98,
    temperatureC: 45,
    firmware: "v3.0.1",
    lastSeen: "2h ago",
  },
  {
    id: "fan-mia-2-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 2",
    ipAddress: "10.0.4.211",
    status: "online",
    rpm: 3400,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 130,
    temperatureC: 44,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-2-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 2",
    ipAddress: "10.0.4.212",
    status: "online",
    rpm: 3400,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 130,
    temperatureC: 44,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-2-3",
    name: "Fan Unit 3",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 2",
    ipAddress: "10.0.4.213",
    status: "online",
    rpm: 3350,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 128,
    temperatureC: 43,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-10-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 10",
    ipAddress: "10.0.4.301",
    status: "online",
    rpm: 3000,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 125,
    temperatureC: 41,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mia-10-2",
    name: "Fan Unit 2",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Miami",
    buildingName: "Building 10",
    ipAddress: "10.0.4.302",
    status: "online",
    rpm: 3000,
    model: "Sunon PMD2412PMB",
    issues: 0,
    powerW: 125,
    temperatureC: 41,
    firmware: "v2.5.0",
    lastSeen: "Just now",
  },
  {
    id: "fan-mar-1-1",
    name: "Fan Unit 1",
    deviceType: "fan",
    subtype: "Exhaust fan",
    siteName: "Marfa",
    buildingName: "Building 1",
    ipAddress: "10.0.5.201",
    status: "online",
    rpm: 2600,
    model: "Delta EFB1248VH",
    issues: 0,
    powerW: 90,
    temperatureC: 35,
    firmware: "v2.1.4",
    lastSeen: "Just now",
  },
];
