@host = http://localhost:4000

### Authenticate
# @name authenticate
POST {{host}}/auth.v1.AuthService/Authenticate
Content-Type: application/json

{
  "username": "protofleet",
  "password": "protofleet"
}

###
@session_cookie = {{authenticate.response.headers.Set-Cookie}}

# Configurable filter variables
# result_view: RESULT_VIEW_ERROR (flat), RESULT_VIEW_DEVICE (by device), RESULT_VIEW_COMPONENT (by component)
# severities: SEVERITY_CRITICAL, SEVERITY_MAJOR, SEVERITY_MINOR, SEVERITY_INFO
# component_types: COMPONENT_TYPE_PSU, COMPONENT_TYPE_HASH_BOARD, COMPONENT_TYPE_FAN, COMPONENT_TYPE_CONTROL_BOARD
@result_view = RESULT_VIEW_ERROR
@filter_severities = ["SEVERITY_CRITICAL", "SEVERITY_MAJOR"]
@filter_component_types = []
@filter_device_identifiers = []
@include_closed = false

### Query errors
POST {{host}}/errors.v1.ErrorQueryService/Query
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "result_view": "{{result_view}}",
  "filter": {
    "simple": {
      "severities": {{filter_severities}},
      "component_types": {{filter_component_types}},
      "device_identifiers": {{filter_device_identifiers}}
    },
    "include_closed": {{include_closed}}
  },
  "page_size": 50
}

### Get single error by ID
POST {{host}}/errors.v1.ErrorQueryService/GetError
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "error_id": "TODO_REPLACE_WITH_ERROR_ID"
}

### List all canonical miner errors
POST {{host}}/errors.v1.ErrorQueryService/ListMinerErrors
Content-Type: application/json
Cookie: {{session_cookie}}

{}

### Watch for real-time error updates (streaming)
POST {{host}}/errors.v1.ErrorQueryService/Watch HTTP/2
Content-Type: application/grpc+json; charset=utf-8
Accept: application/grpc+json
Cookie: {{session_cookie}}

{
  "filter": {
    "simple": {
      "severities": {{filter_severities}},
      "component_types": {{filter_component_types}},
      "device_identifiers": {{filter_device_identifiers}}
    },
    "include_closed": {{include_closed}}
  }
}
