@host = http://localhost:4000

### Create admin user
POST {{host}}/onboarding.v1.OnboardingService/CreateAdminLogin
Content-Type: application/json

{
  "username": "protofleet",
  "password": "protofleet"
}

### Get fleet init status (pre-auth check)
POST {{host}}/onboarding.v1.OnboardingService/GetFleetInitStatus
Content-Type: application/json

{}

### Authenticate
# @name authenticate
POST {{host}}/auth.v1.AuthService/Authenticate
Content-Type: application/json

{
  "username": "protofleet",
  "password": "protofleet"
}

###
@session_cookie = {{authenticate.response.headers.Set-Cookie}}

### Get fleet onboarding status
POST {{host}}/onboarding.v1.OnboardingService/GetFleetOnboardingStatus
Content-Type: application/json
Cookie: {{session_cookie}}

{}
