@host = http://localhost:4000

### Authenticate
# @name authenticate
POST {{host}}/auth.v1.AuthService/Authenticate
Content-Type: application/json

{
  "username": "protofleet",
  "password": "protofleet"
}

###
@session_cookie = {{authenticate.response.headers.Set-Cookie}}

### Discover via mDNS
POST {{host}}/pairing.v1.PairingService/Discover
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "mdns": {
    "service_type": "_http._tcp",
    "domain": "fleet_fleet-network.",
    "timeout_seconds": 15
  }
}

### Discover via nmap
POST {{host}}/pairing.v1.PairingService/Discover
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "nmap": {
    "target": "192.168.2.0/24",
    "ports": ["2121"],
    "fast_scan": false
  }
}

### Discover via IP range
POST {{host}}/pairing.v1.PairingService/Discover
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "ip_range": {
    "start_ip": "10.0.0.248",
    "end_ip": "10.0.0.250",
    "ports": ["2121"]
  }
}

### Discover via IP list
POST {{host}}/pairing.v1.PairingService/Discover
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "ip_list": {
    "ip_addresses": [
      "mms-1",
      "mms-2",
      "miner-1.miner.fleetdev.proto.xyz",
      "miner-2.miner.fleetdev.proto.xyz",
      "miner-3.miner.fleetdev.proto.xyz"
    ],
    "ports": ["2121"]
  }
}

### Pair devices
POST {{host}}/pairing.v1.PairingService/Pair
Content-Type: application/json
Cookie: {{session_cookie}}

{
  "device_identifiers": [
    "TODO_REPLACE_WITH_DEVICE_ID_1",
    "TODO_REPLACE_WITH_DEVICE_ID_2"
  ]
}
