name: Generated code check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generated-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        id: create_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          token: "${{ steps.create_token.outputs.token }}"
          submodules: true

      - name: Activate hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318    # v1.1.4

      - name: Install dependencies
        run: just init

      - name: Generate code
        run: just gen

      - name: Check if committed generated code is up-to-date
        run: >
          git diff --quiet || {
            echo -e "\033[0;31mNewly generated code does not match the committed code. Run 'just gen', then commit and push the changes.\033[0m" 1>&2;
            echo -e "\n\n";
            git diff --exit-code
          }
