# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: ProtoFleet Deploy PR Frontend

on:
  pull_request:
    paths:
      - ".github/workflows/protofleet-deploy-pr-frontend.yml"
      - "miner-web/**"
      - "fleet/deploy/develop/frontend/**"

permissions:
  # Needed for aws-actions/configure-aws-credentials
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-dashboard:
    uses: "./.github/workflows/protofleet-deploy-docker-to-develop-vm.yml"
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/frontend-dashboard-develop:pr-${{ github.event.number }}-main"
      source-build-directory: "fleet/deploy/develop/frontend/dashboard"
      target-directory: "docker/protofleet/pr/${{ github.event.number }}/frontend/dashboard-main"
      docker-compose-parameters: '{ "BACKEND_ADDRESS": "https://backend.main.develop.fleetdev.proto.xyz" }'

  report-dashboard-url:
    uses: "./.github/workflows/protofleet-report-pr-deployment.yml"
    needs: deploy-dashboard
    with:
      component-name: Dashboard (connected to main branch develop backend)
      deployment-domain: "dashboard.pr-${{ github.event.number }}-main.develop.fleetdev.proto.xyz"
      pr-number: ${{ github.event.number }}

  deploy-storybook:
    uses: "./.github/workflows/protofleet-deploy-docker-to-develop-vm.yml"
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/frontend-storybook-develop:pr-${{ github.event.number }}"
      source-build-directory: "fleet/deploy/develop/frontend/storybook"
      target-directory: "docker/protofleet/pr/${{ github.event.number }}/frontend/storybook"

  report-storybook-url:
    uses: "./.github/workflows/protofleet-report-pr-deployment.yml"
    needs: deploy-storybook
    with:
      component-name: Storybook
      deployment-domain: "storybook.pr-${{ github.event.number }}.develop.fleetdev.proto.xyz"
      pr-number: ${{ github.event.number }}
