# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: ProtoFleet Deploy PR Backend

on:
  pull_request:
    paths:
      - ".github/workflows/protofleet-deploy-pr-backend.yml"
      - "server/**"
      - "!deploy/**"
      - "deploy/develop/backend/**"

permissions:
  # Needed for aws-actions/configure-aws-credentials
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-backend:
    uses: "./.github/workflows/protofleet-deploy-docker-to-develop-vm.yml"
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/backend-develop:pr-${{ github.event.number }}"
      source-build-directory: "deploy/develop/backend"
      target-directory: "docker/protofleet/pr/${{ github.event.number }}/backend"

  report-backend-url:
    uses: "./.github/workflows/protofleet-report-pr-deployment.yml"
    needs: deploy-backend
    with:
      component-name: Backend
      deployment-domain: "backend.pr-${{ github.event.number }}.develop.fleetdev.proto.xyz"
      pr-number: ${{ github.event.number }}

  deploy-dashboard:
    uses: "./.github/workflows/protofleet-deploy-docker-to-develop-vm.yml"
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/frontend-dashboard-develop:pr-${{ github.event.number }}-pr"
      source-build-directory: "deploy/develop/frontend/dashboard"
      target-directory: "docker/protofleet/pr/${{ github.event.number }}/frontend/dashboard-pr"
      docker-compose-parameters: '{ "BACKEND_ADDRESS": "https://backend.pr-${{ github.event.number }}.develop.fleetdev.proto.xyz" }'

  report-dashboard-url:
    uses: "./.github/workflows/protofleet-report-pr-deployment.yml"
    needs: deploy-dashboard
    with:
      component-name: Dashboard (connected to this PR's backend)
      deployment-domain: "dashboard.pr-${{ github.event.number }}-pr.develop.fleetdev.proto.xyz"
      pr-number: ${{ github.event.number }}
