name: ProtoFleet Backend tests

on:
  pull_request:
    paths:
      - ".github/workflows/protofleet-backend-tests.yml"
      - "server/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/protofleet-backend-tests.yml"
      - "server/**"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Activate hermit
        uses: cashapp/activate-hermit@v1.1.4

      - name: Configure cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Compile project
        run: just build-all

      - name: Start database
        run: just db-up

      - name: Run tests
        run: just test

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Activate hermit
        uses: cashapp/activate-hermit@v1.1.4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: server
