# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: ProtoFleet Deploy Docker to Develop VM

on:
  workflow_call:
    inputs:
      docker-image-tag:
        required: true
        type: string
        description: The tag for the Docker image to be deployed.
      docker-build-working-directory:
        required: true
        type: string
        description: The working directory where the Docker build will be executed.
      source-build-directory:
        required: true
        type: string
        description: The path to the deploy directory with Dockerfile and Docker Compose file used for building the Docker image.
      target-directory:
        required: true
        type: string
        description: The directory on the target server where the `docker-compose.yml` file will be deployed.
      docker-compose-parameters:
        required: false
        type: string
        default: "{}"
        description: 'Additional parameters passed to the Docker Compose file. Use JSON format: `{ "ARG1"="X", "ARG2"="Y"}` which results in replacements of `${ARG1} and ${ARG2}` in the Docker Compose file.'

permissions:
  # Needed for aws-actions/configure-aws-credentials
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Docker to Develop VM
        uses: ./.github/actions/deploy-docker-to-develop-vm
        with:
          docker-image-tag: ${{ inputs.docker-image-tag }}
          docker-build-working-directory: ${{ inputs.docker-build-working-directory }}
          source-build-directory: ${{ inputs.source-build-directory }}
          target-directory: ${{ inputs.target-directory }}
          docker-compose-parameters: ${{ inputs.docker-compose-parameters }}
