name: ProtoFleet Publish Production Frontend Image
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/protofleet-publish-production-frontend-image.yml"
      - "client/**"
      - "!publish/**"
      - "publish/docker-image/frontend"
  workflow_dispatch:

jobs:
  publish:
    uses: "./.github/workflows/protofleet-publish-production-image.yml"
    concurrency:
      group: "${{ github.workflow }}"
      cancel-in-progress: true
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/frontend-production:main"
      source-build-directory: "publish/docker-image/frontend"