# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: ProtoFleet Deploy PR Proto OS

on:
  pull_request:
    paths:
      - ".github/workflows/protofleet-deploy-pr-frontend.yml"
      - "client/**"
      - "deploy/develop/frontend/**"
      - "miner-firmware"
      - "miner-firmware/**"

permissions:
  # Needed for aws-actions/configure-aws-credentials
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-proto-os:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App token
        id: create_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: "${{ steps.create_token.outputs.token }}"
          submodules: recursive
      - name: Activate hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318    # v1.1.4

      - name: Build base simulator Docker image
        shell: bash
        run: |
          cd client
          npm clean-install
          npm run build:protoOS
          cd ..
          mkdir -p miner-firmware/docker/sim/protoOS/dist/protoOS
          cp -r client/dist/protoOS/* miner-firmware/docker/sim/protoOS/dist/protoOS
          docker build --build-arg "TYPE=b3b-sim" -f "miner-firmware/docker/sim/Dockerfile" -t "protofleet/miner-sim-develop-base:latest" miner-firmware

      - name: Deploy Docker to Develop VM
        uses: ./.github/actions/deploy-docker-to-develop-vm
        with:
          docker-build-working-directory: "."
          docker-image-tag: "protofleet/frontend-proto-os-develop:pr-${{ github.event.number }}"
          source-build-directory: "deploy/develop/frontend/proto-os"
          target-directory: "docker/protofleet/pr/${{ github.event.number }}/frontend/proto-os"

  report-proto-os:
    uses: "./.github/workflows/protofleet-report-pr-deployment.yml"
    needs: deploy-proto-os
    with:
      component-name: Proto OS with miner simulator
      deployment-domain: "proto-os.pr-${{ github.event.number }}.develop.fleetdev.proto.xyz"
      pr-number: ${{ github.event.number }}
