# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: ProtoFleet Deploy Develop Traefik

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/protofleet-deploy-develop-traefik.yml"
      - "deploy/develop/traefik/**"
  workflow_dispatch:

permissions:
  # Needed for aws-actions/configure-aws-credentials
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - instance-subdomain: develop
            instance-id: i-0e47edcb1574765b0
          - instance-subdomain: miner-1.miner
            instance-id: i-01211e1ce58bbae8b
          - instance-subdomain: miner-2.miner
            instance-id: i-089d02537ba8dc14b
          - instance-subdomain: miner-3.miner
            instance-id: i-0c75c04f06ec1d3c4
    concurrency:
      group: "${{ github.workflow }}-deploy-${{ matrix.instance-subdomain }}"
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup AWS SSH
        uses: ./.github/actions/aws-ssh-setup
        with:
          aws-instance-id: "${{ matrix.instance-id }}"
          aws-instance-connect-endpoint-id: "eice-0e5cdfd8da57023b2"
          aws-instance-user: "ubuntu"
          aws-region: "us-east-1"
          aws-role-to-assume: "arn:aws:iam::941377115117:role/GithubActions_ProtoFleet_Deploy_Develop"

      - name: Write VM subdomain to Docker Compose file
        shell: bash
        run: sed -i 's#${VM_SUBDOMAIN}#${{ matrix.instance-subdomain }}#g' "deploy/develop/traefik/docker-compose.yml"

      - name: Deploy Traefik
        uses: ./.github/actions/docker-compose-deploy
        with:
          source-directory: "deploy/develop/traefik"
          target-directory: "docker/protofleet/develop/traefik"
