name: ProtoFleet Deploy Miner Simulator

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/protofleet-deploy-develop-frontend.yml"
      - "client/**"
      - "deploy/develop/frontend/**"
      - "miner-firmware"
      - "miner-firmware/**"
  workflow_dispatch:

permissions:
  # Needed for aws-actions/configure-aws-credentials
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      docker-image-remote-tag: ${{ steps.push-docker-image.outputs.docker-image-remote-tag }}
    concurrency:
      group: "${{ github.workflow }}-build-image"
      cancel-in-progress: true
    steps:
      - name: Create GitHub App token
        id: create_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          token: "${{ steps.create_token.outputs.token }}"
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
        with:
          aws-region: "us-east-1"
          role-to-assume: "arn:aws:iam::941377115117:role/GithubActions_ProtoFleet_Deploy_Develop"

      - name: Activate hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318    # v1.1.4

      - name: Build simulator with ProtoOS dashboard Docker image
        shell: bash
        run: |
          cd client
          npm clean-install
          npm run build:protoOS
          cd ..
          mkdir -p miner-firmware/docker/sim/protoOS/dist/protoOS
          cp -r client/dist/protoOS/* miner-firmware/docker/sim/protoOS/dist/protoOS
          docker build --build-arg "TYPE=b3b-sim" -f "miner-firmware/docker/sim/Dockerfile" -t "protofleet/miner-sim-develop:latest" miner-firmware

      - name: Push Docker image
        id: push-docker-image
        uses: ./.github/actions/docker-image-push
        with:
          docker-image-tag: "protofleet/miner-sim-develop:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    strategy:
      matrix:
        include:
          - miner-name: miner-1
            instance-id: i-01211e1ce58bbae8b
          - miner-name: miner-2
            instance-id: i-089d02537ba8dc14b
          - miner-name: miner-3
            instance-id: i-0c75c04f06ec1d3c4
    concurrency:
      group: "${{ github.workflow }}-deploy-${{ matrix.miner-name }}"
      cancel-in-progress: true
    steps:
      - name: Create GitHub App token
        id: create_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          token: "${{ steps.create_token.outputs.token }}"
          submodules: true

      - name: Setup AWS SSH
        uses: ./.github/actions/aws-ssh-setup
        with:
          aws-instance-id: "${{ matrix.instance-id }}"
          aws-instance-connect-endpoint-id: "eice-0e5cdfd8da57023b2"
          aws-instance-user: "ubuntu"
          aws-region: "us-east-1"
          aws-role-to-assume: "arn:aws:iam::941377115117:role/GithubActions_ProtoFleet_Deploy_Develop"

      - name: Write Docker image tag to Docker Compose file
        shell: bash
        run: sed -i 's#${IMAGE}#${{ needs.build-image.outputs.docker-image-remote-tag }}#g' "deploy/develop/miner/docker-compose.yml"

      - name: Write Miner name to Docker Compose file
        shell: bash
        run: sed -i 's#${MINER_NAME}#${{ matrix.miner-name }}#g' "deploy/develop/miner/docker-compose.yml"

      - name: Write Miner serial number to Docker Compose file
        shell: bash
        run: sed -i 's#${MFG_SERIAL_NUMBER}#develop-${{ matrix.miner-name }}#g' "deploy/develop/miner/docker-compose.yml"

      - name: Copy over initial Miner API config
        shell: bash
        run: ~/rsync_to_ec2 "miner-firmware/crates/miner-api-server/config" "docker/protofleet/develop/${{ matrix.miner-name }}/initial-config/miner-api"

      - name: Copy over initial MCDD config
        shell: bash
        run: ~/rsync_to_ec2 "miner-firmware/crates/mcdd/config" "docker/protofleet/develop/${{ matrix.miner-name }}/initial-config/mcdd"

      - name: Initialize config if it does not exist
        shell: bash
        run: |
          ~/ssh_to_ec2 '
            cd "docker/protofleet/develop/${{ matrix.miner-name }}";
            if [ ! -d volumes ]; then
              mkdir -p volumes/miner-api/config;
              cp -r initial-config/miner-api/config/* volumes/miner-api/config;
              mkdir -p volumes/mcdd/config;
              cp -r initial-config/mcdd/config/* volumes/mcdd/config;
            fi'

      - name: Pull Docker image
        uses: ./.github/actions/docker-image-pull
        with:
          docker-image-remote-tag: ${{ needs.build-image.outputs.docker-image-remote-tag }}

      - name: Deploy
        uses: ./.github/actions/docker-compose-deploy
        with:
          source-directory: "deploy/develop/miner"
          target-directory: "docker/protofleet/develop/${{ matrix.miner-name }}"
