name: ProtoFleet antminer plugin tests

on:
  pull_request:
    paths:
      # - ".github/workflows/protofleet-antminer-plugin-tests.yml"
      - "plugin/antminer/**"
      - "just/go-plugin.just"
  push:
    branches:
      - main
    paths:
      # - ".github/workflows/protofleet-antminer-plugin-tests.yml"
      - "plugin/antminer/**"
      - "just/go-plugin.just"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Activate hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # v1.1.4

      - name: Lint protocol buffers
        run: buf lint

      - name: Lint protocol golang
        run: |
          cd plugin/antminer
          just lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin/antminer
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Activate hermit
        uses: cashapp/activate-hermit@12a728b03ad41eace0f9abaf98a035e7e8ea2318 # v1.1.4

      - name: Configure Go cache
        uses: ./.github/actions/go-cache-setup

      - name: Compile project
        run: just build

      - name: Run tests
        run: just test
