# This VM with Docker Compose deployment is meant to be used only for development and testing of the ProtoFleet on-premise version.

name: ProtoFleet Deploy Develop Frontend

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/protofleet-deploy-develop-frontend.yml"
      - "miner-web/**"
      - "fleet/deploy/develop/frontend/**"
  workflow_dispatch:

jobs:
  deploy-dashboard:
    uses: "./.github/workflows/protofleet-deploy-docker-to-develop-vm.yml"
    concurrency:
      group: "${{ github.workflow }}-dashboard"
      cancel-in-progress: true
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/frontend-dashboard-develop:main"
      source-build-directory: "fleet/deploy/develop/frontend/dashboard"
      target-directory: "docker/protofleet/develop/frontend/dashboard"
      docker-compose-parameters: '{ "BACKEND_ADDRESS": "https://backend.main.develop.fleetdev.proto.xyz" }'

  deploy-storybook:
    uses: "./.github/workflows/protofleet-deploy-docker-to-develop-vm.yml"
    concurrency:
      group: "${{ github.workflow }}-storybook"
      cancel-in-progress: true
    with:
      docker-build-working-directory: "."
      docker-image-tag: "protofleet/frontend-storybook-develop:main"
      source-build-directory: "fleet/deploy/develop/frontend/storybook"
      target-directory: "docker/protofleet/develop/frontend/storybook"
