name: ProtoFleet Report PR Deployment

on:
  workflow_call:
    inputs:
      component-name:
        required: true
        type: string
        description: "The name of the component being deployed."
      deployment-domain:
        required: true
        type: string
        description: "The domain where the component is deployed. Used for deriving the URL."
      pr-number:
        required: true
        type: number
        description: "The number of the pull request that triggered this workflow."

permissions:
  contents: read
  pull-requests: write

jobs:
  report-deployment-url:
    runs-on: ubuntu-latest
    steps:
      - name: Report deployment URL
        uses: actions/github-script@v7
        with:
          script: |
            const body = "The **${{ inputs.component-name }}** was deployed to: https://${{ inputs.deployment-domain }}"
            
            const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ inputs.pr-number }}
            })

            const alreadyReported = comments.data.find(comment => comment.body == body)
            
            if (!alreadyReported) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ inputs.pr-number }},
                body: body,
              })
            }
