name: Pull Request

on: pull_request_target

permissions:
  contents: read
  repository-projects: read
  pull-requests: write

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-latest

    steps:
      - name: Apply labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9  # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-assign:
    name: Auto-Assign
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Assign PR to Creator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.actor }}
