// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_rpc_client.go -package=mocks RPCClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	networking "github.com/block/proto-fleet/plugin/antminer/pkg/antminer/networking"
	rpc "github.com/block/proto-fleet/plugin/antminer/pkg/antminer/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockRPCClient is a mock of RPCClient interface.
type MockRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockRPCClientMockRecorder
	isgomock struct{}
}

// MockRPCClientMockRecorder is the mock recorder for MockRPCClient.
type MockRPCClientMockRecorder struct {
	mock *MockRPCClient
}

// NewMockRPCClient creates a new mock instance.
func NewMockRPCClient(ctrl *gomock.Controller) *MockRPCClient {
	mock := &MockRPCClient{ctrl: ctrl}
	mock.recorder = &MockRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCClient) EXPECT() *MockRPCClientMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockRPCClient) GetConfig(ctx context.Context, connInfo *networking.ConnectionInfo) (*rpc.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, connInfo)
	ret0, _ := ret[0].(*rpc.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockRPCClientMockRecorder) GetConfig(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockRPCClient)(nil).GetConfig), ctx, connInfo)
}

// GetDevs mocks base method.
func (m *MockRPCClient) GetDevs(ctx context.Context, connInfo *networking.ConnectionInfo) (*rpc.DevsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevs", ctx, connInfo)
	ret0, _ := ret[0].(*rpc.DevsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevs indicates an expected call of GetDevs.
func (mr *MockRPCClientMockRecorder) GetDevs(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevs", reflect.TypeOf((*MockRPCClient)(nil).GetDevs), ctx, connInfo)
}

// GetPools mocks base method.
func (m *MockRPCClient) GetPools(ctx context.Context, connInfo *networking.ConnectionInfo) (*rpc.PoolsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPools", ctx, connInfo)
	ret0, _ := ret[0].(*rpc.PoolsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPools indicates an expected call of GetPools.
func (mr *MockRPCClientMockRecorder) GetPools(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPools", reflect.TypeOf((*MockRPCClient)(nil).GetPools), ctx, connInfo)
}

// GetStats mocks base method.
func (m *MockRPCClient) GetStats(ctx context.Context, connInfo *networking.ConnectionInfo) (*rpc.StatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, connInfo)
	ret0, _ := ret[0].(*rpc.StatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRPCClientMockRecorder) GetStats(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRPCClient)(nil).GetStats), ctx, connInfo)
}

// GetSummary mocks base method.
func (m *MockRPCClient) GetSummary(ctx context.Context, connInfo *networking.ConnectionInfo) (*rpc.SummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, connInfo)
	ret0, _ := ret[0].(*rpc.SummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockRPCClientMockRecorder) GetSummary(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockRPCClient)(nil).GetSummary), ctx, connInfo)
}

// GetVersion mocks base method.
func (m *MockRPCClient) GetVersion(ctx context.Context, connInfo *networking.ConnectionInfo) (*rpc.VersionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, connInfo)
	ret0, _ := ret[0].(*rpc.VersionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockRPCClientMockRecorder) GetVersion(ctx, connInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockRPCClient)(nil).GetVersion), ctx, connInfo)
}
