// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	serverlogv1 "github.com/block/proto-fleet/server/generated/grpc/serverlog/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedServerlogsCommand() *cli.Command {
	return &cli.Command{
		Name:  "serverlogs",
		Usage: "Manage serverlogs commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"list",
				"List recent server logs",
				"/serverlog.v1.ServerLogService/ListServerLogs",
				generatedAuthSessionOnly,
				[]cli.Flag{
					&cli.StringFlag{Name: "min-level", Usage: "min level. Valid options: debug, info, warn, error"},
					&cli.StringFlag{Name: "search-text", Usage: "search text"},
					&cli.Uint64Flag{Name: "since-id", Usage: "since id"},
					&cli.IntFlag{Name: "limit", Usage: "limit"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &serverlogv1.ListServerLogsRequest{}
					if cmd.IsSet("min-level") {
						switch normalizeEnum(cmd.String("min-level")) {
						case "debug":
							req.MinLevel = serverlogv1.LogLevel_LOG_LEVEL_DEBUG
						case "info":
							req.MinLevel = serverlogv1.LogLevel_LOG_LEVEL_INFO
						case "warn":
							req.MinLevel = serverlogv1.LogLevel_LOG_LEVEL_WARN
						case "error":
							req.MinLevel = serverlogv1.LogLevel_LOG_LEVEL_ERROR
						default:
							return nil, fmt.Errorf("invalid value for min-level: %s. Valid options: debug, info, warn, error", cmd.String("min-level"))
						}
					}
					if cmd.IsSet("search-text") {
						req.SearchText = cmd.String("search-text")
					}
					if cmd.IsSet("since-id") {
						req.SinceId = cmd.Uint64("since-id")
					}
					if cmd.IsSet("limit") {
						req.Limit = int32(cmd.Int("limit"))
					}
					return req, nil
				},
				func() proto.Message { return &serverlogv1.ListServerLogsResponse{} },
			),
		},
	}
}
