// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	onboardingv1 "github.com/block/proto-fleet/server/generated/grpc/onboarding/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedOnboardingCommand() *cli.Command {
	return &cli.Command{
		Name:  "onboarding",
		Usage: "Manage onboarding commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"create-admin",
				"Create the initial Fleet admin login",
				"/onboarding.v1.OnboardingService/CreateAdminLogin",
				generatedAuthUnauthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "username", Usage: "username"},
					&cli.BoolFlag{Name: "password-stdin", Usage: "Read password from stdin"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &onboardingv1.CreateAdminLoginRequest{}
					if cmd.IsSet("username") {
						req.Username = cmd.String("username")
					}
					secretPassword, err := generatedReadSecret(cmd, "password-stdin", "password")
					if err != nil {
						return nil, err
					}
					req.Password = secretPassword
					return req, nil
				},
				func() proto.Message { return &onboardingv1.CreateAdminLoginResponse{} },
			),
		},
	}
}
