// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"

	authzv1 "github.com/block/proto-fleet/server/generated/grpc/authz/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedRolesCommand() *cli.Command {
	return &cli.Command{
		Name:  "roles",
		Usage: "Manage roles commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"create",
				"Create custom role",
				"/authz.v1.AuthzService/CreateCustomRole",
				generatedAuthSessionOnly,
				[]cli.Flag{
					&cli.StringFlag{Name: "name", Usage: "(required) name", Required: true},
					&cli.StringFlag{Name: "description", Usage: "description"},
					&cli.StringSliceFlag{Name: "permission-keys", Usage: "permission keys"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &authzv1.CreateCustomRoleRequest{}
					if cmd.IsSet("name") {
						req.Name = cmd.String("name")
					}
					if cmd.IsSet("description") {
						req.Description = cmd.String("description")
					}
					if cmd.IsSet("permission-keys") {
						req.PermissionKeys = cmd.StringSlice("permission-keys")
					}
					return req, nil
				},
				func() proto.Message { return &authzv1.CreateCustomRoleResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete custom role",
				"/authz.v1.AuthzService/DeleteCustomRole",
				generatedAuthSessionOnly,
				[]cli.Flag{
					&cli.StringFlag{Name: "role-id", Usage: "(required) role id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &authzv1.DeleteCustomRoleRequest{}
					if cmd.IsSet("role-id") {
						req.RoleId = cmd.String("role-id")
					}
					return req, nil
				},
				func() proto.Message { return &authzv1.DeleteCustomRoleResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List roles",
				"/authz.v1.AuthzService/ListRoles",
				generatedAuthSessionOnly,
				[]cli.Flag{},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &authzv1.ListRolesRequest{}
					return req, nil
				},
				func() proto.Message { return &authzv1.ListRolesResponse{} },
			),
			generatedRequestCommand(
				"permissions",
				"List permissions",
				"/authz.v1.AuthzService/ListPermissions",
				generatedAuthSessionOnly,
				[]cli.Flag{},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &authzv1.ListPermissionsRequest{}
					return req, nil
				},
				func() proto.Message { return &authzv1.ListPermissionsResponse{} },
			),
			generatedRequestCommand(
				"update",
				"Update custom role",
				"/authz.v1.AuthzService/UpdateCustomRole",
				generatedAuthSessionOnly,
				[]cli.Flag{
					&cli.StringFlag{Name: "role-id", Usage: "(required) role id", Required: true},
					&cli.StringFlag{Name: "name", Usage: "(required) name", Required: true},
					&cli.StringFlag{Name: "description", Usage: "description"},
					&cli.StringSliceFlag{Name: "permission-keys", Usage: "permission keys"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &authzv1.UpdateCustomRoleRequest{}
					if cmd.IsSet("role-id") {
						req.RoleId = cmd.String("role-id")
					}
					if cmd.IsSet("name") {
						req.Name = cmd.String("name")
					}
					if cmd.IsSet("description") {
						req.Description = cmd.String("description")
					}
					if cmd.IsSet("permission-keys") {
						req.PermissionKeys = cmd.StringSlice("permission-keys")
					}
					return req, nil
				},
				func() proto.Message { return &authzv1.UpdateCustomRoleResponse{} },
			),
		},
	}
}
