// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	devicesetv1 "github.com/block/proto-fleet/server/generated/grpc/device_set/v1"
	cli "github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedRacksCommand() *cli.Command {
	return &cli.Command{
		Name:  "racks",
		Usage: "Manage racks commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to a rack",
				"/device_set.v1.DeviceSetService/AssignDevicesToRack",
				generatedAuthAuthenticated,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "target-rack-id", Usage: "target rack id", Required: true},
					&cli.BoolFlag{Name: "force-clear-conflicting-site", Usage: "force clear conflicting site"},
				}, generatedCommonDeviceListSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.AssignDevicesToRackRequest{}
					selector, err := generatedBuildCommonDeviceListSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("target-rack-id") {
						value := cmd.Int64("target-rack-id")
						req.TargetRackId = &value
					}
					if cmd.IsSet("force-clear-conflicting-site") {
						value := cmd.Bool("force-clear-conflicting-site")
						req.ForceClearConflictingSite = &value
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.AssignDevicesToRackResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete a rack",
				"/device_set.v1.DeviceSetService/DeleteDeviceSet",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.DeleteDeviceSetRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.DeleteDeviceSetResponse{} },
			),
			generatedRequestCommand(
				"device",
				"List racks for a device identifier",
				"/device_set.v1.DeviceSetService/GetDeviceDeviceSets",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "device-identifier", Usage: "device identifier"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetDeviceDeviceSetsRequest{}
					req.Type = devicesetv1.DeviceSetType_DEVICE_SET_TYPE_RACK
					if cmd.IsSet("device-identifier") {
						req.DeviceIdentifier = cmd.String("device-identifier")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetDeviceDeviceSetsResponse{} },
			),
			generatedRequestCommand(
				"get",
				"Get a rack by id",
				"/device_set.v1.DeviceSetService/GetDeviceSet",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetDeviceSetRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					if err := generatedRequireDeviceSetType(ctx, client, req.DeviceSetId, devicesetv1.DeviceSetType_DEVICE_SET_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetDeviceSetResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List racks",
				"/device_set.v1.DeviceSetService/ListDeviceSets",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringSliceFlag{Name: "zones", Usage: "zones"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.ListDeviceSetsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					req.Type = devicesetv1.DeviceSetType_DEVICE_SET_TYPE_RACK
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("zones") {
						req.Zones = cmd.StringSlice("zones")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.ListDeviceSetsResponse{} },
			),
			generatedRequestCommand(
				"members",
				"List rack members",
				"/device_set.v1.DeviceSetService/ListDeviceSetMembers",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.ListDeviceSetMembersRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if err := generatedRequireDeviceSetType(ctx, client, req.DeviceSetId, devicesetv1.DeviceSetType_DEVICE_SET_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.ListDeviceSetMembersResponse{} },
			),
			generatedRequestCommand(
				"save",
				"Create or update a rack",
				"/device_set.v1.DeviceSetService/SaveRack",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.SaveRackRequest{}
					if err := readProtoJSON(cmd.String("json"), req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.SaveRackResponse{} },
			),
			generatedRequestCommand(
				"slots",
				"List occupied rack slots",
				"/device_set.v1.DeviceSetService/GetRackSlots",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetRackSlotsRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetRackSlotsResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get aggregated stats for one or more racks",
				"/device_set.v1.DeviceSetService/GetDeviceSetStats",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "device-set-ids", Usage: "device set ids"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetDeviceSetStatsRequest{}
					if cmd.IsSet("device-set-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("device-set-ids"))
						if err != nil {
							return nil, err
						}
						req.DeviceSetIds = values
					}
					if err := generatedRequireDeviceSetTypes(ctx, client, req.DeviceSetIds, devicesetv1.DeviceSetType_DEVICE_SET_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetDeviceSetStatsResponse{} },
			),
			generatedRequestCommand(
				"types",
				"List all rack layouts",
				"/device_set.v1.DeviceSetService/ListRackTypes",
				generatedAuthAuthenticated,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.ListRackTypesRequest{}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.ListRackTypesResponse{} },
			),
			generatedRequestCommand(
				"zones",
				"List all rack zones",
				"/device_set.v1.DeviceSetService/ListRackZones",
				generatedAuthAuthenticated,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.ListRackZonesRequest{}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.ListRackZonesResponse{} },
			),
		},
	}
}
