// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	"fmt"

	errorsv1 "github.com/block/proto-fleet/server/generated/grpc/errors/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedErrorsCommand() *cli.Command {
	return &cli.Command{
		Name:  "errors",
		Usage: "Manage errors commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"get",
				"Get a miner error by id",
				"/errors.v1.ErrorQueryService/GetError",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "error-id", Usage: "(required) error id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &errorsv1.GetErrorRequest{}
					if cmd.IsSet("error-id") {
						req.ErrorId = cmd.String("error-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &errorsv1.GetErrorResponse{} },
			),
			generatedRequestCommand(
				"list-miner",
				"List canonical miner errors",
				"/errors.v1.ErrorQueryService/ListMinerErrors",
				generatedAuthAuthenticated,
				[]cli.Flag{},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &errorsv1.ListMinerErrorsRequest{}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &errorsv1.ListMinerErrorsResponse{} },
			),
			generatedRequestCommand(
				"query",
				"Query miner errors",
				"/errors.v1.ErrorQueryService/Query",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "result-view", Usage: "result view. Valid options: error, component, device"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringFlag{Name: "order-by", Usage: "order by"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &errorsv1.QueryRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if req.PageSize == 0 {
						req.PageSize = int32(100)
					}
					if cmd.IsSet("result-view") {
						switch normalizeEnum(cmd.String("result-view")) {
						case "error":
							req.ResultView = errorsv1.ResultView_RESULT_VIEW_ERROR
						case "component":
							req.ResultView = errorsv1.ResultView_RESULT_VIEW_COMPONENT
						case "device":
							req.ResultView = errorsv1.ResultView_RESULT_VIEW_DEVICE
						default:
							return nil, fmt.Errorf("invalid value for result-view: %s. Valid options: error, component, device", cmd.String("result-view"))
						}
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("order-by") {
						req.OrderBy = cmd.String("order-by")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &errorsv1.QueryResponse{} },
			),
		},
	}
}
