// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	devicesetv1 "github.com/block/proto-fleet/server/generated/grpc/device_set/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedGroupsCommand() *cli.Command {
	return &cli.Command{
		Name:  "groups",
		Usage: "Manage groups commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to a group",
				"/device_set.v1.DeviceSetService/AddDevicesToGroup",
				generatedAuthAuthenticated,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "target-group-id", Usage: "target group id"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.AddDevicesToGroupRequest{}
					selector, err := generatedBuildCommonSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("target-group-id") {
						req.TargetGroupId = cmd.Int64("target-group-id")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.AddDevicesToGroupResponse{} },
			),
			generatedRequestCommand(
				"create",
				"Create a group",
				"/device_set.v1.DeviceSetService/CreateDeviceSet",
				generatedAuthAuthenticated,
				append([]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.StringFlag{Name: "label", Usage: "label"},
					&cli.StringFlag{Name: "description", Usage: "description"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.CreateDeviceSetRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if generatedCommonSelectorProvided(cmd) {
						selector, err := generatedBuildCommonSelector(cmd)
						if err != nil {
							return nil, err
						}
						req.DeviceSelector = selector
					}
					req.Type = devicesetv1.DeviceSetType_DEVICE_SET_TYPE_GROUP
					if cmd.IsSet("label") {
						req.Label = cmd.String("label")
					}
					if cmd.IsSet("description") {
						req.Description = cmd.String("description")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.CreateDeviceSetResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete a group",
				"/device_set.v1.DeviceSetService/DeleteDeviceSet",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.DeleteDeviceSetRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.DeleteDeviceSetResponse{} },
			),
			generatedRequestCommand(
				"device",
				"List groups for a device identifier",
				"/device_set.v1.DeviceSetService/GetDeviceDeviceSets",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "device-identifier", Usage: "device identifier"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetDeviceDeviceSetsRequest{}
					req.Type = devicesetv1.DeviceSetType_DEVICE_SET_TYPE_GROUP
					if cmd.IsSet("device-identifier") {
						req.DeviceIdentifier = cmd.String("device-identifier")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetDeviceDeviceSetsResponse{} },
			),
			generatedRequestCommand(
				"get",
				"Get a group by id",
				"/device_set.v1.DeviceSetService/GetDeviceSet",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetDeviceSetRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					if err := generatedRequireDeviceSetType(ctx, client, req.DeviceSetId, devicesetv1.DeviceSetType_DEVICE_SET_TYPE_GROUP); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetDeviceSetResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List groups",
				"/device_set.v1.DeviceSetService/ListDeviceSets",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.ListDeviceSetsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					req.Type = devicesetv1.DeviceSetType_DEVICE_SET_TYPE_GROUP
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.ListDeviceSetsResponse{} },
			),
			generatedRequestCommand(
				"members",
				"List group members",
				"/device_set.v1.DeviceSetService/ListDeviceSetMembers",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.ListDeviceSetMembersRequest{}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if err := generatedRequireDeviceSetType(ctx, client, req.DeviceSetId, devicesetv1.DeviceSetType_DEVICE_SET_TYPE_GROUP); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.ListDeviceSetMembersResponse{} },
			),
			generatedRequestCommand(
				"remove-devices",
				"Remove devices from a group",
				"/device_set.v1.DeviceSetService/RemoveDevicesFromGroup",
				generatedAuthAuthenticated,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "target-group-id", Usage: "target group id"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.RemoveDevicesFromGroupRequest{}
					selector, err := generatedBuildCommonSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("target-group-id") {
						req.TargetGroupId = cmd.Int64("target-group-id")
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.RemoveDevicesFromGroupResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get aggregated stats for one or more groups",
				"/device_set.v1.DeviceSetService/GetDeviceSetStats",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "device-set-ids", Usage: "device set ids"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.GetDeviceSetStatsRequest{}
					if cmd.IsSet("device-set-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("device-set-ids"))
						if err != nil {
							return nil, err
						}
						req.DeviceSetIds = values
					}
					if err := generatedRequireDeviceSetTypes(ctx, client, req.DeviceSetIds, devicesetv1.DeviceSetType_DEVICE_SET_TYPE_GROUP); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.GetDeviceSetStatsResponse{} },
			),
			generatedRequestCommand(
				"update",
				"Update a group",
				"/device_set.v1.DeviceSetService/UpdateDeviceSet",
				generatedAuthAuthenticated,
				append([]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.Int64Flag{Name: "device-set-id", Usage: "device set id"},
					&cli.StringFlag{Name: "label", Usage: "label"},
					&cli.StringFlag{Name: "description", Usage: "description"},
				}, generatedCommonSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.UpdateDeviceSetRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if generatedCommonSelectorProvided(cmd) {
						selector, err := generatedBuildCommonSelector(cmd)
						if err != nil {
							return nil, err
						}
						req.DeviceSelector = selector
					}
					if cmd.IsSet("device-set-id") {
						req.DeviceSetId = cmd.Int64("device-set-id")
					}
					if cmd.IsSet("label") {
						value := cmd.String("label")
						req.Label = &value
					}
					if cmd.IsSet("description") {
						value := cmd.String("description")
						req.Description = &value
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.UpdateDeviceSetResponse{} },
			),
		},
	}
}
