// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	buildingsv1 "github.com/block/proto-fleet/server/generated/grpc/buildings/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedBuildingsCommand() *cli.Command {
	return &cli.Command{
		Name:  "buildings",
		Usage: "Manage buildings commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"get",
				"Get a building by id",
				"/buildings.v1.BuildingService/GetBuilding",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "id", Usage: "id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &buildingsv1.GetBuildingRequest{}
					if cmd.IsSet("id") {
						req.Id = cmd.Int64("id")
					}
					return req, nil
				},
				func() proto.Message { return &buildingsv1.GetBuildingResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List buildings",
				"/buildings.v1.BuildingService/ListBuildings",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "site-ids", Usage: "site ids"},
					&cli.BoolFlag{Name: "include-unassigned", Usage: "include unassigned"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &buildingsv1.ListBuildingsRequest{}
					if cmd.IsSet("site-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("site-ids"))
						if err != nil {
							return nil, err
						}
						req.SiteIds = values
					}
					if cmd.IsSet("include-unassigned") {
						req.IncludeUnassigned = cmd.Bool("include-unassigned")
					}
					return req, nil
				},
				func() proto.Message { return &buildingsv1.ListBuildingsResponse{} },
			),
			generatedRequestCommand(
				"racks",
				"List racks assigned to a building",
				"/buildings.v1.BuildingService/ListBuildingRacks",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "building-id", Usage: "building id", Required: true},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &buildingsv1.ListBuildingRacksRequest{}
					if cmd.IsSet("building-id") {
						req.BuildingId = cmd.Int64("building-id")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &buildingsv1.ListBuildingRacksResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get building stats",
				"/buildings.v1.BuildingService/GetBuildingStats",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "building-id", Usage: "building id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &buildingsv1.GetBuildingStatsRequest{}
					if cmd.IsSet("building-id") {
						req.BuildingId = cmd.Int64("building-id")
					}
					return req, nil
				},
				func() proto.Message { return &buildingsv1.GetBuildingStatsResponse{} },
			),
		},
	}
}
