// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	alertsv1 "github.com/block/proto-fleet/server/generated/grpc/alerts/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedAlertsCommand() *cli.Command {
	return &cli.Command{
		Name:  "alerts",
		Usage: "Manage alerts commands",
		Commands: []*cli.Command{
			{
				Name:  "channels",
				Usage: "Manage channels commands",
				Commands: []*cli.Command{
					generatedRequestCommand(
						"create",
						"Create channel",
						"/alerts.v1.ChannelService/CreateChannel",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
							&cli.StringFlag{Name: "name", Usage: "name", Required: true},
							&cli.StringFlag{Name: "kind", Usage: "kind. Valid options: webhook, smtp, slack", Required: true},
							&cli.BoolFlag{Name: "webhook-bearer-stdin", Usage: "bearer header"},
							&cli.BoolFlag{Name: "smtp-password-stdin", Usage: "password"},
							&cli.BoolFlag{Name: "slack-webhook-stdin", Usage: "webhook url"},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.CreateChannelRequest{}
							if jsonPath := cmd.String("json"); jsonPath != "" {
								if err := readProtoJSON(jsonPath, req); err != nil {
									return nil, err
								}
							}
							if cmd.IsSet("name") {
								req.Name = cmd.String("name")
							}
							if cmd.IsSet("kind") {
								switch normalizeEnum(cmd.String("kind")) {
								case "webhook":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_WEBHOOK
								case "smtp":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_SMTP
								case "slack":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_SLACK
								default:
									return nil, fmt.Errorf("invalid value for kind: %s. Valid options: webhook, smtp, slack", cmd.String("kind"))
								}
							}
							if cmd.IsSet("webhook-bearer-stdin") {
								secretWebhookBearerHeader, err := generatedReadSecret(cmd, "webhook-bearer-stdin", "webhook bearer")
								if err != nil {
									return nil, err
								}
								if req.Webhook == nil {
									req.Webhook = &alertsv1.WebhookConfig{}
								}
								req.Webhook.BearerHeader = secretWebhookBearerHeader
							}
							if cmd.IsSet("smtp-password-stdin") {
								secretSmtpPassword, err := generatedReadSecret(cmd, "smtp-password-stdin", "smtp password")
								if err != nil {
									return nil, err
								}
								if req.Smtp == nil {
									req.Smtp = &alertsv1.SmtpConfig{}
								}
								req.Smtp.Password = secretSmtpPassword
							}
							if cmd.IsSet("slack-webhook-stdin") {
								secretSlackWebhookUrl, err := generatedReadSecret(cmd, "slack-webhook-stdin", "slack webhook")
								if err != nil {
									return nil, err
								}
								if req.Slack == nil {
									req.Slack = &alertsv1.SlackConfig{}
								}
								req.Slack.WebhookUrl = secretSlackWebhookUrl
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.CreateChannelResponse{} },
					),
					generatedRequestCommand(
						"delete",
						"Delete channel",
						"/alerts.v1.ChannelService/DeleteChannel",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "id", Usage: "id", Required: true},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.DeleteChannelRequest{}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.DeleteChannelResponse{} },
					),
					generatedRequestCommand(
						"list",
						"List channels",
						"/alerts.v1.ChannelService/ListChannels",
						generatedAuthSessionOnly,
						[]cli.Flag{
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.ListChannelsRequest{}
							return req, nil
						},
						func() proto.Message { return &alertsv1.ListChannelsResponse{} },
					),
					generatedRequestCommand(
						"test",
						"Test channel",
						"/alerts.v1.ChannelService/TestChannel",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
							&cli.StringFlag{Name: "id", Usage: "id"},
							&cli.StringFlag{Name: "kind", Usage: "kind. Valid options: webhook, smtp, slack"},
							&cli.BoolFlag{Name: "webhook-bearer-stdin", Usage: "bearer header"},
							&cli.BoolFlag{Name: "smtp-password-stdin", Usage: "password"},
							&cli.BoolFlag{Name: "slack-webhook-stdin", Usage: "webhook url"},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.TestChannelRequest{}
							if jsonPath := cmd.String("json"); jsonPath != "" {
								if err := readProtoJSON(jsonPath, req); err != nil {
									return nil, err
								}
							}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							if cmd.IsSet("kind") {
								switch normalizeEnum(cmd.String("kind")) {
								case "webhook":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_WEBHOOK
								case "smtp":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_SMTP
								case "slack":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_SLACK
								default:
									return nil, fmt.Errorf("invalid value for kind: %s. Valid options: webhook, smtp, slack", cmd.String("kind"))
								}
							}
							if cmd.IsSet("webhook-bearer-stdin") {
								secretWebhookBearerHeader, err := generatedReadSecret(cmd, "webhook-bearer-stdin", "webhook bearer")
								if err != nil {
									return nil, err
								}
								if req.Webhook == nil {
									req.Webhook = &alertsv1.WebhookConfig{}
								}
								req.Webhook.BearerHeader = secretWebhookBearerHeader
							}
							if cmd.IsSet("smtp-password-stdin") {
								secretSmtpPassword, err := generatedReadSecret(cmd, "smtp-password-stdin", "smtp password")
								if err != nil {
									return nil, err
								}
								if req.Smtp == nil {
									req.Smtp = &alertsv1.SmtpConfig{}
								}
								req.Smtp.Password = secretSmtpPassword
							}
							if cmd.IsSet("slack-webhook-stdin") {
								secretSlackWebhookUrl, err := generatedReadSecret(cmd, "slack-webhook-stdin", "slack webhook")
								if err != nil {
									return nil, err
								}
								if req.Slack == nil {
									req.Slack = &alertsv1.SlackConfig{}
								}
								req.Slack.WebhookUrl = secretSlackWebhookUrl
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.TestChannelResponse{} },
					),
					generatedRequestCommand(
						"update",
						"Update channel",
						"/alerts.v1.ChannelService/UpdateChannel",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
							&cli.StringFlag{Name: "id", Usage: "id", Required: true},
							&cli.StringFlag{Name: "name", Usage: "name", Required: true},
							&cli.StringFlag{Name: "kind", Usage: "kind. Valid options: webhook, smtp, slack", Required: true},
							&cli.BoolFlag{Name: "webhook-bearer-stdin", Usage: "bearer header"},
							&cli.BoolFlag{Name: "smtp-password-stdin", Usage: "password"},
							&cli.BoolFlag{Name: "slack-webhook-stdin", Usage: "webhook url"},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.UpdateChannelRequest{}
							if jsonPath := cmd.String("json"); jsonPath != "" {
								if err := readProtoJSON(jsonPath, req); err != nil {
									return nil, err
								}
							}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							if cmd.IsSet("name") {
								req.Name = cmd.String("name")
							}
							if cmd.IsSet("kind") {
								switch normalizeEnum(cmd.String("kind")) {
								case "webhook":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_WEBHOOK
								case "smtp":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_SMTP
								case "slack":
									req.Kind = alertsv1.ChannelKind_CHANNEL_KIND_SLACK
								default:
									return nil, fmt.Errorf("invalid value for kind: %s. Valid options: webhook, smtp, slack", cmd.String("kind"))
								}
							}
							if cmd.IsSet("webhook-bearer-stdin") {
								secretWebhookBearerHeader, err := generatedReadSecret(cmd, "webhook-bearer-stdin", "webhook bearer")
								if err != nil {
									return nil, err
								}
								if req.Webhook == nil {
									req.Webhook = &alertsv1.WebhookConfig{}
								}
								req.Webhook.BearerHeader = secretWebhookBearerHeader
							}
							if cmd.IsSet("smtp-password-stdin") {
								secretSmtpPassword, err := generatedReadSecret(cmd, "smtp-password-stdin", "smtp password")
								if err != nil {
									return nil, err
								}
								if req.Smtp == nil {
									req.Smtp = &alertsv1.SmtpConfig{}
								}
								req.Smtp.Password = secretSmtpPassword
							}
							if cmd.IsSet("slack-webhook-stdin") {
								secretSlackWebhookUrl, err := generatedReadSecret(cmd, "slack-webhook-stdin", "slack webhook")
								if err != nil {
									return nil, err
								}
								if req.Slack == nil {
									req.Slack = &alertsv1.SlackConfig{}
								}
								req.Slack.WebhookUrl = secretSlackWebhookUrl
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.UpdateChannelResponse{} },
					),
				},
			},
			{
				Name:  "history",
				Usage: "Manage history commands",
				Commands: []*cli.Command{
					generatedRequestCommand(
						"list",
						"List alerts",
						"/alerts.v1.HistoryService/ListAlerts",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "before-id", Usage: "before id"},
							&cli.IntFlag{Name: "page-size", Usage: "page size"},
							&cli.BoolFlag{Name: "active-only", Usage: "active only"},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.ListAlertsRequest{}
							if cmd.IsSet("before-id") {
								req.BeforeId = cmd.String("before-id")
							}
							if cmd.IsSet("page-size") {
								req.PageSize = int32(cmd.Int("page-size"))
							}
							if cmd.IsSet("active-only") {
								req.ActiveOnly = cmd.Bool("active-only")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.ListAlertsResponse{} },
					),
				},
			},
			{
				Name:  "maintenance-windows",
				Usage: "Manage maintenance windows commands",
				Commands: []*cli.Command{
					generatedRequestCommand(
						"create",
						"Create maintenance window",
						"/alerts.v1.MaintenanceWindowService/CreateMaintenanceWindow",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
							&cli.StringFlag{Name: "comment", Usage: "comment"},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.CreateMaintenanceWindowRequest{}
							if jsonPath := cmd.String("json"); jsonPath != "" {
								if err := readProtoJSON(jsonPath, req); err != nil {
									return nil, err
								}
							}
							if cmd.IsSet("comment") {
								req.Comment = cmd.String("comment")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.CreateMaintenanceWindowResponse{} },
					),
					generatedRequestCommand(
						"delete",
						"Delete maintenance window",
						"/alerts.v1.MaintenanceWindowService/DeleteMaintenanceWindow",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "id", Usage: "id", Required: true},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.DeleteMaintenanceWindowRequest{}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.DeleteMaintenanceWindowResponse{} },
					),
					generatedRequestCommand(
						"list",
						"List maintenance windows",
						"/alerts.v1.MaintenanceWindowService/ListMaintenanceWindows",
						generatedAuthSessionOnly,
						[]cli.Flag{
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.ListMaintenanceWindowsRequest{}
							return req, nil
						},
						func() proto.Message { return &alertsv1.ListMaintenanceWindowsResponse{} },
					),
					generatedRequestCommand(
						"update",
						"Update maintenance window",
						"/alerts.v1.MaintenanceWindowService/UpdateMaintenanceWindow",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
							&cli.StringFlag{Name: "id", Usage: "id", Required: true},
							&cli.StringFlag{Name: "comment", Usage: "comment"},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.UpdateMaintenanceWindowRequest{}
							if jsonPath := cmd.String("json"); jsonPath != "" {
								if err := readProtoJSON(jsonPath, req); err != nil {
									return nil, err
								}
							}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							if cmd.IsSet("comment") {
								req.Comment = cmd.String("comment")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.UpdateMaintenanceWindowResponse{} },
					),
				},
			},
			{
				Name:  "rules",
				Usage: "Manage rules commands",
				Commands: []*cli.Command{
					generatedRequestCommand(
						"list",
						"List rules",
						"/alerts.v1.RuleService/ListRules",
						generatedAuthSessionOnly,
						[]cli.Flag{
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.ListRulesRequest{}
							return req, nil
						},
						func() proto.Message { return &alertsv1.ListRulesResponse{} },
					),
					generatedRequestCommand(
						"pause",
						"Pause rule",
						"/alerts.v1.RuleService/PauseRule",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "id", Usage: "id", Required: true},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.PauseRuleRequest{}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.PauseRuleResponse{} },
					),
					generatedRequestCommand(
						"resume",
						"Resume rule",
						"/alerts.v1.RuleService/ResumeRule",
						generatedAuthSessionOnly,
						[]cli.Flag{
							&cli.StringFlag{Name: "id", Usage: "id", Required: true},
						},
						func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
							req := &alertsv1.ResumeRuleRequest{}
							if cmd.IsSet("id") {
								req.Id = cmd.String("id")
							}
							return req, nil
						},
						func() proto.Message { return &alertsv1.ResumeRuleResponse{} },
					),
				},
			},
		},
	}
}
