// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"
	collectionv1 "github.com/block/proto-fleet/server/generated/grpc/collection/v1"
	devicesetv1 "github.com/block/proto-fleet/server/generated/grpc/device_set/v1"
	cli "github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedRacksCommand() *cli.Command {
	return &cli.Command{
		Name:  "racks",
		Usage: "Manage racks commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to a rack",
				"/device_set.v1.DeviceSetService/AssignDevicesToRack",
				generatedAuthAuthenticated,
				append([]cli.Flag{
					&cli.Int64Flag{Name: "target-rack-id", Usage: "target rack id", Required: true},
					&cli.BoolFlag{Name: "force-clear-conflicting-site", Usage: "force clear conflicting site"},
				}, generatedCommonDeviceListSelectorFlags()...),
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &devicesetv1.AssignDevicesToRackRequest{}
					selector, err := generatedBuildCommonDeviceListSelector(cmd)
					if err != nil {
						return nil, err
					}
					req.DeviceSelector = selector
					if cmd.IsSet("target-rack-id") {
						value := cmd.Int64("target-rack-id")
						req.TargetRackId = &value
					}
					if cmd.IsSet("force-clear-conflicting-site") {
						value := cmd.Bool("force-clear-conflicting-site")
						req.ForceClearConflictingSite = &value
					}
					if req.TargetRackId != nil {
						if err := generatedRequireCollectionType(ctx, client, *req.TargetRackId, collectionv1.CollectionType_COLLECTION_TYPE_RACK); err != nil {
							return nil, err
						}
					}
					return req, nil
				},
				func() proto.Message { return &devicesetv1.AssignDevicesToRackResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete a rack",
				"/collection.v1.DeviceCollectionService/DeleteCollection",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.DeleteCollectionRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					if err := generatedRequireCollectionType(ctx, client, req.CollectionId, collectionv1.CollectionType_COLLECTION_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.DeleteCollectionResponse{} },
			),
			generatedRequestCommand(
				"device",
				"List racks for a device identifier",
				"/collection.v1.DeviceCollectionService/GetDeviceCollections",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "device-identifier", Usage: "device identifier"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetDeviceCollectionsRequest{}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_RACK
					if cmd.IsSet("device-identifier") {
						req.DeviceIdentifier = cmd.String("device-identifier")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetDeviceCollectionsResponse{} },
			),
			generatedRequestCommand(
				"get",
				"Get a rack by id",
				"/collection.v1.DeviceCollectionService/GetCollection",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetCollectionRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					if err := generatedRequireCollectionType(ctx, client, req.CollectionId, collectionv1.CollectionType_COLLECTION_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetCollectionResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List racks",
				"/collection.v1.DeviceCollectionService/ListCollections",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringSliceFlag{Name: "zones", Usage: "zones"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListCollectionsRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					req.Type = collectionv1.CollectionType_COLLECTION_TYPE_RACK
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("zones") {
						req.Zones = cmd.StringSlice("zones")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListCollectionsResponse{} },
			),
			generatedRequestCommand(
				"members",
				"List rack members",
				"/collection.v1.DeviceCollectionService/ListCollectionMembers",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListCollectionMembersRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if err := generatedRequireCollectionType(ctx, client, req.CollectionId, collectionv1.CollectionType_COLLECTION_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListCollectionMembersResponse{} },
			),
			generatedRequestCommand(
				"save",
				"Create or update a rack",
				"/collection.v1.DeviceCollectionService/SaveRack",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.SaveRackRequest{}
					if err := readProtoJSON(cmd.String("json"), req); err != nil {
						return nil, err
					}
					if req.CollectionId != nil {
						if err := generatedRequireCollectionType(ctx, client, *req.CollectionId, collectionv1.CollectionType_COLLECTION_TYPE_RACK); err != nil {
							return nil, err
						}
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.SaveRackResponse{} },
			),
			generatedRequestCommand(
				"slots",
				"List occupied rack slots",
				"/collection.v1.DeviceCollectionService/GetRackSlots",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "collection-id", Usage: "collection id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetRackSlotsRequest{}
					if cmd.IsSet("collection-id") {
						req.CollectionId = cmd.Int64("collection-id")
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetRackSlotsResponse{} },
			),
			generatedRequestCommand(
				"stats",
				"Get aggregated stats for one or more racks",
				"/collection.v1.DeviceCollectionService/GetCollectionStats",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringSliceFlag{Name: "collection-ids", Usage: "collection ids"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.GetCollectionStatsRequest{}
					if cmd.IsSet("collection-ids") {
						values, err := parseInt64Slice(cmd.StringSlice("collection-ids"))
						if err != nil {
							return nil, err
						}
						req.CollectionIds = values
					}
					if err := generatedRequireCollectionTypes(ctx, client, req.CollectionIds, collectionv1.CollectionType_COLLECTION_TYPE_RACK); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &collectionv1.GetCollectionStatsResponse{} },
			),
			generatedRequestCommand(
				"types",
				"List all rack layouts",
				"/collection.v1.DeviceCollectionService/ListRackTypes",
				generatedAuthAuthenticated,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListRackTypesRequest{}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListRackTypesResponse{} },
			),
			generatedRequestCommand(
				"zones",
				"List all rack zones",
				"/collection.v1.DeviceCollectionService/ListRackZones",
				generatedAuthAuthenticated,
				[]cli.Flag{
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &collectionv1.ListRackZonesRequest{}
					return req, nil
				},
				func() proto.Message { return &collectionv1.ListRackZonesResponse{} },
			),
		},
	}
}
