// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import "github.com/urfave/cli/v3"

func generatedCommands() []*cli.Command {
	return []*cli.Command{
		generatedActivityCommand(),
		generatedBuildingsCommand(),
		generatedErrorsCommand(),
		generatedGroupsCommand(),
		generatedMinersCommand(),
		generatedOnboardingCommand(),
		generatedPoolsCommand(),
		generatedRacksCommand(),
		generatedServerlogsCommand(),
		generatedSitesCommand(),
	}
}

func allCommands() []*cli.Command {
	return append(manualCommands(), generatedCommands()...)
}
