// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"

	activityv1 "github.com/block/proto-fleet/server/generated/grpc/activity/v1"
	"github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedActivityCommand() *cli.Command {
	return &cli.Command{
		Name:  "activity",
		Usage: "Manage activity commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"filters",
				"List available activity filter options",
				"/activity.v1.ActivityService/ListActivityFilterOptions",
				generatedAuthAuthenticated,
				[]cli.Flag{},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &activityv1.ListActivityFilterOptionsRequest{}
					return req, nil
				},
				func() proto.Message { return &activityv1.ListActivityFilterOptionsResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List activity entries",
				"/activity.v1.ActivityService/ListActivities",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "Path to a request JSON file, or - for stdin"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &activityv1.ListActivitiesRequest{}
					if jsonPath := cmd.String("json"); jsonPath != "" {
						if err := readProtoJSON(jsonPath, req); err != nil {
							return nil, err
						}
					}
					if req.PageSize == 0 {
						req.PageSize = int32(100)
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					return req, nil
				},
				func() proto.Message { return &activityv1.ListActivitiesResponse{} },
			),
		},
	}
}
