// Code generated by server/tools/generate-fleet-cli; DO NOT EDIT.

package main

import (
	"context"

	minerchannelv1 "github.com/block/proto-fleet/server/generated/grpc/minerchannel/v1"
	cli "github.com/urfave/cli/v3"
	proto "google.golang.org/protobuf/proto"
)

func generatedMinerChannelsCommand() *cli.Command {
	return &cli.Command{
		Name:  "miner-channels",
		Usage: "Manage miner channels commands",
		Commands: []*cli.Command{
			generatedRequestCommand(
				"add-devices",
				"Add devices to miner channel",
				"/minerchannel.v1.MinerChannelService/AddDevicesToMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "(required) device identifiers", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.AddDevicesToMinerChannelRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.AddDevicesToMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"admin-reassign",
				"Admin reassign",
				"/minerchannel.v1.MinerChannelService/AdminReassign",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "target-miner-channel-id", Usage: "(required) target miner channel id", Required: true},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "(required) device identifiers", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.AdminReassignRequest{}
					if cmd.IsSet("target-miner-channel-id") {
						req.TargetMinerChannelId = cmd.Int64("target-miner-channel-id")
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.AdminReassignResponse{} },
			),
			generatedRequestCommand(
				"admin-release",
				"Admin release miner channel",
				"/minerchannel.v1.MinerChannelService/AdminReleaseMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.AdminReleaseMinerChannelRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.AdminReleaseMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"create",
				"Create miner channel",
				"/minerchannel.v1.MinerChannelService/CreateMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "(required) Path to a request JSON file, or - for stdin", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.CreateMinerChannelRequest{}
					if err := readProtoJSON(cmd.String("json"), req); err != nil {
						return nil, err
					}
					if err := generatedValidateRequiredFields(req, "label", "purpose"); err != nil {
						return nil, err
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.CreateMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"delete",
				"Delete miner channel",
				"/minerchannel.v1.MinerChannelService/DeleteMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.DeleteMinerChannelRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.DeleteMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"extend",
				"Update miner channel",
				"/minerchannel.v1.MinerChannelService/UpdateMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "(required) Path to a request JSON file, or - for stdin", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.UpdateMinerChannelRequest{}
					if err := readProtoJSON(cmd.String("json"), req); err != nil {
						return nil, err
					}
					if err := generatedValidateRequiredFields(req, "miner_channel_id"); err != nil {
						return nil, err
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.UpdateMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"list",
				"List miner channels",
				"/minerchannel.v1.MinerChannelService/ListMinerChannels",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.BoolFlag{Name: "include-released", Usage: "include released"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringFlag{Name: "search", Usage: "search"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.ListMinerChannelsRequest{}
					if cmd.IsSet("include-released") {
						req.IncludeReleased = cmd.Bool("include-released")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("search") {
						req.Search = cmd.String("search")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.ListMinerChannelsResponse{} },
			),
			generatedRequestCommand(
				"my",
				"Get my miner channels",
				"/minerchannel.v1.MinerChannelService/GetMyMinerChannels",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.BoolFlag{Name: "include-released", Usage: "include released"},
					&cli.IntFlag{Name: "page-size", Usage: "page size"},
					&cli.StringFlag{Name: "page-token", Usage: "page token"},
					&cli.StringFlag{Name: "search", Usage: "search"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.GetMyMinerChannelsRequest{}
					if cmd.IsSet("include-released") {
						req.IncludeReleased = cmd.Bool("include-released")
					}
					if cmd.IsSet("page-size") {
						req.PageSize = int32(cmd.Int("page-size"))
					}
					if cmd.IsSet("page-token") {
						req.PageToken = cmd.String("page-token")
					}
					if cmd.IsSet("search") {
						req.Search = cmd.String("search")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.GetMyMinerChannelsResponse{} },
			),
			generatedRequestCommand(
				"release",
				"Release miner channel",
				"/minerchannel.v1.MinerChannelService/ReleaseMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.ReleaseMinerChannelRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.ReleaseMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"remove-devices",
				"Remove devices from miner channel",
				"/minerchannel.v1.MinerChannelService/RemoveDevicesFromMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
					&cli.StringSliceFlag{Name: "device-identifiers", Usage: "(required) device identifiers", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.RemoveDevicesFromMinerChannelRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if cmd.IsSet("device-identifiers") {
						req.DeviceIdentifiers = cmd.StringSlice("device-identifiers")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.RemoveDevicesFromMinerChannelResponse{} },
			),
			generatedRequestCommand(
				"rigs",
				"List devices",
				"/minerchannel.v1.MinerChannelService/ListDevices",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.StringFlag{Name: "json", Usage: "(required) Path to a request JSON file, or - for stdin", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.ListDevicesRequest{}
					if err := readProtoJSON(cmd.String("json"), req); err != nil {
						return nil, err
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.ListDevicesResponse{} },
			),
			generatedRequestCommand(
				"set-firmware-target",
				"Set miner channel firmware target",
				"/minerchannel.v1.MinerChannelService/SetMinerChannelFirmwareTarget",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
					&cli.StringFlag{Name: "manufacturer", Usage: "manufacturer"},
					&cli.StringFlag{Name: "model", Usage: "model"},
					&cli.StringFlag{Name: "firmware-file-id", Usage: "firmware file id"},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.SetMinerChannelFirmwareTargetRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if cmd.IsSet("manufacturer") {
						value := cmd.String("manufacturer")
						req.Manufacturer = &value
					}
					if cmd.IsSet("model") {
						value := cmd.String("model")
						req.Model = &value
					}
					if cmd.IsSet("firmware-file-id") {
						value := cmd.String("firmware-file-id")
						req.FirmwareFileId = &value
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.SetMinerChannelFirmwareTargetResponse{} },
			),
			generatedRequestCommand(
				"status",
				"Get miner channel",
				"/minerchannel.v1.MinerChannelService/GetMinerChannel",
				generatedAuthAuthenticated,
				[]cli.Flag{
					&cli.Int64Flag{Name: "miner-channel-id", Usage: "(required) miner channel id", Required: true},
				},
				func(ctx context.Context, cmd *cli.Command, client *Client) (proto.Message, error) {
					req := &minerchannelv1.GetMinerChannelRequest{}
					if cmd.IsSet("miner-channel-id") {
						req.MinerChannelId = cmd.Int64("miner-channel-id")
					}
					if err := generatedValidateRequest(req); err != nil {
						return nil, err
					}
					return req, nil
				},
				func() proto.Message { return &minerchannelv1.GetMinerChannelResponse{} },
			),
		},
	}
}
