// Code generated by cmd/generate/main.go. DO NOT EDIT.
// Source: miner-firmware/crates/miner_utils/src/error_details.rs

package errors

// GetGeneratedErrorDefinitions returns error definitions generated from Rust source
// These match the ErrorDetails enum in miner-firmware
func GetGeneratedErrorDefinitions() []ErrorDefinition {
	return []ErrorDefinition{
		{
			Code:         "AsicOverTemp",
			Name:         "Asic Over Temp",
			Description:  "ASIC temperature exceeds safe operating limits",
			Category:     "ASIC",
			// DefaultLevel: "Warning",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "asic_index", Type: "number", Required: true, Description: "ASIC index"},
				{Name: "temperature", Type: "number", Required: true, Description: "Temperature in Celsius"},
			},
		},
		{
			Code:         "AsicUnderTemp",
			Name:         "Asic Under Temp",
			Description:  "ASIC temperature is below minimum operating threshold",
			Category:     "ASIC",
			// DefaultLevel: "Warning",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "asic_index", Type: "number", Required: true, Description: "ASIC index"},
				{Name: "temperature", Type: "number", Required: true, Description: "Temperature in Celsius"},
			},
		},
		{
			Code:         "AsicOverVoltage",
			Name:         "Asic Over Voltage",
			Description:  "ASIC voltage exceeds safe operating limits",
			Category:     "ASIC",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "asic_index", Type: "number", Required: true, Description: "ASIC index"},
				{Name: "voltage", Type: "number", Required: true, Description: "Voltage"},
			},
		},
		{
			Code:         "AsicUnderVoltage",
			Name:         "Asic Under Voltage",
			Description:  "ASIC voltage is below minimum operating threshold",
			Category:     "ASIC",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "asic_index", Type: "number", Required: true, Description: "ASIC index"},
				{Name: "voltage", Type: "number", Required: true, Description: "Voltage"},
			},
		},
		{
			Code:         "AsicEcc",
			Name:         "Asic Ecc",
			Description:  "ASIC ECC errors detected",
			Category:     "ASIC",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
			},
		},
		{
			Code:         "AsicEnumeration",
			Name:         "Asic Enumeration",
			Description:  "Failed to enumerate expected number of ASICs",
			Category:     "ASIC",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
			},
		},
		{
			Code:         "AsicNotHashing",
			Name:         "Asic Not Hashing",
			Description:  "One or more ASICs are not producing valid hashes",
			Category:     "ASIC",
			// DefaultLevel: "Warning",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "asics", Type: "array", Required: true, Description: "Array of ASIC indices"},
			},
		},
		{
			Code:         "FanSlow",
			Name:         "Fan Slow",
			Description:  "Fan RPM is below expected speed",
			Category:     "Cooling",
			// DefaultLevel: "Warning",
			Parameters: []ParameterDefinition{
				{Name: "fan_bay_index", Type: "number", Required: true, Description: "Fan bay index"},
				{Name: "fan_id", Type: "number", Required: true, Description: "Fan identifier"},
				{Name: "fan_pwm_target_pct", Type: "number", Required: true, Description: "Target PWM percentage"},
				{Name: "fan_rpm_tach", Type: "number", Required: true, Description: "Actual fan RPM from tachometer"},
			},
		},
		{
			Code:         "FanNotSpinning",
			Name:         "Fan Not Spinning",
			Description:  "Fan has stopped spinning",
			Category:     "Cooling",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "fan_bay_index", Type: "number", Required: true, Description: "Fan bay index"},
				{Name: "fan_id", Type: "number", Required: true, Description: "Fan identifier"},
				{Name: "fan_pwm_target_pct", Type: "number", Required: true, Description: "Target PWM percentage"},
				{Name: "fan_rpm_tach", Type: "number", Required: true, Description: "Actual fan RPM from tachometer"},
			},
		},
		{
			Code:         "FanConnectedInImmersion",
			Name:         "Fan Connected In Immersion",
			Description:  "Fan connected while in immersion cooling mode",
			Category:     "Cooling",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "fan_bay_index", Type: "number", Required: true, Description: "Fan bay index"},
				{Name: "fan_id", Type: "number", Required: true, Description: "Fan identifier"},
			},
		},
		{
			Code:         "HashboardOverheat",
			Name:         "Hashboard Overheat",
			Description:  "Hashboard temperature exceeds safe operating limits",
			Category:     "Hashboard",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "temperature", Type: "number", Required: true, Description: "Temperature in Celsius"},
			},
		},
		{
			Code:         "HashboardOverVoltage",
			Name:         "Hashboard Over Voltage",
			Description:  "Hashboard voltage exceeds safe operating limits",
			Category:     "Hashboard",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "voltage", Type: "number", Required: true, Description: "Voltage"},
			},
		},
		{
			Code:         "HashboardUnderVoltage",
			Name:         "Hashboard Under Voltage",
			Description:  "Hashboard voltage is below minimum operating threshold",
			Category:     "Hashboard",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "voltage", Type: "number", Required: true, Description: "Voltage"},
			},
		},
		{
			Code:         "HashboardOverCurrent",
			Name:         "Hashboard Over Current",
			Description:  "Hashboard current exceeds safe operating limits",
			Category:     "Hashboard",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "current", Type: "number", Required: true, Description: "Current in Amperes"},
			},
		},
		{
			Code:         "HashboardPowerLost",
			Name:         "Hashboard Power Lost",
			Description:  "Hashboard has lost power",
			Category:     "Hashboard",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
			},
		},
		{
			Code:         "HashboardUsbConnectionLost",
			Name:         "Hashboard Usb Connection Lost",
			Description:  "Lost USB connection to hashboard",
			Category:     "Hashboard",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
			},
		},
		{
			Code:         "PoolConnectionLost",
			Name:         "Pool Connection Lost",
			Description:  "Lost connection to mining pool",
			Category:     "Pool",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "pool_id", Type: "number", Required: true, Description: "Pool identifier"},
				{Name: "pool_url", Type: "string", Required: true, Description: "Pool URL"},
			},
		},
		{
			Code:         "NoPoolConfigured",
			Name:         "No Pool Configured",
			Description:  "No mining pool has been configured",
			Category:     "Pool",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
			},
		},
		{
			Code:         "PsuHardwareFault",
			Name:         "Psu Hardware Fault",
			Description:  "Power supply unit has detected a hardware fault",
			Category:     "PSU",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "fault", Type: "object", Required: true, Description: "Fault information"},
				{Name: "psu_bay_index", Type: "number", Required: true, Description: "PSU bay index"},
				{Name: "psu_index", Type: "number", Required: true, Description: "PSU index"},
				{Name: "psu_sn", Type: "string", Required: true, Description: "PSU serial number"},
			},
		},
		{
			Code:         "PsuCommsLost",
			Name:         "Psu Comms Lost",
			Description:  "Lost communication with power supply unit",
			Category:     "PSU",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "psu_bay_index", Type: "number", Required: true, Description: "PSU bay index"},
				{Name: "psu_index", Type: "number", Required: true, Description: "PSU index"},
				{Name: "psu_sn", Type: "string", Required: true, Description: "PSU serial number"},
			},
		},
		{
			Code:         "MixedHashboardTypesInBay",
			Name:         "Mixed Hashboard Types In Bay",
			Description:  "Different hashboard types detected in the same system",
			Category:     "System",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "hashboards", Type: "array", Required: true, Description: "List of hashboard information"},
			},
		},
		{
			Code:         "InsufficientCooling",
			Name:         "Insufficient Cooling",
			Description:  "Not enough operational fans for adequate cooling",
			Category:     "Cooling",
			// DefaultLevel: "Error",
			Parameters: []ParameterDefinition{
				{Name: "bay_index", Type: "number", Required: true, Description: "Bay index"},
				{Name: "num_operational_fans", Type: "number", Required: true, Description: "Number of operational fans"},
				{Name: "num_expected_fans", Type: "number", Required: true, Description: "Number of expected fans"},
				{Name: "failed_fans", Type: "array", Required: true, Description: "Array of failed fan IDs"},
				{Name: "required_fans", Type: "array", Required: true, Description: "Array of required fan IDs"},
			},
		},
		{
			Code:         "PsuRecoveryInProgress",
			Name:         "Psu Recovery In Progress",
			Description:  "PSU recovery in progress",
			Category:     "PSU",
			// DefaultLevel: "Warning",
			Parameters: []ParameterDefinition{
				{Name: "psu_bay_index", Type: "number", Required: true, Description: "PSU bay index"},
				{Name: "psu_index", Type: "number", Required: true, Description: "PSU index"},
				{Name: "psu_sn", Type: "string", Required: true, Description: "PSU serial number"},
				{Name: "faults", Type: "array", Required: true, Description: "List of fault types"},
			},
		},
		{
			Code:         "HbRecoveryInProgress",
			Name:         "Hb Recovery In Progress",
			Description:  "Hashboard recovery in progress",
			Category:     "Hashboard",
			// DefaultLevel: "Warning",
			Parameters: []ParameterDefinition{
				{Name: "hb_slot", Type: "number", Required: true, Description: "Hashboard slot number"},
				{Name: "hb_sn", Type: "string", Required: true, Description: "Hashboard serial number"},
				{Name: "errors", Type: "array", Required: true, Description: "List of error types"},
			},
		},
	}
}

// GetAllErrorDefinitions combines hardcoded and generated definitions
func GetAllErrorDefinitions() []ErrorDefinition {
	// Start with generated definitions
	defs := GetGeneratedErrorDefinitions()

	// Add any custom definitions that aren't in the Rust source
	// (currently none, but this allows for extension)

	return defs
}
